import { tinyStoriesBeginnerGuidance } from './tinystories-beginner-guidance';
import { sqlBeginnerGuidance } from './sql-beginner-guidance';

export type BeginnerSectionGuide = {
  why: string;
  mechanism: string;
  analogy: string;
  boundary?: string;
};

export type BeginnerGuide = {
  background: string;
  picture: string;
  misconception: string;
  goal: string;
  notes: Record<string, BeginnerSectionGuide>;
};

const note = (why: string, mechanism: string, analogy: string, boundary?: string): BeginnerSectionGuide => ({ why, mechanism, analogy, boundary });

export const beginnerGuidance: Record<string, BeginnerGuide> = {
  ...tinyStoriesBeginnerGuidance,
  ...sqlBeginnerGuidance,
  'lab-setup': {
    background: 'Training a model is not one mysterious program. It is a chain of ordinary jobs: fetch text, turn it into numbers, run mathematical operations, adjust stored numbers, save results, and display evidence. The setup in this lesson gives each job a known tool and a known place so later results can be explained and repeated.',
    picture: 'Think of preparing a teaching laboratory. Python is the language on the instruction cards, MLX supplies the numerical equipment, the Apple GPU performs many calculations together, and the wiki is the lab notebook that connects actions to observations.',
    misconception: 'Installing an AI library does not install intelligence or a ready-made Shakespeare model. MLX provides mathematical building blocks; the knowledge will come only from training on data.',
    goal: 'Be able to point to the tool that runs each part of the project and explain why recording versions and commands is part of the experiment.',
    notes: {
      'why-a-lab': note('A result is only useful if we can tell what produced it. Otherwise a lower loss might come from changed data, changed code, or a different library rather than the idea we meant to test.', 'The project records source code, package versions, hardware, settings, random seeds, data provenance, checkpoints, and measurements. Together these form the conditions of the experiment.', 'A cake labelled “best so far” is not reproducible unless the recipe also records the ingredients, quantities, oven, temperature, and cooking time. The model score is the cake; the project records are the recipe.'),
      'tooling-installed': note('Several tools appear because model training and webpage display are different kinds of work. Knowing their boundaries makes errors less mysterious.', 'Python runs the training scripts. MLX represents arrays and calculates gradients efficiently on Apple silicon. Vinext and React render this wiki in a browser. Git records deliberate changes to code and lessons.', 'A small theatre needs a playwright, stage machinery, front-of-house staff, and an archive. They contribute to one production, but each has a distinct responsibility.', 'The tools coordinate a computation; none of them understands the text or decides what should be learned.'),
      'environment-command': note('Software packages change. If an experiment silently uses a different version later, the same code can behave differently or stop working.', 'A virtual environment creates a project-specific Python interpreter and package directory. Activating it makes commands resolve those pinned packages instead of unrelated system copies.', 'It is a sealed tool case labelled for this project: replacing a screwdriver in another case does not alter this one.', 'The environment isolates Python packages, not the dataset, operating system, or every source of numerical variation.'),
      'project-shape': note('A beginner should be able to trace evidence from the displayed claim back to the script and saved output that produced it.', 'Raw data enters through data folders; scripts transform and train; experiment folders preserve configurations and checkpoints; public data feeds measured results to the interface; lesson files explain the chain.', 'Imagine labelled stations on a factory line. Raw material, machinery, quality records, finished parts, and the visitor display are kept separate so an item can be traced.', 'Folders create order, but they do not prove correctness. We still verify that each file contains what its label claims.'),
      'live-refresh': note('Training can take time, so the learner needs evidence that work is progressing without restarting the page or guessing from terminal noise.', 'The trainer periodically writes a small results file. Browser code requests that file again on a timer; when its values change, React redraws the affected panel.', 'It resembles a departures board reading a timetable database every few seconds. The board is not driving the trains; it is reporting their latest recorded state.', 'A fresh-looking dashboard can still display bad measurements. Refreshing solves visibility, not scientific validity.'),
    },
  },
  'data-and-tokenisation': {
    background: 'A neural network accepts numbers, not written characters. Before learning can begin, we must decide what pieces of text exist, assign each piece an integer name, and create examples in which earlier pieces are the question and the following piece is the answer.',
    picture: 'Imagine dismantling a book into a box of reusable tiles. For this first project every distinct character is one tile; tokenisation defines the tile set and encoding replaces the book with tile numbers.',
    misconception: 'Token IDs do not contain meaning. The number 42 is merely a label, like a coat-check ticket; the model must learn useful relationships involving that label.',
    goal: 'Trace visible Shakespeare text into token IDs, training questions, and withheld validation questions without treating tokenisation as learning.',
    notes: {
      download: note('The model can only learn patterns present in its source material, so we must know exactly what text entered the experiment.', 'A script downloads one known Tiny Shakespeare file and records its origin. We inspect its size and characters before any model sees it.', 'It is choosing the exact textbook edition for a class and writing its ISBN in the course notes.', 'Provenance tells us where data came from; it does not guarantee that the text is complete, unbiased, or suitable for every purpose.'),
      'characters-as-tokens': note('The choice of text pieces determines what the model can see and how many prediction steps a sentence requires.', 'We collect every distinct character to form a vocabulary of 65 tokens. Spaces, punctuation, capital letters, and line breaks receive separate entries because each can be predicted next.', 'A typesetter keeps one compartment for every symbol it may place. Writing a line means selecting compartments one after another.', 'Unlike Scrabble tiles, token IDs have no built-in letter value or meaning; their useful numeric representations are learned later.'),
      encode: note('The mathematical model needs a stable numeric representation of the text before it can index tables or form tensors.', 'An encoder looks up each character in the vocabulary and emits its integer ID. A decoder performs the reverse lookup, allowing generated IDs to become readable text again.', 'A cloakroom swaps each coat for a numbered ticket and later uses the ticket to retrieve the same coat. The number identifies; it does not describe.', 'Encoding is lossless here only because every corpus character is in the vocabulary. It has not compressed meaning or taught the model language.'),
      split: note('We need questions the optimiser never practises on, otherwise memorising the workbook could look like genuine improvement.', 'The first 90% of token IDs supplies training examples. The final 10% is validation data: it is used for scoring during development but never for gradient updates.', 'A teacher keeps one set of exam questions locked away while lessons use a separate workbook.', 'Validation is not a perfectly untouched final test because we use its scores to choose later experiments. It is still much more honest than scoring only the training text.'),
      batches: note('One long token stream must become many small prediction exercises that fit the model’s context and can be processed efficiently together.', 'For selected starting positions, the input contains a run of tokens and the target contains the same run shifted one place left. Thus every position asks for its actual successor. Several such sequences form one batch.', 'Slide a transparent window along a sentence: the upper row shows clues and the lower row shows the answer one square later. Stacking several windows creates a worksheet.', 'A batch is a computational grouping, not a topic or chapter. Examples in one batch do not share knowledge directly.'),
    },
  },
  'random-baseline': {
    background: 'A model architecture is the arrangement of calculations; its weights are the adjustable numbers inside that arrangement. We can run the architecture immediately after filling its weights with random values. That output is intentionally poor and gives us a before-training reference.',
    picture: 'Picture a 65-row lookup board. The current character selects one row, and the 65 random numbers in that row are initial preferences for every possible next character.',
    misconception: 'Random initialisation is not a crude database of Shakespeare or a miniature pretrained model. It is simply a non-identical starting position from which training can adjust the weights.',
    goal: 'Separate constructing, invoking, sampling from, and training a model—and explain why the random output is valuable evidence.',
    notes: {
      architecture: note('This tiny architecture exposes the core language-model interface without transformer complexity: input token IDs go in and one score per possible next token comes out.', 'The current character ID selects one row of a 65 × 65 weight table. That row contains 65 logits, one for each candidate next character.', 'It resembles a book of answer sheets indexed by the last character seen. Each sheet has a pencil mark beside every possible next character.', 'The sheet has no memory beyond the current character and performs no reasoning; it is only a learned conditional lookup.'),
      'random-weights': note('If every weight started identically, many parts of a larger network would receive identical signals and remain indistinguishable. Small random differences let training discover different roles.', 'MLX’s pseudo-random generator fills the weight table from a numerical distribution determined by a recorded seed. The same seed recreates the same initial table.', 'Runners begin on slightly different marked lanes so we can observe and adjust them separately.', 'Randomness supplies variation, not useful knowledge. A seed makes the variation repeatable, not intrinsically fair or representative.'),
      invoke: note('“Running” a model is often confused with training it. Invocation is only the forward calculation used both before and after training.', 'The code encodes a prompt, passes token IDs through the current weights, and receives logits. Unless loss, gradients, and an optimiser update follow, no weight changes.', 'Asking a student a question reveals the current answer; it does not teach the student unless feedback and correction occur afterward.', 'The model is not consciously answering. It deterministically calculates scores, followed by optional random sampling.'),
      sample: note('Logits are unrestricted scores, so we need a rule that turns them into a legal probability distribution and chooses one continuation.', 'Softmax exponentiates and normalises the 65 scores so they are non-negative and total 1. Sampling draws one token according to those probabilities, appends it, and repeats.', 'Each score buys a differently sized slice of a roulette wheel; spinning selects a slice, then a new wheel is calculated for the next character.', 'The wheel image is useful for probability, but software uses pseudo-random numbers rather than a physical spinner.'),
      limits: note('A baseline’s limitation tells us what capability the next architecture must add.', 'Because its logits depend only on the current character ID, two prompts ending in the same character always produce the same probability distribution, regardless of everything before it.', 'It is like completing every sentence while allowed to see only its final letter. “the” and “time” both ending in e become indistinguishable.', 'More training can improve pair frequencies, but cannot overcome information that the architecture never receives.'),
    },
  },
  'bigram-training': {
    background: 'Training is a repeated numerical correction process. The model predicts; a loss function compares the prediction with the known next character; automatic differentiation measures how each weight affected that loss; an optimiser makes a small update. Thousands of repetitions shape random values into useful statistical preferences.',
    picture: 'Imagine a control panel with thousands of dials. Each practice round produces an error score and an arrow beside every dial; the optimiser uses those arrows to make coordinated, small turns.',
    misconception: 'The training text is not copied into one hidden file and retrieved later. Its repeated examples gradually alter weights, distributing statistical patterns across numbers.',
    goal: 'Explain the complete loss → gradient → optimiser → updated-weight loop and why validation evidence matters.',
    notes: {
      command: note('An experiment command is part of the evidence because options and script version determine what work actually ran.', 'Launching the script loads data, constructs fresh seeded weights, repeatedly samples batches and updates the model, evaluates checkpoints, and writes artifacts. Command-line settings select the recipe.', 'It is the dated work order sent to a factory: it identifies the process and settings that produced a particular batch.', 'A recorded command is necessary but not sufficient; data version, dependencies, code, and outputs must also be preserved.'),
      loss: note('We need one differentiable number that says how poor an entire batch of probability assignments was.', 'Cross-entropy reads the probability assigned to each correct next character and applies a logarithmic penalty. A confident wrong prediction receives a large penalty; probability concentrated on the correct answer receives a small one. Batch losses are averaged.', 'A forecaster is penalised more for saying “zero chance of rain” on a wet day than for admitting uncertainty.', 'Loss is not a percentage of good Shakespeare and cannot tell us whether one generated passage is meaningful. It measures next-token prediction under a specific dataset and tokenizer.'),
      gradients: note('Knowing the total error is not enough; with thousands of weights we need to know which tiny change would reduce it.', 'Automatic differentiation follows the recorded calculations backward from loss and computes a derivative for every weight. AdamW combines current gradients with running averages to choose an update, then the next forward pass uses the altered weights.', 'On a foggy hillside, each dial receives a local slope arrow. The optimiser takes a cautious downhill step using both the new arrow and recent directions.', 'A gradient points downhill only locally. It does not reveal the globally best model, and the optimiser has no intention or understanding.'),
      checkpoints: note('Without saved intermediate states we would see only the finish and miss when useful structure appeared, plateaued, or deteriorated.', 'At selected steps the script serialises the current weights plus identifying metadata and samples under fixed generation settings. A checkpoint can later be loaded without replaying all earlier updates.', 'They are save-game slots photographed with the same camera settings, allowing fair before/during/after comparison.', 'A checkpoint preserves numerical state, not the model’s “memories” as readable facts, and resuming exactly may require optimiser and random-generator state too.'),
      interpret: note('A falling number is evidence only when we understand what the number measures and what the architecture can possibly represent.', 'Training and validation loss fall because character-pair probabilities improve. Generated text gains common pairings and punctuation, but the one-character input prevents longer dependencies, so improvement eventually plateaus.', 'A student using only a two-letter phrasebook may learn common pairs perfectly yet remain unable to compose sentences.', 'Poor prose does not mean training failed; it may reveal the ceiling of the chosen information and architecture.'),
    },
  },
  'context-windows': {
    background: 'Language depends on more than the immediately previous character. A context window gives the model a fixed number of earlier tokens. This lesson changes the input from one token to eight, then adds machinery capable of turning those eight positions into a next-character prediction.',
    picture: 'Instead of seeing one fridge magnet, the model sees an eight-magnet strip. Each position is converted to features, the features are laid side by side, and a small network searches that combined pattern.',
    misconception: 'A longer context does not automatically mean the model remembers in a human sense. It merely receives more recent token IDs as inputs to one calculation.',
    goal: 'Understand what extra information the window provides, how its tensor shape flows through the network, and why fixed slots remain limiting.',
    notes: {
      question: note('The bigram ceiling suggests missing context may matter, but a fair interpretation requires recording every accompanying change.', 'The new model receives eight token IDs and introduces embeddings plus dense layers to process them. Dataset, tokenizer, split, sampling settings, and evaluation stay fixed so the comparison remains informative.', 'We widen a peephole and also install a lens to focus the larger view; both changes must appear on the invoice.', 'Because memory and processing capacity change together, the result cannot isolate context length perfectly.'),
      'batch-shape': note('Shape notation tells us what each array axis means; without it, code can run while mixing examples, positions, or features incorrectly.', 'A batch has 32 sequences, each 8 tokens long: shape 32 × 8. Targets have the same shape but are shifted one token forward, producing eight supervised predictions per sequence.', 'Picture 32 rows of eight clue cards, with an answer card beneath every column.', 'Dimensions describe arrangement, not meaning. The number 8 is useful only because code consistently treats that axis as sequence positions.'),
      architecture: note('Integer IDs are labels, so the network needs learnable numeric features before it can combine several positions.', 'Each ID looks up an embedding vector. Eight vectors are concatenated into one long vector, passed through a hidden nonlinear layer, and projected to 65 next-token logits.', 'Each character receives a small description card; eight cards are stapled in order and handed to a pattern-matching desk.', 'The learned features are not human-readable definitions, and concatenation fixes every position to a permanent slot.'),
      parameters: note('Counting weights reveals how much adjustable capacity each design adds and prevents “small model” from becoming a vague claim.', 'We multiply input and output dimensions for every weight matrix and add biases and embedding entries. Summing these pieces gives 43,361 trainable values.', 'It is an itemised construction quote: timber, windows, wiring, and labour are listed separately before the total.', 'Parameter count measures size, not quality, runtime, memory use, or intelligence.'),
      invoke: note('The same forward function supports learning and generation; the difference lies in what happens around its output.', 'During training, many known contexts produce logits, loss compares them with targets, and gradients update weights. During generation, the latest eight tokens produce probabilities, one token is sampled and appended, and no weights change.', 'The same piano can be used during a lesson with corrections or during a performance without corrections.', 'Feeding generated output back as new input can amplify early sampling choices; it is not the same distribution as teacher-guided training inputs.'),
      results: note('Visible structure helps connect a lower abstract loss to the capability added by the experiment.', 'Eight characters can jointly reveal fragments such as a speaker name plus colon, common word endings, and short punctuation patterns. The model therefore distinguishes contexts that the bigram collapsed together.', 'Seeing eight jigsaw pieces exposes part of the picture that one isolated piece cannot.', 'The output remains statistical imitation; recognisable formatting is not proof of understanding dialogue or characters.'),
      limits: note('Learning architecture means noticing not only what improved, but what becomes awkward as we scale the same idea.', 'Concatenation assigns separate weights to every seat. Extending 8 positions to 64 greatly enlarges the first matrix, and the model cannot dynamically reuse the same relevance rule at different positions.', 'It is a control panel with a dedicated socket for seat 1, seat 2, and so on; adding seats requires rewiring the panel.', 'Fixed windows still process context, but they lack attention’s content-dependent routing and position-sharing structure.'),
    },
  },
  'self-attention': {
    background: 'The fixed-window model mixes positions using the same fixed connections. Self-attention instead calculates, for the current text, how strongly each position should draw information from earlier positions. It is a differentiable routing mechanism inside the model—not awareness or concentration.',
    picture: 'Imagine every position carrying three cards: a request, a label describing what it offers, and a parcel of information. Requests are compared with labels; strong matches receive a larger share of the delivered parcels.',
    misconception: 'The word “attention” is a metaphor coined by researchers. The model does not notice meaning or choose deliberately; matrix multiplication produces relevance scores learned through prediction loss.',
    goal: 'Follow queries, keys, values, masking, weighted mixing, and residual flow while keeping the computation distinct from human attention.',
    notes: {
      purpose: note('We want one reusable mechanism that can connect relevant positions even when their distance and content change from sentence to sentence.', 'Every position produces a query and compares it with keys from allowed earlier positions. The resulting scores determine a weighted sum of value vectors, so the output is a context-dependent mixture.', 'A library request is matched against catalogue labels, and matching books contribute information to the answer.', 'No symbolic rule says that a colon or name matters. Training shapes projections only insofar as they help next-token prediction.'),
      positions: note('Attention sees a collection of vectors and otherwise has no built-in notion that one came first or fifth, yet order is essential to text.', 'A token embedding represents the token identity and a positional embedding represents its slot. Adding them gives each position a vector containing learnable information about both what and where.', 'Two identical actors wear different seat badges, allowing the usher to distinguish the first appearance from the later one.', 'The vectors do not store neat human categories; “what” and “where” become distributed numeric features that can interact.'),
      qkv: note('Queries, keys, and values separate the act of finding relevant sources from the information those sources contribute.', 'Three learned matrix projections transform each position vector. Dot products compare one query with all keys; the associated values—not the keys themselves—are blended using the resulting weights.', 'A search form states what is wanted, catalogue entries advertise what each book covers, and selected books supply the actual pages.', 'These roles are learned vectors, not English questions, labels, or facts. Inspecting one component rarely yields a plain-language rule.'),
      mask: note('During training the full passage is present in memory, so we must explicitly prevent a position from reading the answer that comes after it.', 'Before softmax, scores pointing to future positions are replaced with negative infinity. Their probability becomes zero; remaining scores are scaled and normalised to total 1.', 'An exam sheet has later answers covered, then the student divides a fixed attention budget only among visible clues.', 'The mask blocks future token positions in this calculation; it does not prevent the training corpus from containing repeated or related text elsewhere.'),
      block: note('New processing can damage useful input signals or make optimisation unstable, so the block preserves an easy route for existing information.', 'Attention output is projected back to model width and added to the original representation through a residual connection. Normalisation controls feature scale before or around the sublayer.', 'A bypass road carries the original traffic while a side road adds processed traffic before they rejoin.', 'Addition does not guarantee every original detail survives unchanged; later layers can still transform the combined representation.'),
      parameters: note('Attention’s flexibility comes from learned transformations, and counting them shows exactly what capacity was added.', 'Query, key, value, and output projections are matrices whose dimensions depend on model width, alongside token and position embeddings and the final vocabulary projection.', 'Each sorting station needs its own adjustable stencil for requests, labels, parcels, and recombination.', 'A modest parameter count can still incur substantial temporary memory because attention also builds a score grid for every pair of positions.'),
      run: note('This deliberately incomplete model lets us test whether routing alone solves the fixed-window limitation.', 'The script constructs one causal attention head, trains it on 64-character sequences with the recorded recipe, saves checkpoints, and evaluates the same held-out corpus.', 'We test a new engine component on a simple rig before building the entire vehicle around it.', 'The result evaluates this particular single-head block and recipe, not the value of attention in all models.'),
      results: note('A negative result protects us from equating fashionable complexity with improvement and points toward a missing component.', 'Although the model sees longer context and learns attention weights, its validation loss is worse than the simpler fixed-window network under this run. The routing mechanism alone lacks strong per-position nonlinear processing.', 'A postal system may route every parcel correctly but still fail if no workshop can transform the delivered materials.', 'One experiment does not prove attention is useless; it shows this isolated design did not win under controlled conditions.'),
      interpret: note('Understanding a transformer requires distinguishing communication between positions from computation within each position.', 'Attention mixes information across the sequence. A feed-forward network then transforms each position’s gathered features; multiple heads, residual paths, normalisation, and stacked blocks repeat and stabilise this cycle.', 'A meeting gathers relevant reports; afterward each participant needs a private desk to analyse what arrived.', 'The office metaphor suggests agents with intentions, but the implementation is only repeated learned matrix operations and nonlinear functions.'),
    },
  },
  'tiny-transformer': {
    background: 'A decoder-only transformer repeatedly alternates two jobs: attention moves information between token positions, and a feed-forward network transforms the information at each position. Residual connections and normalisation make this deep chain trainable. The last position is projected into scores for the next token.',
    picture: 'Think of a row of workstations. A communication round lets each workstation collect relevant earlier messages; a private processing round transforms its own bundle; skip lanes preserve the incoming bundle while new work is added.',
    misconception: 'A transformer is not one magical “AI layer.” It is a carefully arranged stack of ordinary operations whose weights are adjusted together by the same loss-and-gradient process already used for the bigram.',
    goal: 'Trace one batch from token IDs through embeddings, attention heads, feed-forward layers, residual additions, and final next-token logits.',
    notes: {
      complete: note('The word transformer names a repeatable block design, so we need to identify the essential sublayers rather than treat the name as an explanation.', 'Each block normalises its input, applies causal multi-head attention and adds the result; then it normalises again, applies a feed-forward network and adds that result. Stacking blocks repeats communication and transformation.', 'It is a two-station assembly cell—shared-message sorting, then private machining—with a conveyor bypass around each station.', 'Real transformer families vary in normalisation, position encoding, activation, and other details; this is one small decoder-only design.'),
      flow: note('Shapes are the map of where information lives and catch many errors that prose hides.', 'Token IDs shaped batch × time become batch × time × features after embeddings. Attention preserves that shape while mixing across time; feed-forward preserves it while transforming features; the final linear layer changes features into vocabulary logits.', 'Parcel labels record number of crates, items per crate, and measurements per item as the shipment passes each machine.', 'A shape tells us quantity and arrangement, not what a feature represents or whether the computation is correct.'),
      heads: note('One attention pattern may be too restrictive because several relationships can matter at the same position.', 'The 64 feature channels are split across four heads. Each head forms its own query–key scores and value mixture; their outputs are concatenated and projected back to 64 features.', 'Four research assistants inspect the same passage with separate learned filing systems, then combine their notes.', 'Heads are not assigned human categories in advance, and a head need not correspond cleanly to grammar, names, or punctuation.'),
      'feed-forward': note('After gathering context, each position needs nonlinear computation capable of creating and combining richer features.', 'A linear layer expands 64 values to 256, GELU bends the response so combinations are not merely linear, and another layer compresses back to 64. The same weights process every sequence position independently.', 'A workbench spreads a compact kit across a larger surface, performs cuts and joins, then repacks a refined kit.', 'The wider hidden space is temporary workspace, not extra context or a readable train of thought.'),
      block: note('Deep networks can become difficult to optimise when signals shrink, explode, or must pass through every transformation.', 'Pre-layer normalisation rescales each position’s features before a sublayer. A residual addition then combines the sublayer output with its input, providing a short path for information and gradients.', 'Before using a specialist machine, materials are standardised; a bypass belt ensures the original shipment can continue alongside the modification.', 'Normalisation and residuals improve trainability but do not guarantee stable training or preserve each feature literally.'),
      parameters: note('An itemised count connects architectural words to the actual number of learned values and reveals where capacity is concentrated.', 'Embedding tables, attention projections, two large feed-forward matrices per block, normalisation scale and bias, and the output projection sum to 112,065 parameters. The feed-forward layers dominate because of their 64 → 256 → 64 matrices.', 'A building budget reveals that the private workshops cost more than the meeting rooms.', 'Weights are reused over many tokens, so parameter count is not the number of operations performed during generation.'),
      run: note('A training recipe must be concrete enough for somebody else to recreate the result and compare it fairly.', 'The command fixes width, heads, blocks, context, batch size, steps, learning rate, seed, data split, and checkpoint schedule. The script repeatedly executes the same training loop on the new architecture.', 'It is a manufacturing run card specifying machine layout, material batch, speed, duration, and inspection points.', 'Matching settings improves reproducibility but hardware and low-level numerical differences can still cause small deviations.'),
      results: note('Watching fixed checkpoints ties visible behaviour to measured learning rather than presenting the final model as an unexplained leap.', 'Random weights produce nearly uniform character noise. As loss falls, common words, punctuation, line structure, and speaker formatting become more probable because the model has captured longer statistical dependencies.', 'A photograph sequence shows scattered iron filings gradually aligning around a magnetic field.', 'Coherent-looking fragments can occur without coherent meaning; humans are especially good at seeing intent in plausible text.'),
      comparison: note('We want to know which added capability produced the gain, but this experiment changed several things together.', 'Relative to the attention-only model, the transformer adds multiple heads, feed-forward layers, more residual structure, normalisation, blocks, and parameters. The final score measures the package, not each component separately.', 'Replacing an engine, gearbox, and tyres together can improve lap time without revealing each part’s contribution.', 'The comparison supports “this complete recipe worked better,” not “feed-forward layers alone caused the exact improvement.”'),
      limits: note('A successful experiment needs a precise boundary so fluent output is not mistaken for general intelligence.', 'The model estimates the next character from at most 64 prior characters using patterns learned from one corpus. It has no instruction training, retrieval, factual verification, persistent memory, senses, or goals.', 'It is an extremely elaborate autocomplete trained on one shelf of plays, not an actor who has read and understood Shakespeare.', 'Even “autocomplete” is incomplete: the learned internal representations are richer than a simple phrase lookup, but they still do not establish human understanding.'),
    },
  },
  evaluation: {
    background: 'Training loss tells us how well the model fits examples used for updates. Evaluation asks a different question: how well do frozen weights predict held-out text under rules chosen before seeing the answer? Several metrics and generated samples illuminate different parts of that question.',
    picture: 'Imagine every checkpoint sitting the same examination in the same room, with the same question-selection rule and the same writing prompt. Only then can score differences be attributed to the checkpoint rather than the test.',
    misconception: 'A pleasing sample is not a model score. Generation contains randomness, and people naturally remember striking successes while overlooking many failures.',
    goal: 'Explain what the frozen protocol controls and how loss, perplexity, generalisation gap, repeats, and samples complement one another.',
    notes: {
      purpose: note('Changing evaluation settings after seeing outputs makes it easy to favour a preferred model unconsciously.', 'The protocol fixes data split, batch sampling seeds, number of batches, metric calculations, prompt, temperature, generation length, and sampling seed before comparisons are read.', 'A race uses the same course, timing equipment, and start rules for every runner.', 'Identical tests make candidates comparable, but they do not guarantee that the chosen test represents every real use.'),
      protocol: note('A single sampled batch can be unusually easy or hard, so repeated measurements estimate the noise in evaluation itself.', 'The evaluator selects several deterministic groups of validation windows and computes loss for each. Their mean estimates performance and their spread shows batch-sampling variation.', 'Instead of judging a pupil from one page, we photograph performance on several pages drawn by a fixed rule.', 'These repeats evaluate the same trained weights. They do not measure variation caused by retraining from different random initialisations.'),
      run: note('Evaluation must not accidentally continue training, or the supposedly fixed candidates would change while being measured.', 'The script rebuilds each architecture, loads saved tensors, switches to inference-only calculations, samples frozen validation batches, and writes a separate report. It never calls backward or optimiser update.', 'An examiner may read and score a submitted paper but cannot rewrite the student’s answers.', 'Loading weights correctly also requires the exact matching architecture; a checkpoint alone is not a self-describing program.'),
      metrics: note('No single number answers every question about a language model, so closely related measurements must still be interpreted carefully.', 'Cross-entropy averages surprise at the correct next token. Perplexity is its exponential, roughly translating that surprise into an effective number of equally plausible choices. Validation minus training loss is the generalisation gap.', 'Loss is a log-scale instrument reading; perplexity relabels the same reading in more intuitive units; the gap compares rehearsal with the exam.', 'Perplexity is not literally the number of words the model considered, and scores are comparable only under the same tokenisation and data definition.'),
      'prompt-test': note('Generated text exposes failure modes—formatting, repetition, incoherence—that an average loss does not make vivid.', 'Every checkpoint receives the same encoded prompt and generation settings. A fixed sampling seed controls the pseudo-random draws, making visible differences easier to attribute to model probabilities.', 'It is asking every candidate to write the same essay with the same time limit after the multiple-choice exam.', 'One essay remains a tiny, qualitative sample; fixing the seed improves comparison but can still favour an accidental path.'),
      decision: note('Measurement earns its cost only when it changes the next question we ask.', 'The combined evidence shows continued prediction improvement alongside a widening train–validation gap. That suggests testing training regularisation or schedule changes before assuming that a larger architecture is the only route.', 'A medical test does not merely produce a number; it helps choose the next controlled intervention.', 'The evidence narrows plausible next steps but does not prove the cause of the gap until a controlled experiment tests it.'),
    },
  },
  'prompt-playground': {
    background: 'The trained model lives in Python as arrays and mathematical functions, while the wiki lives in a browser. The playground connects them with a small local API. Prompting supplies starting context for repeated next-token prediction; it does not retrain the model.',
    picture: 'The browser is a waiter carrying a structured order to a kitchen. The Python service loads the recipe and equipment, converts the order to token IDs, cooks one next character at a time, and returns text.',
    misconception: 'A prompt is not automatically an instruction. This model was trained only to continue Shakespeare-like characters, so it treats every prompt as preceding text rather than a command to obey.',
    goal: 'Trace a request across the browser/API/Python boundary and distinguish checkpoint choice, prompt context, sampling controls, and training.',
    notes: {
      'two-processes': note('Separating interface code from numerical inference lets each environment do the job it supports well and makes the connection visible.', 'The browser sends an HTTP POST containing JSON. The Python server validates those fields, invokes MLX model code, and returns JSON containing the completion and metadata. Neither process directly reaches into the other’s memory.', 'A waiter and kitchen communicate through a written order format rather than sharing a workbench.', 'Unlike a restaurant, both processes run on the same laptop and the API contract is defined entirely by this project.'),
      start: note('A webpage can remain visible even when the model service is absent, so beginners need to recognise the two independent lifecycles.', 'One long-running process serves and refreshes React pages on port 3000. Another listens for inference requests on port 8001. The playground checks the second service and reports whether it is reachable.', 'A shopfront and workshop have separate light switches; opening one does not power the other.', 'Ports are software addresses on the same machine, not separate physical computers.'),
      load: note('Saved weights are only numerical contents; inference also needs the matching arrangement of layers that knows where each tensor belongs.', 'The server reads checkpoint metadata, reconstructs the transformer with the recorded dimensions, loads named tensors into it, and caches the result so later requests avoid disk loading.', 'A save file contains the positions of pieces, while the game program supplies the rules and board on which those positions make sense.', 'Caching speeds reuse but consumes memory, and a mismatched code version can make old weights incompatible.'),
      'encode-prompt': note('The model cannot accept arbitrary visible text directly and can consult only the amount of history supported by its architecture.', 'The prompt is mapped through the same 65-character vocabulary used in training. At each prediction only the most recent 64 IDs are passed to the transformer; earlier characters are discarded from model input.', 'A speaker may read only the last page of a long briefing even though the audience can still see all earlier pages.', 'The visible textbox is not the context window. Unsupported characters or information beyond 64 tokens cannot influence this model as displayed.'),
      sampling: note('A language model produces a distribution for one next token, so a multi-character completion must be built iteratively.', 'The server takes logits at the final position, applies temperature and softmax, draws one token with the seeded random generator, appends it, crops to the context limit, and runs the model again.', 'Write one word on a branching story card, then use the expanded card to choose the next branch.', 'The model does not plan the finished passage before emitting it. Early random choices alter all later contexts.'),
      invoke: note('Seeing the raw request removes the illusion that the button performs hidden magic and makes the interface reproducible outside the UI.', 'The curl command serialises fields such as checkpoint, prompt, temperature, length, and seed into JSON, sends them to the local endpoint, and prints the returned JSON. The button performs the same contract.', 'It is viewing the exact order form that the polished counter hides.', 'The API validates request structure, but a syntactically valid prompt can still be unhelpful or outside the model’s learned distribution.'),
      controls: note('Several controls change output for different reasons, so changing them together makes comparison impossible to interpret.', 'Checkpoint changes learned weights; prompt changes visible context; temperature reshapes the probability distribution; seed changes pseudo-random draws; length changes how many feedback steps occur.', 'In a sound test, swap one microphone or one room setting at a time so you can identify the source of a difference.', 'Holding controls fixed reduces variation but does not make one completion representative of all possible generations.'),
      limits: note('Prompting and learning are often conflated, especially because large instruction-tuned models appear to respond intelligently to directions.', 'This service performs forward passes only. Prompt tokens temporarily influence activations and next-token probabilities, but checkpoint weights remain byte-for-byte unchanged after the response.', 'Writing a hint on a calculator’s input line changes the current calculation, not its internal circuitry.', 'A future model trained to follow instructions may respond differently, but even then prompting remains context at inference time rather than weight training.'),
    },
  },
  'training-improvements': {
    background: 'Architecture determines what computations a model can represent; the training recipe determines how its weights travel from randomness toward a useful setting. Before enlarging the transformer, this lesson tests whether gentler early steps, smaller late steps, or protection from rare large gradients improves the same architecture.',
    picture: 'Keep the same student, textbook, and exam, but compare study schedules: one uses constant-size corrections, another begins cautiously and gradually shifts from broad corrections to fine polishing, and another adds a safety limit.',
    misconception: 'A better optimiser recipe does not give the model new information or a new architecture. It may help the same capacity reach a better set of weights.',
    goal: 'Separate optimisation from architecture and read a controlled recipe comparison without overclaiming a single run.',
    notes: {
      question: note('Larger models cost more memory and time, so we should first test whether existing capacity is being used effectively.', 'The architecture, data, seed, batch sequence, steps, and evaluation remain fixed while learning-rate behaviour and clipping are changed. This focuses the question on the path through weight space.', 'Before buying a larger oven, check whether the current oven’s temperature schedule is ruining the bake.', 'Holding many variables fixed strengthens attribution, but low-level randomness and interaction between settings can still matter.'),
      variants: note('A control recipe provides the reference needed to tell whether each proposed change helped.', 'The baseline keeps a constant learning rate. The schedule variant adds warmup and cosine decay. The combined variant adds gradient clipping to that schedule. Each is trained and evaluated under matching conditions.', 'Three identical gardens receive the same seeds and water; only the named fertiliser schedule differs.', 'The variants test packages as defined. The combined result cannot reveal clipping’s effect at every possible threshold or schedule.'),
      schedule: note('Large updates can be risky when random weights and optimiser statistics are immature, while late training may benefit from fine adjustments rather than constant jumps.', 'Warmup raises the learning rate from small to full over early steps. Cosine decay then smoothly lowers it, so parameter changes become progressively smaller near the end.', 'A sculptor starts with controlled cuts, uses stronger shaping once oriented, then finishes with increasingly fine tools.', 'The schedule follows a fixed clock; it does not inspect whether the model personally “needs” caution or polish.'),
      clipping: note('Occasional large gradient norms can propose an update big enough to destabilise useful progress.', 'The script calculates the combined norm of all gradients. If it exceeds the threshold, every gradient is rescaled by the same factor so direction is preserved but total magnitude is limited.', 'A circuit breaker limits an electrical surge without redesigning the appliance.', 'Clipping does not fix consistently bad gradients, choose a better direction, or guarantee a smaller AdamW parameter update in every coordinate.'),
      run: note('Recipe comparisons are especially sensitive to different random starts or batch orders masquerading as an improvement.', 'Seeded initialisation and deterministic sampling align starting weights and corresponding training batches. Each variant writes separate checkpoints and metadata under the same measurement schedule.', 'Runners start from the same line and encounter the same course; only pacing instructions differ.', 'Perfectly identical floating-point execution is not guaranteed across software or hardware versions, which is why results and environment are recorded.'),
      checkpoints: note('Schedules change the path of learning, so the final score alone hides whether a candidate learned slowly, overtook late, or became unstable.', 'Checkpoint losses are plotted against steps and the recorded learning rate. Warmup can lag initially because updates are deliberately small, while decay may improve later stability and validation performance.', 'Two travellers can reach the same destination by different speed profiles; mile markers reveal where their journeys diverged.', 'Intermediate loss is noisy and does not justify selecting the visually smoothest curve without final frozen evaluation.'),
      'frozen-results': note('A recipe should win under the same higher-quality evaluation used for every other candidate, not the small samples used for live monitoring.', 'The evaluator loads final checkpoints and computes repeated held-out batches with the frozen protocol. Mean validation loss and uncertainty are compared directly.', 'Practice-score snapshots guide coaching, but the scheduled final exam decides the recorded result.', 'More evaluation batches reduce measurement noise for these checkpoints; they do not measure uncertainty across independent training runs.'),
      generation: note('Learners can see whether a numerical gain corresponds to noticeable output, while avoiding selection of a convenient showcase.', 'All variants receive the same prompt, temperature, length, and sampling seed. Differences therefore arise from their learned probabilities, although one path remains only one sample.', 'Every candidate receives the same opening line and the same sequence of dice rolls.', 'Equal dice rolls do not choose equivalent tokens when distributions differ, and another seed could produce a different visual ranking.'),
      limits: note('One seeded comparison can identify a promising recipe but cannot establish that it reliably wins from all random starts.', 'Matched seeds reduce noise within this experiment. To estimate training-seed variance, the entire training process—not merely evaluation batches—must be repeated with independent seeds.', 'One controlled crop trial suggests which fertiliser to retest; several seasons are needed for confidence.', 'Three seeds later provide stronger evidence, but still describe this small model, corpus, and training budget rather than a universal optimiser law.'),
    },
  },
  'scaling-experiment': {
    background: 'A transformer can be enlarged in different dimensions. Width gives every token representation more features, depth applies more sequential blocks, and context exposes more earlier tokens. These choices have different costs because stored weights and temporary calculations grow differently.',
    picture: 'A workshop can buy wider benches, add more workstations in series, or provide longer source documents. Each investment changes what workers can do and what space or time the workshop consumes.',
    misconception: '“Bigger” is not one setting, and parameter count alone does not predict runtime or memory. A longer context may add few learned weights while creating a much larger attention workspace.',
    goal: 'Explain width, depth, and context as separate resources and make a quality–memory–speed decision from controlled evidence.',
    notes: {
      design: note('Changing one dimension at a time lets us connect a measured gain and cost to a specific kind of capacity.', 'Starting from the 64-wide, two-block, 64-context reference, separate candidates double width, double blocks, or double context. Data order, seed, update count, batch size, and training recipe remain fixed.', 'Test a wider desk, a longer assembly line, and a larger reference binder in otherwise matching workshops.', 'Each change also alters parameter count or computation, so this isolates the design dimension—not a perfectly equal resource budget.'),
      cost: note('A model that fits in stored weights may still run out of memory during training because activations, gradients, optimiser state, and attention score grids also occupy space.', 'Width enlarges matrices along two axes and often grows parameters roughly quadratically. Depth repeats block storage and work. Context creates a time × time attention grid, so doubling sequence length makes four times as many pair scores.', 'A theatre’s permanent seats are like weights, while temporary staging for every pair of performers is like attention memory; the latter can dominate during a large scene.', 'Quadratic attention is the leading relationship here, but actual runtime and memory also depend on implementation, batch size, and hardware.'),
      run: note('All candidates must receive enough identical treatment for observed differences to be meaningful and reproducible.', 'One script trains four recorded configurations, saves matching checkpoints, measures wall time and peak Metal allocation, and evaluates held-out loss. The GPU executes tensor operations using unified memory.', 'A test laboratory runs four machines from one protocol and logs quality, electricity, and duration at the same inspection points.', 'Wall-clock measurements on a laptop can vary with temperature and other activity, so small timing differences should not be overinterpreted.'),
      results: note('Scaling is an engineering trade-off, not merely a hunt for the lowest loss.', 'The wider candidate achieves the best validation loss with about 421k parameters and moderate extra time and memory. Longer context adds few weights but has the highest memory and runtime because of its larger attention grids.', 'A wider workbench improves output most here; a longer reference table owns little permanent equipment yet occupies the largest floor area while in use.', 'These rankings belong to this training budget. More steps or different data could change which dimension pays off.'),
      sample: note('Output makes the wider model’s improvement tangible, but selection must aggregate many predictions rather than reward an appealing accident.', 'Under the frozen prompt and seed, the wider checkpoint produces longer word-like and dialogue-like fragments. Validation loss averages correctness across thousands of held-out next-character targets.', 'One audition shows style and failure modes; the scored season measures consistency.', 'Humans readily forgive plausible prose and notice successes, so qualitative samples require fixed settings and numerical support.'),
      decision: note('A winning single run is a candidate hypothesis; random initialisation may have made it unusually lucky or unlucky.', 'Width is selected because it offers the best observed quality within comfortable memory. The next lesson retrains this exact specification with multiple seeds while keeping all non-random choices frozen.', 'A prototype wins the first trial, then identical units are built to see whether the design—not one fortunate specimen—was responsible.', 'Replication reduces one source of uncertainty but cannot repair reuse of the development validation set or establish performance on other writing.'),
    },
  },
  'final-evaluation': {
    background: 'Model training is stochastic: random initial weights and batch choices can change the final result even when the architecture and recipe are identical. Repeating complete training with several seeds tests whether the selected wider design’s gain is robust to those ordinary variations.',
    picture: 'Instead of declaring a teaching method successful because one student scored well, train several students with the same course and compare their exam-score cluster with the old course.',
    misconception: 'A seed is not a quality setting and seed 43 is not inherently better. It labels a repeatable path through pseudo-random choices; its slightly better score may be chance.',
    goal: 'Distinguish model selection from scientific summary, interpret across-seed variation, and state exactly what this project has and has not demonstrated.',
    notes: {
      'final-spec': note('Freezing every design choice before confirmation prevents us from quietly tailoring the model after seeing each repeat.', 'Architecture dimensions, tokenizer, data split, optimiser, schedule, step count, batch size, evaluation, and hardware stay fixed. Only the seed controlling initial weights and batch sampling changes.', 'Seal the recipe in an envelope before baking confirmation cakes; only the random lot number on ingredients varies.', 'Even a frozen specification is conditional on earlier development choices made using the validation set.'),
      repeat: note('Repeated evaluation of one checkpoint measures quiz sampling noise; repeated training measures whether the learning process itself is stable.', 'Seeds 43 and 44 initialise new random tensors and generate new deterministic batch sequences, then perform all 3,000 updates. Seed 42 reuses the matching previously trained checkpoint.', 'Photographing one runner several times differs from training three runners under the same programme.', 'Three runs give a useful small check, not a precise estimate of every possible random outcome.'),
      'three-seeds': note('A consistent gap across independent runs is stronger evidence that width helped than one unusually low score.', 'Each wider model is evaluated with repeated frozen batches. Their validation losses cluster tightly around 1.5846 and all remain below the 64-wide reference at 1.7051.', 'Three arrows landing close together and beyond the old target line suggest the bow design helped, not merely one lucky shot.', 'The comparison does not isolate width beyond this recipe and corpus, and the small sample of seeds limits uncertainty estimates.'),
      selection: note('The playground needs one concrete checkpoint, while the scientific conclusion should represent the architecture rather than celebrate the luckiest run.', 'Seed 43 has the lowest observed validation loss and becomes the default artifact. The reported architecture result remains the mean and spread across all three independently trained models.', 'Choose one well-performing appliance for the showroom, but publish the quality record for the entire production sample.', 'Selecting the lowest of three introduces winner’s luck; its tiny advantage should not be treated as a discovered property of seed 43.'),
      journey: note('A stage-by-stage table shows which ideas created large gains and which refinements were marginal, building a causal story cautiously from controlled comparisons.', 'The random transformer establishes pre-training behaviour; bigram and fixed-context models add learned local patterns; the transformer adds flexible long-context processing; schedule tuning nudges optimisation; width adds capacity.', 'A route map marks which bridge produced the large shortcut and which roadworks saved only a minute.', 'Several transitions changed packages of features rather than one variable, so the table is an evidence narrative, not a perfect attribution of every loss reduction.'),
      limits: note('Clear limits stop a successful small experiment from being mistaken for a miniature general-purpose assistant.', 'The model predicts characters from one Shakespeare-derived corpus with a 64-character window. The validation tail influenced development, and there is no untouched test set, cross-domain corpus, factual task, or human evaluation of understanding.', 'A musician who imitates one short songbook is not thereby fluent in every genre or able to explain the music.', 'The model does not possess a musician’s experience or intentions; the comparison describes narrow statistical imitation.'),
      complete: note('The durable outcome is a reusable experimental method, not merely one entertaining checkpoint.', 'You can now trace data to tokens, tensors, logits, loss, gradients, updated weights, checkpoints, evaluation, controlled changes, replication, and local inference. Later projects will change token scale and training strategy while preserving this evidence chain.', 'You have learned the whole laboratory workflow with a tabletop experiment before operating larger equipment.', 'Completing the workflow is a foundation, not mastery. Larger datasets and pretrained models add engineering, safety, licensing, and evaluation challenges.'),
    },
  },
};
