export type BeginnerGuide = { picture: string; goal: string; notes: Record<string, string> };

export const beginnerGuidance: Record<string, BeginnerGuide> = {
  'lab-setup': {
    picture: 'Think of this lesson as preparing a clean kitchen before cooking: we label the ingredients, use the right appliances, and write down the recipe so somebody else can reproduce the meal.',
    goal: 'You do not need to memorise every tool. Understand which part trains the model, which part displays the lessons, and why isolated versions make results trustworthy.',
    notes: {
      'why-a-lab': 'A model result is like a scientific experiment: the equipment and conditions are part of the result, not background trivia.',
      'tooling-installed': 'Python is the language, MLX is the maths workshop, the Apple GPU is the fast calculator, and the wiki is the lab notebook you are reading.',
      'environment-command': 'A virtual environment is a sealed toolbox for this project. Its package versions cannot get mixed up with tools from another project.',
      'project-shape': 'Folders are labelled drawers: training code, raw material, saved model snapshots, measured results, and lesson pages each have their own drawer.',
      'live-refresh': 'The trainer leaves a fresh results card on the counter; the open webpage checks for a new card every two seconds and redraws itself.',
    },
  },
  'data-and-tokenisation': {
    picture: 'A model cannot read letters directly. We first make a numbered set of Scrabble tiles, then replace every character in the play with its tile number.',
    goal: 'Follow one character from downloaded text to an integer in a tensor, and understand why some text is withheld from training.',
    notes: {
      download: 'Downloading the corpus is simply collecting the textbook the model will study. Provenance tells us exactly which edition we used.',
      'characters-as-tokens': 'The vocabulary is the complete box of 65 allowed tiles. A space and a line break count as tiles just like A or q.',
      encode: 'Encoding is a substitution cipher, not learning: each visible character is replaced by its agreed integer ID.',
      split: 'Training text is the practice workbook; validation text is a closed-book quiz. Looking at quiz answers while practising would make the score dishonest.',
      batches: 'A batch is a handful of short practice questions graded together. Each question asks: given these characters, what character came next?',
    },
  },
  'random-baseline': {
    picture: 'Imagine a 65-by-65 roulette board. Every current character points to a row of initially random preferences for the next character.',
    goal: 'See that the architecture exists before knowledge does, and distinguish building a model from training it.',
    notes: {
      architecture: 'The table is a set of 65 answer sheets—one for each possible current character—with 65 candidate next-character scores on each sheet.',
      'random-weights': 'Random weights are an untrained student circling answers arbitrarily. Randomness gives each answer a different starting point; it contributes no Shakespeare knowledge.',
      invoke: 'Invoking means feeding numbers through the model once. It is like asking the untrained student a question; no learning happens unless we later update weights.',
      sample: 'Softmax turns raw scores into slices of a probability pie. Sampling spins that weighted wheel to choose one next character.',
      limits: 'Because the model sees only one character, it cannot know whether “t” belongs to “the,” “time,” or a speaker name. Its memory ends immediately.',
    },
  },
  'bigram-training': {
    picture: 'Training is repeated coaching: ask a question, measure how wrong the answer was, point out which knobs contributed, then nudge those knobs.',
    goal: 'Understand the loop loss → gradients → optimiser update, and why a falling validation loss is stronger evidence than nicer-looking text alone.',
    notes: {
      command: 'The command is the start button plus written settings. Recording it is how we repeat the same experiment later.',
      loss: 'Loss is a single “how surprised were you by the right answer?” score. Confidently choosing the wrong character is penalised most.',
      gradients: 'A gradient is a tiny arrow on every knob saying which direction would reduce the mistake. AdamW decides how far to turn each knob.',
      checkpoints: 'A checkpoint is a save-game slot. It lets us revisit the model before training, partway through, and at the end.',
      interpret: 'The model improves spelling-like transitions but hits a ceiling because one-character memory cannot represent phrases or grammar.',
    },
  },
  'context-windows': {
    picture: 'Instead of guessing the next tile from one tile, the model now receives an eight-character fridge magnet strip.',
    goal: 'See how added memory changes both the input shape and what patterns the model can learn.',
    notes: {
      question: 'This is an experiment about memory, but the new memory also needs more machinery. We record both changes rather than pretending only one thing moved.',
      'batch-shape': 'Each row is one eight-character clue; 32 rows mean 32 clues are answered together.',
      architecture: 'Embeddings turn each character into a small bundle of features. Concatenating them lays eight bundles side by side before the dense layer reads them.',
      parameters: 'Parameter counting is an invoice: it shows exactly where the model spends its learnable numbers.',
      invoke: 'Training and generation use the same model. During training we know the answer and update it; during generation we sample an answer and feed it back in.',
      results: 'Speaker labels appear because eight characters can contain clues such as a name followed by a colon—information the bigram never saw together.',
      limits: 'Every position is a fixed seat. The model cannot easily decide that seat 2 matters today while seat 7 matters for another sentence.',
    },
  },
  'self-attention': {
    picture: 'Attention is a meeting where each character can look back across the table and decide whose information is relevant before speaking.',
    goal: 'Understand queries, keys, values and the causal mask as information routing—not as intelligence by themselves.',
    notes: {
      purpose: 'The fixed-window model mixes every seat in one fixed way. Attention calculates a fresh seating plan for each input.',
      positions: 'Token embedding says “what character am I?” Position embedding adds “where am I sitting?” The sum carries both facts.',
      qkv: 'A query is what I am looking for, a key is what I advertise, and a value is the information I will hand over if selected.',
      mask: 'The mask is an exam invigilator covering future answers. Softmax then divides 100% of attention among only visible positions.',
      block: 'A residual connection is a bypass road: new processing is added without destroying the original representation.',
      parameters: 'Attention needs learned projections that manufacture queries, keys and values, plus the existing embeddings and output layer.',
      run: 'This command trains a deliberately incomplete attention model so we can learn what attention alone contributes.',
      results: 'A negative result is useful evidence. More context and attention did not beat the simpler eight-character model under this recipe.',
      interpret: 'Attention moves information between positions; a full transformer also needs machinery that transforms that information within each position.',
    },
  },
  'tiny-transformer': {
    picture: 'A transformer block is a small office: attention gathers relevant messages from colleagues, then the feed-forward desk processes the gathered material.',
    goal: 'Follow the complete decoder-only transformer from token IDs to 65 next-character scores.',
    notes: {
      complete: 'A complete block alternates communication across positions with private processing at each position, while residual paths and normalisation keep work stable.',
      flow: 'Tensor shapes are parcel labels: batch 32, sequence 64, and feature width 64 tell us how many examples, positions, and numbers per position are moving.',
      heads: 'Four heads are four researchers reading the same passage with separate notebooks. They can look for different relationships at once.',
      'feed-forward': 'The network temporarily spreads 64 features onto a 256-space workbench, applies nonlinear processing, then packs the result back into 64 features.',
      block: 'Layer normalisation keeps feature scales orderly; residual addition preserves the incoming message while adding the sublayer’s contribution.',
      parameters: 'Most weights live in the feed-forward workbenches. Four heads divide the existing attention width rather than multiplying it.',
      run: 'The settings after the command are the recipe card: model size, steps, batch size, learning rate and seed.',
      results: 'Early samples show letter noise; later ones acquire words, punctuation and speaker-like structure. That visible progression mirrors falling loss.',
      comparison: 'This comparison is informative but not perfectly controlled because architecture size and training recipe changed together.',
      limits: 'Shakespeare-like texture is not understanding. The model predicts plausible characters without a world model, instructions, or verified facts.',
    },
  },
  evaluation: {
    picture: 'Evaluation is a driving test on a fixed route: every checkpoint faces the same roads and scoring rules so the comparison is fair.',
    goal: 'Learn why loss, perplexity, variation and generated examples answer different questions and should be read together.',
    notes: {
      purpose: 'If we change the quiz for each student, scores are meaningless. Freezing the protocol stops us quietly favouring a model.',
      protocol: 'Repeats are several photographs of the same model on different sampled quiz pages—not several independently trained models.',
      run: 'The evaluator opens saved weights in read-only mode. It measures them but never turns a training knob.',
      metrics: 'Loss is the underlying surprise score. Perplexity is the same result translated to a more intuitive uncertainty scale. The gap compares practice with quiz performance.',
      'prompt-test': 'A generated sample is like reading one essay from a student: revealing, but too small to replace a whole exam score.',
      decision: 'Good evaluation ends with a decision. Here it says training still helps, but the widening train/validation gap deserves attention.',
    },
  },
  'prompt-playground': {
    picture: 'The webpage is a waiter, the Python service is the kitchen, and the saved checkpoint is the chef’s learned recipe.',
    goal: 'Trace your prompt from browser text to token IDs, model probabilities, sampled characters and displayed continuation.',
    notes: {
      'two-processes': 'The browser handles buttons and text boxes; Python owns the numerical model. The API is their agreed order slip.',
      start: 'Two processes must be awake: one serves the wiki and one serves model completions. Closing either terminal stops that half.',
      load: 'A checkpoint stores learned numbers, not the blueprint. Python rebuilds the blueprint first, then pours the saved numbers into it.',
      'encode-prompt': 'Only the last 64 characters fit on the model’s desk. Older prompt text remains visible to you but falls outside its working memory.',
      sampling: 'Generation is a feedback loop: choose one character, append it, ask again. Small early choices can send later text down a different path.',
      invoke: 'The curl example is the raw order slip behind the button. JSON names the prompt, checkpoint, temperature, length and seed.',
      controls: 'Change one control at a time. Otherwise you cannot tell whether a different result came from training, randomness, temperature or prompt wording.',
      limits: 'Prompting is giving context, not teaching. The model’s weights remain unchanged and it does not interpret your text as an instruction.',
    },
  },
  'training-improvements': {
    picture: 'We keep the same student and textbook but test two study schedules: gentler pacing of lessons and a safety brake on unusually large corrections.',
    goal: 'Distinguish optimisation improvements from architecture improvements by changing one training rule at a time.',
    notes: {
      question: 'Before buying a larger model, check whether the current one is being taught well. The architecture is held fixed for this reason.',
      variants: 'The baseline is the control group. Each other recipe changes one named ingredient so the result has an interpretable cause.',
      schedule: 'Warmup starts with cautious steps; cosine decay makes steps progressively finer, like switching from a paint roller to a detail brush.',
      clipping: 'Gradient clipping is a circuit breaker. It activates only when the proposed overall update is unusually large.',
      run: 'Both variants start from the same seeded initial conditions and see corresponding batches, making the recipe the intended difference.',
      checkpoints: 'The schedule can look worse early because it deliberately learns slowly, then overtake once smaller late updates refine the model.',
      'frozen-results': 'The larger final evaluation decides the winner; the small checkpoint measurements are progress indicators, not the finish-line judge.',
      generation: 'Better average prediction does not guarantee every individual sample looks better. Generation remains stochastic and qualitative.',
      limits: 'Repeating evaluation batches measures quiz noise. Repeating full training seeds is needed to measure whether the recipe itself reliably wins.',
    },
  },
  'scaling-experiment': {
    picture: 'We can improve a workshop by widening each workbench, adding more workstations in sequence, or giving workers a longer document to consult.',
    goal: 'Compare model width, model depth and context length as separate investments in quality, time and memory.',
    notes: {
      design: 'Width means more features at each position; depth means more processing stages; context means more earlier characters visible. They are different resources.',
      cost: 'A longer desk holds more paper but attention compares every position with every other visible position, so its comparison grid grows quickly.',
      run: 'Four full training runs use the same teaching recipe. Each saves intermediate models so the result can be inspected rather than trusted from one final number.',
      results: 'Width wins quality here, but it also spends more parameters. Longer context spends surprisingly little on weights and a lot on temporary attention memory.',
      sample: 'The wider model’s sample looks more play-like, yet selection rests on thousands of held-out predictions rather than one attractive paragraph.',
      decision: 'One winning run is a candidate, not a conclusion. We next retrain the chosen design from different random starting points.',
    },
  },
  'final-evaluation': {
    picture: 'The final stage is asking three students trained with the same course to sit the same exam, rather than declaring victory from one unusually good student.',
    goal: 'Understand what multiple training seeds confirm, why one checkpoint is selected, and the limits of the final claim.',
    notes: {
      'final-spec': 'Freezing the specification is sealing the recipe before the confirmation bake. Only the random seed label changes.',
      repeat: 'A new training seed reshuffles initial weights and sampled practice batches. It creates a genuinely new trained model, not another reading of the old one.',
      'three-seeds': 'The close cluster of three scores is the important result: width helped regardless of which of these random starts was used.',
      selection: 'Seed 43 is selected because a working product needs one checkpoint. The across-seed average is the more honest scientific summary.',
      journey: 'Read the table as an evidence ladder: added memory and transformer processing made the large gains; schedule tuning helped a little; width helped again.',
      limits: 'The validation pages were consulted during development, so they are no longer a sealed final exam. The score is useful in-domain evidence, not a universal benchmark.',
      complete: 'The transferable lesson is the experimental loop, not Shakespeare imitation. The same loop will carry into larger data, tokenizers and task-specific evaluation.',
    },
  },
};
