export type LessonEngineeringBrief = {
  question: string;
  enters: string;
  changes: string;
  evidence: string;
  handoff: string;
  boundary: string;
  run: {
    command: string;
    reads: string;
    computes: string;
    writes: string;
    mutates: string;
    complete: string;
    recovery: string;
    cost: string;
  };
};

export const lessonEngineeringBriefs: Record<string, LessonEngineeringBrief> = {
  'lab-setup': {
    question: 'Can another learner identify and recreate the software and hardware context before interpreting a model result?',
    enters: 'A repository checkout, supported Node/Python tooling, and an unverified local machine.',
    changes: 'The isolated JavaScript/Python environments and local development processes only; no data or model state.',
    evidence: 'System report, resolved lock files, installed versions, successful lint/build, and a reachable local wiki.',
    handoff: 'A reproducible local lab with `.venv/`, `node_modules/`, and known hardware/backend constraints.',
    boundary: 'A working environment proves that the course can run; it does not reproduce any training evidence or guarantee later models fit.',
    run: {
      command: 'python3 scripts/system_report.py\nnpm ci\nuv sync --python 3.12 --extra apple\nnpm run dev',
      reads: 'Operating-system and hardware metadata, package.json/package-lock.json, pyproject.toml, uv.lock, and application source.',
      computes: 'A non-destructive platform report, exact dependency resolution, and local wiki compilation.',
      writes: 'Local dependency directories and caches; the development server keeps compiled state in temporary build directories.',
      mutates: 'Installs project-local dependencies and starts a local process; downloads no course dataset and updates no weights.',
      complete: 'The system report names the backend limits, locked installs succeed, and the wiki loads without build or console errors.',
      recovery: 'Resolve the first version/profile error from the report and lock files. Do not change model settings to hide a setup mismatch.',
      cost: 'Initial dependency downloads can take several minutes and multiple gigabytes; later starts are much cheaper.',
    },
  },
  'data-and-tokenisation': {
    question: 'What exact text becomes training examples, and which characters are withheld from weight updates?',
    enters: 'The verified lab and an empty or previously verified Tiny Shakespeare raw-data path.',
    changes: 'Dataset presence plus the declared character vocabulary, 90/10 boundary, and next-character batching procedure.',
    evidence: 'Source URL, SHA-256 checksum, byte/character counts, 65-token vocabulary, split sizes, and input/target shapes.',
    handoff: 'One checksum-verified raw corpus and a deterministic in-memory encoding/split contract; no learned weights.',
    boundary: 'The final 10% is same-corpus validation—not an untouched test set—and the upstream repository licence does not by itself settle corpus redistribution.',
    run: {
      command: 'uv run --no-sync python scripts/download_tiny_shakespeare.py',
      reads: 'The pinned upstream raw URL, expected SHA-256 constant, and any existing local corpus file.',
      computes: 'Streaming download and checksum verification. Training scripts later derive the sorted character vocabulary, contiguous split, and shifted batches in memory.',
      writes: 'Only `data/raw/tiny-shakespeare.txt`; token tensors and batches are not persisted.',
      mutates: 'Creates or atomically replaces the ignored raw file after verification; performs no model construction or optimiser update.',
      complete: 'The file hash is 86c4…65ed and later loading yields 1,115,394 characters, 65 tokens, and the declared split sizes.',
      recovery: 'A checksum mismatch deletes the temporary download and leaves no unverified replacement. Recheck the recorded upstream source before changing the expected hash.',
      cost: 'One approximately 1.1 MB download; tokenisation and batching are negligible beside training.',
    },
  },
  'random-baseline': {
    question: 'What does this architecture produce before text changes even one weight?',
    enters: 'Verified corpus/token mapping, seed 42, and a 65×65 bigram architecture with no learned state.',
    changes: 'Random weight materialisation and evidence capture only at checkpoint step 0.',
    evidence: '4,225-parameter count, initial logits, fixed sampling controls, random continuation, and saved step-zero weights.',
    handoff: 'The causal before-training checkpoint embedded in the Lesson 4 experiment.',
    boundary: 'The shared command continues into training after capturing step 0; random output is a baseline, not evidence of dataset learning.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_bigram.py --steps 400',
      reads: 'Verified corpus plus the fixed vocabulary, split, seed, prompt start token, and bigram configuration.',
      computes: 'Constructs and materialises random weights, performs one forward inference path, samples 280 characters, and saves step 0 before the first update.',
      writes: 'Step-zero evidence and Safetensors under the normal bigram local result/run paths; the same command later adds trained checkpoints.',
      mutates: 'Step-zero capture performs no optimiser update. Continuing the shared command then performs Lesson 4’s 400 updates.',
      complete: 'Checkpoint 0 exists, its parameter count/configuration match, and its sample was captured before any loss-gradient-update cycle.',
      recovery: 'Rerun the complete deterministic bigram experiment rather than combining a new step-zero file with checkpoints from another configuration.',
      cost: 'The baseline itself is one short inference capture; the shared command also pays for the small 400-update Lesson 4 run.',
    },
  },
  'bigram-training': {
    question: 'How far can repeated next-character correction take a model that sees only one character?',
    enters: 'A freshly recreated seed-42 step-zero bigram, verified data split, and fixed batch/sampling rules.',
    changes: 'Only the 4,225 table weights through 400 AdamW updates.',
    evidence: 'Train/validation loss and fixed-seed samples at steps 0, 1, 25, 100, and 400.',
    handoff: 'A weight-only bigram checkpoint cohort that exposes both rapid learning and the one-character ceiling.',
    boundary: 'Randomly sampled validation batches make tiny late differences noisy; the checkpoints do not contain optimiser or data-order state for exact resume.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_bigram.py --steps 400',
      reads: 'Verified corpus, deterministic character mapping/split, and command-line training configuration.',
      computes: 'Shifted batches, cross-entropy, automatic differentiation, 400 AdamW updates, scheduled validation, and generation.',
      writes: '`public/data/local/shakespeare-metrics.json`, run configuration, and five Safetensors checkpoints under `work/experiments/shakespeare-bigram-001/`.',
      mutates: 'Trains a fresh weight table and atomically refreshes learner evidence; committed Reference evidence remains untouched.',
      complete: 'The dashboard status is complete and all five declared steps contain matching evidence/checkpoint files.',
      recovery: 'Restart the lesson from seed 42 after interruption. Weight-only checkpoints are for comparison/inference, not exact optimiser continuation.',
      cost: 'Very small training run: 400 updates over a 4,225-parameter table plus sampled validation and generation.',
    },
  },
  'context-windows': {
    question: 'Does giving a fresh model eight ordered characters improve prediction beyond the bigram ceiling?',
    enters: 'The same corpus/token/split protocol and an independently initialised fixed-context MLP.',
    changes: 'Context grows from 1 to 8 and the architecture grows to embeddings plus dense layers; prior bigram weights are not reused.',
    evidence: 'Tensor shapes, 43,361-parameter accounting, checkpoint losses, runtime, and fixed-seed samples.',
    handoff: 'A weight-only six-checkpoint MLP cohort and an explicit record that context and capacity changed together.',
    boundary: 'This comparison shows the combined new architecture works better; it does not isolate context length from added parameters.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_context.py --steps 2000',
      reads: 'Verified corpus plus the fixed tokenizer/split, seed, eight-character batching, and MLP configuration.',
      computes: 'Fresh initialisation, context embedding/flattening, 2,000 AdamW updates, scheduled validation, and generation.',
      writes: 'Local context dashboard JSON, configuration, and weight-only checkpoints under `work/experiments/shakespeare-context-001/`.',
      mutates: 'Creates a separate model history; it neither loads nor overwrites bigram checkpoints.',
      complete: 'Declared checkpoints through step 2,000 exist and the configuration, parameter count, shapes, and evidence agree.',
      recovery: 'Restart from the fixed seed because optimiser/data cursor are not saved. Treat a shape mismatch as configuration drift.',
      cost: '2,000 updates on a 43,361-parameter MLP; still a short laptop experiment.',
    },
  },
  'self-attention': {
    question: 'Can dynamic causal information routing help without a complete transformer block?',
    enters: 'The same character corpus/split and a fresh 64-context, single-head attention architecture.',
    changes: 'Architecture becomes token/position embeddings plus one causal attention head and output projection.',
    evidence: 'Mask behavior, query/key/value shapes, 28,993 parameters, checkpoint losses, runtime, and samples.',
    handoff: 'A weight-only attention cohort demonstrating that attention is useful machinery but not sufficient alone.',
    boundary: 'The run differs from the MLP in context, parameter count, and architecture; it is a teaching comparison, not a pure attention ablation.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_attention.py --steps 2000',
      reads: 'Verified corpus, fixed token/split rules, seed, causal mask, and attention configuration.',
      computes: 'Fresh initialisation, query-key scores, future masking, softmax mixing, 2,000 AdamW updates, validation, and generation.',
      writes: 'Local attention dashboard JSON, configuration, and six weight-only checkpoints under `work/experiments/shakespeare-attention-001/`.',
      mutates: 'Trains a separate model from randomness; no prior architecture checkpoint is loaded.',
      complete: 'All scheduled checkpoints exist, future positions remain masked, parameter accounting matches, and evidence reaches step 2,000.',
      recovery: 'Restart the lesson after interruption; reject checkpoint reload when architecture or vocabulary metadata differ.',
      cost: '2,000 updates with 64-token attention matrices; modest on the reference laptop.',
    },
  },
  'tiny-transformer': {
    question: 'What changes when attention is combined with feed-forward and residual processing in repeated blocks?',
    enters: 'The frozen data/token protocol and a fresh two-block decoder-only transformer.',
    changes: 'Architecture adds four attention heads, feed-forward sublayers, pre-normalisation, residual paths, and final normalisation.',
    evidence: 'End-to-end tensor flow, 112,065 parameters, seven checkpoint losses, runtime, and fixed-seed generations.',
    handoff: 'The baseline transformer checkpoint cohort used by evaluation, playground, and recipe experiments.',
    boundary: 'Better in-domain next-character prediction does not demonstrate meaning, reasoning, factual knowledge, or broad language ability.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_transformer.py --steps 3000',
      reads: 'Verified corpus, tokenizer/split, seed, 64-character batches, and full transformer configuration.',
      computes: 'Fresh initialisation, complete forward/backward paths, 3,000 AdamW updates, scheduled validation, and generation.',
      writes: 'Local transformer dashboard JSON, configuration, and seven weight-only checkpoints under `work/experiments/shakespeare-transformer-001/`.',
      mutates: 'Creates a new transformer history; it does not continue the earlier attention model.',
      complete: 'Checkpoints 0–3,000, configuration, parameter count, losses, timing, memory, and samples are all present.',
      recovery: 'Restart from seed 42 after interruption. Downstream lessons must reject a missing or shape-incompatible checkpoint.',
      cost: '3,000 updates plus seven validation/generation captures; the first material transformer run.',
    },
  },
  'evaluation': {
    question: 'Do frozen transformer checkpoints improve under identical measurements, and where does overfitting begin to appear?',
    enters: 'The exact Lesson 7 architecture/configuration and seven weight-only checkpoints.',
    changes: 'Nothing in model weights; only measurement breadth and repeatability increase.',
    evidence: 'Repeated train/validation loss, spread across sampled batches, perplexity, generalisation gap, and fixed prompts/seeds.',
    handoff: 'A frozen development-evaluation record and selected baseline checkpoint for controlled follow-up work.',
    boundary: 'Repeated validation batches measure one checkpoint’s evaluation noise. Validation already guided development, and no untouched test set exists.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_evaluate.py',
      reads: 'Verified corpus/split, transformer config, seven checkpoint files, and a predeclared evaluation protocol.',
      computes: 'Forward-only repeated losses, mean/spread, perplexity, gaps, and identical prompt generations.',
      writes: '`public/data/local/shakespeare-evaluation.json` and `work/experiments/shakespeare-evaluation-001/config.json`.',
      mutates: 'Writes evaluation evidence only; no gradients, optimiser, or checkpoint changes occur.',
      complete: 'Every declared checkpoint loads and has five matched train/validation repeats plus all fixed prompt records.',
      recovery: 'Rerun the owning transformer lesson for missing/incompatible weights. A mechanical rerun may preserve the same protocol; changing it creates a new evaluation.',
      cost: 'Forward-only evaluation of seven checkpoints: 70 loss-estimation groups plus fixed generations.',
    },
  },
  'prompt-playground': {
    question: 'How does a browser prompt invoke fixed local weights without retraining them?',
    enters: 'The evaluated transformer checkpoint cohort and, when available, later recipe/final checkpoints.',
    changes: 'Prompt, checkpoint, temperature, seed, and generation length only; weights remain frozen.',
    evidence: 'Returned continuation plus run/checkpoint identity, controls, token count, stop reason, and elapsed time.',
    handoff: 'Reproducible exploratory observations—not a new model selection or scored evaluation.',
    boundary: 'Interactive retries invite cherry-picking, and loopback exposure is not a production security design.',
    run: {
      command: 'npm run dev\nuv run --no-sync python ml/shakespeare_inference_server.py',
      reads: 'Local checkpoint/config files, verified corpus-derived vocabulary, and learner-entered JSON requests.',
      computes: 'Health discovery, architecture reconstruction, strict weight loading, prompt encoding, autoregressive sampling, and decoding.',
      writes: 'No experiment files; displayed runs live only in current browser state.',
      mutates: 'Starts two loopback processes and caches models in memory; performs no training or checkpoint writes.',
      complete: 'Health reports ready and a request returns a continuation whose metadata matches the selected run, step, seed, and controls.',
      recovery: 'Start the checkpoint-owning lesson when files are missing, then restart Python. Keep the service bound to 127.0.0.1.',
      cost: 'Interactive inference; first use loads/compiles a checkpoint, while cached requests are cheaper.',
    },
  },
  'training-improvements': {
    question: 'Can a different update schedule improve the same transformer without adding capacity?',
    enters: 'The Lesson 7 baseline checkpoint/config plus the frozen Lesson 8 evaluation protocol.',
    changes: 'Two fresh matched seed-42 runs change learning-rate schedule or gradient clipping; architecture and batch identities stay fixed.',
    evidence: 'Baseline plus candidate losses, schedule traces, clipped-step counts, memory/time, checkpoints, and fixed generation.',
    handoff: 'A provisional warmup/cosine recipe and complete three-variant comparison record.',
    boundary: 'Only one training seed is compared, and the new variants are fresh trainings—not continuations from the baseline checkpoint.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_training_improvements.py',
      reads: 'Baseline final checkpoint/config, frozen corpus/split/evaluation, and the two declared recipe variants.',
      computes: 'Re-evaluates the baseline, trains two isolated 3,000-update paths from matched random state/batches, then applies frozen evaluation.',
      writes: 'Local comparison JSON, experiment selection config, and weight-only candidate checkpoints/configurations.',
      mutates: 'Creates two new model histories; baseline weights remain unchanged.',
      complete: 'All three variants have matched final evidence and the predeclared lowest-validation rule selects a provisional recipe.',
      recovery: 'A missing baseline blocks comparison. Interrupted candidates restart because optimiser/data-order state is not checkpointed.',
      cost: 'Two new 3,000-update trainings plus evaluation of three final checkpoints.',
    },
  },
  'scaling-experiment': {
    question: 'Which single architecture axis buys the most validation improvement for its laptop cost?',
    enters: 'The provisional warmup/cosine recipe, frozen data/evaluation, and no inherited candidate weights.',
    changes: 'Width, depth, or context separately across four fresh seed-42 trainings.',
    evidence: 'Validation mean/spread, perplexity, gap, parameters, elapsed time, peak MLX allocation, checkpoints, and fixed continuation.',
    handoff: 'A selected 128-wide seed-42 checkpoint and full quality–memory–time comparison.',
    boundary: 'One seed and 3,000-update budget rank these candidates locally; they do not establish universal scaling laws or eventual model potential.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_scaling.py',
      reads: 'Frozen corpus/token/split/evaluation, warmup/cosine recipe, and four architecture specifications.',
      computes: 'Four isolated fresh 3,000-update runs, repeated final evaluation, resource measurement, generation, and rule-based selection.',
      writes: 'Local scaling JSON, selection config, and five weight-only checkpoints/configuration per candidate.',
      mutates: 'Creates four independent histories; it does not enlarge or overwrite Lesson 9 weights.',
      complete: 'Every candidate records quality and cost under matched controls and selectedRunId names an observed complete variant.',
      recovery: 'An interrupted candidate restarts; do not compare a partial run or splice weights into a different tensor shape.',
      cost: 'Four full transformer trainings; one of the course’s larger Shakespeare runs.',
    },
  },
  'final-evaluation': {
    question: 'Does the selected wider recipe remain strong across independent random training paths?',
    enters: 'Frozen 128-wide architecture/recipe/evaluation and the checksum-compatible Lesson 10 seed-42 checkpoint.',
    changes: 'Only seed-driven initial weights and batch paths for fresh seeds 43 and 44.',
    evidence: 'Three validation means/spreads, across-seed mean/std, perplexity, runtime, memory, checkpoint identities, and fixed continuation.',
    handoff: 'A selected practical checkpoint plus the three-seed architecture summary and explicit course limits.',
    boundary: 'Three seeds are a small stability check. Validation shaped every earlier choice, no untouched test set exists, and selecting seed 43 is developmental.',
    run: {
      command: 'uv run --no-sync python ml/shakespeare_final.py',
      reads: 'Verified corpus/split, frozen final spec, Lesson 10 seed-42 checkpoint/config, and fixed evaluation/generation controls.',
      computes: 'Reuses verified seed 42, trains seeds 43/44 for 3,000 updates each, evaluates all three, summarizes variation, and selects one practical checkpoint.',
      writes: 'Two new final checkpoints/configurations, final local dashboard JSON, and experiment summary config.',
      mutates: 'Creates independent seed-43/44 histories; seed 42 and all earlier checkpoints remain unchanged.',
      complete: 'All three seeds have complete matched evidence, the distribution is reported before selection, and the capability boundary remains visible.',
      recovery: 'A missing seed-42 scaling run blocks confirmation. Interrupted new seeds restart because only final weights—not resumable optimiser state—are saved.',
      cost: 'Two new 3,000-update wider-model trainings plus three-seed evaluation.',
    },
  },
  'transition-to-subwords': {
    question: 'Can the complete TinyStories path connect before we spend time training?',
    enters: 'The Shakespeare concepts, an empty TinyStories raw-data folder, and random model weights.',
    changes: 'Corpus and token scale; the model remains untrained.',
    evidence: 'Verified sample files, tokenizer round-trip, tensor/logit shapes, finite random loss, random generation, and checkpoint reload.',
    handoff: 'A traceable 1,000/200-story feasibility sample and provisional tokenizer/model—not a frozen training recipe.',
    boundary: 'This is a plumbing result. It does not establish dataset quality, tokenizer quality, or story capability.',
    run: {
      command: 'uv run --no-sync python scripts/download_tinystories_sample.py\nuv run --no-sync python ml/tinystories_transition.py',
      reads: 'The Hugging Face TinyStories source, then the downloaded sample manifest and JSONL files.',
      computes: 'Sampling, hashes, provisional BPE training, one random-model forward pass, loss, generation, and strict reload.',
      writes: 'Raw sample files under data/raw/, local dashboard JSON, a run configuration, tokenizer, and checkpoint zero.',
      mutates: 'Downloads data and creates learner artifacts; performs zero optimiser updates.',
      complete: 'All source hashes match, tokenizer round-trip succeeds, arrays have declared shapes, and the saved checkpoint reloads exactly.',
      recovery: 'If download or hashes fail, rerun the downloader. If model checks fail, keep the evidence and inspect the first failing invariant—do not copy a Reference metric.',
      cost: 'Small feasibility run; the first invocation includes download and compilation overhead.',
    },
  },
  'dataset-audit': {
    question: 'Is the bounded sample trustworthy enough to become teaching material?',
    enters: 'Lesson 1 sample files, their manifest, and the provisional tokenizer.',
    changes: 'No source row, tokenizer rule, or model weight; only audit evidence and a frozen split identity are added.',
    evidence: 'Schema and character checks, length distributions, exact and near-duplicate comparisons, template counts, keyword triage, and tokenizer integrity.',
    handoff: 'The named tinystories-development-v1 split with hashes and explicit known limitations.',
    boundary: 'The audit covers declared automated checks on 1,200 stories, not every bias, unsafe theme, or full-source distribution property.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_dataset_audit.py',
      reads: 'Lesson 1 JSONL files, manifest, and provisional tokenizer.',
      computes: 'Read-only validation, counts, pairwise similarity, keyword screens, and encode/decode checks.',
      writes: 'Local audit JSON and an ignored experiment configuration.',
      mutates: 'Creates evidence only; no dataset rewrite and no model construction or training.',
      complete: 'Required fields and hashes pass, leakage measurements finish, and the result names the frozen split and its limitations.',
      recovery: 'A hash mismatch belongs to the downloader; a structural or overlap failure belongs in the audit record and requires an explicit data decision before continuing.',
      cost: 'CPU audit with 200,000 cross-split comparisons; normally much cheaper than training.',
    },
  },
  'tokenizer-experiment': {
    question: 'Which vocabulary size preserves text while balancing sequence length and model cost?',
    enters: 'The frozen development split; no model checkpoint is eligible to influence this choice.',
    changes: 'Vocabulary size only across four otherwise matched byte-level BPE candidates.',
    evidence: 'Round-trip integrity, unknown-token count, validation compression, vocabulary-dependent parameter cost, and a predeclared selection rule.',
    handoff: 'One checksum-identified 2,048-piece tokenizer used by every later TinyStories lesson.',
    boundary: 'Tokenizer selection measures representation efficiency, not downstream story quality.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_tokenizer_experiment.py',
      reads: 'Frozen train/validation JSONL and the Lesson 2 audit result.',
      computes: 'Four training-only BPE vocabularies, validation encoding/decoding, compression, and induced embedding/output parameter counts.',
      writes: 'Candidate reports, selected tokenizer JSON, configuration, and local dashboard evidence.',
      mutates: 'Creates tokenizer artifacts; changes no model weights.',
      complete: 'Every hard integrity gate passes and selection.json identifies one tokenizer under the recorded rule.',
      recovery: 'Rerun Lesson 2 if dataset hashes disagree. Treat a round-trip or unknown-token failure as a blocked candidate, not a score to average away.',
      cost: 'Four small tokenizer fits; CPU-bound and short relative to model training.',
    },
  },
  'sequence-batching': {
    question: 'Can separate stories become rectangular causal tensors without inventing targets or crossing boundaries?',
    enters: 'Frozen dataset hashes and the selected tokenizer checksum.',
    changes: 'Data representation only: stories become token windows, padding, targets, and masks.',
    evidence: 'Exact adjacent-pair coverage, no cross-story targets, reconstruction, tensor shapes, padding masks, and utilization.',
    handoff: 'A frozen context-128, batch-32 batching contract shared by baseline and training.',
    boundary: 'Correct batches prove data plumbing, not that a model can learn from them.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_sequence_batching.py',
      reads: 'Selected tokenizer, frozen dataset files, and their prerequisite evidence.',
      computes: 'Per-story BOS/EOS wrapping, context windows, shifted targets, right padding, loss masks, and audit invariants.',
      writes: 'Local batching JSON, configuration, and a human-readable batch preview.',
      mutates: 'Creates arrays and evidence; performs no forward pass, loss calculation, or weight update.',
      complete: 'Every genuine adjacent pair appears once, no target crosses a story, reconstruction matches, and padding contributes zero loss.',
      recovery: 'A checksum failure belongs to the owning data/tokenizer lesson. A pair-count or boundary failure belongs to batching code and must be fixed before training.',
      cost: 'Small deterministic preprocessing and audit run.',
    },
  },
  'random-gpt-baseline': {
    question: 'What does the final TinyStories architecture do before learning?',
    enters: 'Frozen tokenizer and batch contract; no trained weights.',
    changes: 'Architecture is frozen and random weights are materialized once.',
    evidence: 'Parameter arithmetic, complete held-out loss, probabilities, fixed prompts, memory, throughput, checkpoint hash, and strict reload parity.',
    handoff: 'The official 5,816,320-parameter checkpoint zero that Lesson 6 must inherit exactly.',
    boundary: 'A valid forward pass and finite loss prove invocation, not language competence.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_random_baseline.py',
      reads: 'Frozen tokenizer, batching evidence, and complete validation windows.',
      computes: 'Seeded model construction, forward-only validation, fixed-prompt generation, allocator measurements, save and strict reload.',
      writes: 'Local baseline JSON, configuration, and checkpoint-0000.safetensors.',
      mutates: 'Creates and saves random weights; constructs no optimiser and performs zero updates.',
      complete: 'Parameter count and finite metrics match the declared architecture, and a fresh load reproduces the fixed logit slice exactly.',
      recovery: 'Rerun the tokenizer/batching owner when hashes differ. Treat a reload mismatch as checkpoint corruption or architecture drift.',
      cost: 'Complete validation plus short generation; forward-only and much cheaper than training.',
    },
  },
  'first-pretraining': {
    question: 'How does repeated next-token correction change the official random checkpoint?',
    enters: 'The exact checkpoint-zero weights, frozen data order rules, tokenizer, batches, and prompts.',
    changes: 'Model weights through 500 AdamW updates; architecture and evaluation remain fixed.',
    evidence: 'Masked train/validation loss, gradients, update checkpoints, throughput, memory, and fixed-prompt samples at declared steps.',
    handoff: 'Weight-only checkpoints through step 500, suitable for evaluation/inference but not exact interruption recovery.',
    boundary: 'Lower next-token loss and improved prose fragments do not establish planning, truth, safety, or general language ability.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_first_pretraining.py',
      reads: 'Checkpoint zero, frozen tokenizer/batches, train windows, and complete validation windows.',
      computes: 'Masked loss, automatic differentiation, AdamW updates, scheduled checkpoint evaluation, and generation.',
      writes: 'Local training dashboard, configuration, traces, and weight-only checkpoints at the declared steps.',
      mutates: 'Updates model weights in memory and writes new checkpoints; does not overwrite checkpoint zero.',
      complete: 'All scheduled checkpoints exist with hashes, validation covers every real target, and the final evidence preserves random-to-trained comparisons.',
      recovery: 'Because optimiser and data cursor are not saved here, an interrupted run restarts this lesson. Do not claim exact resume from a weight-only checkpoint.',
      cost: 'First substantive training run: 500 updates plus repeated complete validation and generation.',
    },
  },
  'checkpoints-dashboard': {
    question: 'Can training stop and continue in a fresh process without losing the state that determines the next update?',
    enters: 'Lesson 6 step-500 weights, with an explicitly fresh AdamW/data-order boundary.',
    changes: 'One named 100-update continuation segment and the checkpoint format; not the architecture or task.',
    evidence: 'Exact tensor reload, optimiser-state parity, batch hashes/cursor, next-batch identity, and bounded floating-point continuation differences.',
    handoff: 'A manifest-complete step-600 model/optimiser/trainer/data-order checkpoint.',
    boundary: 'Resume reliability says nothing about whether those extra updates improved model quality.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_checkpoint_resume.py',
      reads: 'Step-500 weights plus frozen tokenizer and batch contract.',
      computes: 'A control continuation, checkpoint at 550, fresh-process reload, independent continuation to 600, and parity checks.',
      writes: 'Live dashboard JSON plus manifest-marked model, optimiser, trainer, and data-order state under the local run directory.',
      mutates: 'Performs 100 continuation updates on each comparison path and writes complete resumable state.',
      complete: 'Discrete state matches exactly, saved tensors reload exactly, and all numerical differences remain within predeclared tolerances.',
      recovery: 'Only directories with the final manifest are loadable. Remove or separately archive an incomplete local attempt before a clean rerun; never bless partial files manually.',
      cost: 'Two matched 50-update continuations plus validation; larger disk use because optimiser state is saved.',
    },
  },
  'training-recipe': {
    question: 'Can the same step-600 model use its next 100 batches better with another learning-rate policy?',
    enters: 'The complete Lesson 7 step-600 model, AdamW history, batch cursor, and frozen evaluation.',
    changes: 'Learning-rate policy only across three branches.',
    evidence: 'Matched batch identities, train traces, complete step-700 validation, memory/time, fixed prompts, and a predeclared improvement threshold.',
    handoff: 'One selected inherited-history step-700 checkpoint and a record of all three branches.',
    boundary: 'The result compares this local continuation segment; it does not identify a universally best schedule.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_training_recipe.py',
      reads: 'Manifest-complete step-600 state, frozen tokenizer/data, prompts, and protocol.',
      computes: 'Three isolated 100-update continuations with identical batches and different rates, then complete validation.',
      writes: 'Candidate checkpoints, traces, selection record, and local dashboard JSON.',
      mutates: 'Creates three new model/optimiser histories without modifying the shared start.',
      complete: 'All branches consume matching batch hashes, save complete step-700 states, and the recorded rule selects or retains the control.',
      recovery: 'A missing prerequisite manifest requires rerunning Lesson 7. A partial candidate must not be mixed with completed branches from another protocol.',
      cost: 'Three 100-update workers plus complete validation; roughly triple one short continuation.',
    },
  },
  'scaling-budget': {
    question: 'Which architecture/data axis is worth scaling within the laptop budget?',
    enters: 'Frozen dataset/tokenizer/batching rules; architecture candidates cannot share Lesson 8 weights.',
    changes: 'One declared axis per fresh-start probe, followed by one clean selected 700-update run.',
    evidence: 'Probe validation loss, parameters, update time, peak MLX allocation, feasibility gates, and clean-run validation.',
    handoff: 'A clean-history selected architecture checkpoint at step 700, separate from Lesson 8’s inherited-history result.',
    boundary: 'Short probes measure usefulness under this budget, not the eventual potential of larger models or more data.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_scaling_budget.py',
      reads: 'Frozen tokenizer, dataset/batches, probe specification, and evaluation prompts.',
      computes: 'Five fresh 100-update probes, a gated selection, then one fresh 700-update confirmation.',
      writes: 'Probe weights/traces, selection record, complete selected checkpoint, and local dashboard evidence.',
      mutates: 'Trains fresh weights for every candidate; it does not continue or overwrite Lesson 8 checkpoints.',
      complete: 'Every probe records quality and cost, the selection rule is applied once, and the chosen long run has a complete manifest.',
      recovery: 'Resume only from a manifest-complete selected checkpoint. Do not splice a Lesson 8 state into a different tensor shape.',
      cost: 'One of the largest single lessons: five probes plus a 700-update training run.',
    },
  },
  'story-evaluation': {
    question: 'What behaviors changed beyond average next-token loss?',
    enters: 'Random, inherited-history, and clean-history checkpoints whose identities and hashes are frozen.',
    changes: 'Nothing in model state; only the breadth of evaluation.',
    evidence: 'Complete validation, fixed scenarios/seeds, adherence and contradiction proxies, repetition/diversity, closure, training overlap, and fixed outputs.',
    handoff: 'An evaluated checkpoint cohort and a visible error taxonomy for controlled prompting.',
    boundary: 'Surface proxies and 15 generations per checkpoint cannot measure meaning, truth, plot coherence, or every copying path.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_story_evaluation.py',
      reads: 'Frozen checkpoint cohort, tokenizer, validation set, training text, and prewritten protocol.',
      computes: 'Forward-only validation and deterministic surface measurements over fixed generations.',
      writes: 'Protocol, full local result records, and polling dashboard JSON; no checkpoint.',
      mutates: 'Writes evidence only; performs no gradients or optimiser updates.',
      complete: 'Every checkpoint hash is verified and every declared prompt/seed/metric record is present.',
      recovery: 'Rerun the lesson that owns a missing checkpoint. Use an empty run directory when the evaluator rejects stale protocol state.',
      cost: 'Inference-only, but includes complete validation and 45 fixed generations.',
    },
  },
  'tinystories-playground': {
    question: 'How does a learner-controlled prompt travel through fixed local checkpoints?',
    enters: 'The Lesson 10 evaluated cohort, and optionally the final selected checkpoint after Lesson 12.',
    changes: 'Prompt and sampling controls only; weights remain frozen.',
    evidence: 'Returned text plus checkpoint hash, prompt tokens visible, seed, temperature, stop reason, token count, and elapsed time.',
    handoff: 'Exploratory observations with reproducible controls—not a new scored model selection.',
    boundary: 'Retrying prompts makes this useful for diagnosis but unsuitable as an unbiased capability estimate.',
    run: {
      command: 'npm run dev\nuv run --no-sync python ml/tinystories_inference_server.py',
      reads: 'Lesson 10 evidence, tokenizer, checkpoint files, and learner-entered prompts.',
      computes: 'Validated local HTTP requests, tokenization, forward inference, sampling, and decoding.',
      writes: 'No experiment artifacts; the page holds displayed runs only in current browser state.',
      mutates: 'Starts two local processes and allocates model memory; performs no training or checkpoint writes.',
      complete: 'Health is ready, checkpoint hashes verify, one request returns metadata, and compare-all holds sampling controls fixed.',
      recovery: 'A missing/mismatched file belongs to its owning lesson. Keep both services loopback-only and restart the inference process after final checkpoint changes.',
      cost: 'Interactive inference; first use of each checkpoint includes load and compilation latency.',
    },
  },
  'final-story-model': {
    question: 'How stable is the clean 700-update recipe across independent training paths?',
    enters: 'The frozen Lesson 9 recipe and reused, checksum-verified seed-42 checkpoint.',
    changes: 'Training seed and shuffled batch path only for two fresh confirmations.',
    evidence: 'Three complete validation losses, mean/standard deviation/range, target exposure, fixed behavior suite, and exact checkpoint identities.',
    handoff: 'A selected practical checkpoint plus a three-seed recipe result and explicit course capability boundary.',
    boundary: 'Validation already shaped the course; there is no untouched TinyStories test split in this bounded sample.',
    run: {
      command: 'uv run --no-sync python ml/tinystories_final.py',
      reads: 'Frozen recipe/protocol, seed-42 checkpoint/evaluation, tokenizer, data, and fixed prompts.',
      computes: 'Two fresh 700-update trainings, complete validation, three-seed statistics, fixed behavior evaluation, and selection.',
      writes: 'Two new checkpoints, configurations, full result/progress JSON, and selected-checkpoint metadata.',
      mutates: 'Creates independent seed-43/44 weights and AdamW histories; does not retrain seed 42.',
      complete: 'All three seeds have verified complete evidence and the result reports the distribution before naming a practical checkpoint.',
      recovery: 'Run one fresh seed as a pipeline check on constrained hardware, but label two-seed/one-seed completion as incomplete confirmation.',
      cost: 'Largest TinyStories confirmation: 1,400 new updates plus complete evaluation; approximately 46 MiB of new course-local artifacts.',
    },
  },
  'task-and-dataset-audit': {
    question: 'What may the model see, what may it emit, and what does correct mean?',
    enters: 'No selected pretrained model and no permission to trust or redistribute the dataset blindly.',
    changes: 'Only the task/evaluator contract and dataset evidence; no model state.',
    evidence: 'Verified WikiSQL files, structural validity, split overlap, read-only reference execution, and explicit licence uncertainty.',
    handoff: 'A frozen single-table input/output grammar and development/test boundary.',
    boundary: 'The audit does not measure model accuracy or grant dataset redistribution rights.',
    run: {
      command: 'uv run --no-sync python scripts/download_wikisql.py\nuv run --no-sync python ml/sql_task_dataset_audit.py',
      reads: 'The official WikiSQL archive, then its manifest, JSONL/table files, and SQLite databases.',
      computes: 'Hash verification, schema/operator checks, split-overlap counts, and sampled reference-query execution.',
      writes: 'Raw files under data/raw/, local audit JSON, and an ignored run configuration.',
      mutates: 'Downloads data and creates evidence; selects, loads, and trains no model.',
      complete: 'All source/structure checks pass and 300 sampled reference queries execute under the restricted read-only path.',
      recovery: 'A source hash mismatch blocks the audit. A structural failure must remain visible and be resolved upstream or through a new documented dataset version.',
      cost: 'One roughly 25 MB download plus a full structured audit and 300 reference execution smokes.',
    },
  },
  'base-model-selection': {
    question: 'Which small pretrained base is the defensible starting point on this laptop?',
    enters: 'Frozen task contract, closed test split, and no task-specific weight updates.',
    changes: 'Candidate model/tokenizer only; questions, prompt semantics, decoding, and evaluator stay fixed.',
    evidence: 'Pinned revision/licence/context, load eligibility, memory, latency, prompt tokens, valid SQL, exact match, and development execution.',
    handoff: 'One pinned selected base revision for prompt-format comparison.',
    boundary: 'A 24-example development screen ranks only the declared candidates and does not estimate final test accuracy.',
    run: {
      command: 'uv run python ml/sql_base_model_selection.py',
      reads: 'WikiSQL development examples/tables/databases and pinned model repositories from the Hugging Face cache.',
      computes: 'Separate-process model loading, chat-template prompts, greedy generation, restricted parsing, and read-only execution.',
      writes: 'Per-candidate records, protocol/selection JSON, and local dashboard evidence.',
      mutates: 'Downloads model files to the external cache and creates evidence; performs zero optimiser updates.',
      complete: 'At least one candidate passes eligibility, every eligible candidate has a complete matched record, and the predeclared rule selects one revision.',
      recovery: 'Treat a missing/incompatible model file as a mechanical eligibility failure, not zero accuracy. Repair or replace the candidate before interpreting a behavior comparison.',
      cost: 'Roughly 600 MB of candidate repositories plus 48 short greedy generations.',
    },
  },
  'prompt-formatting': {
    question: 'Which schema serialization helps the selected base follow the SQL interface without leaking answers?',
    enters: 'The exact Lesson 2 model revision and a still-closed test split.',
    changes: 'Schema serialization only: compact, DDL-like, or JSON.',
    evidence: 'Matched development execution, exact match, valid SQL, prompt-token count, and latency.',
    handoff: 'One frozen prompt style used to create all LoRA records and final prompts.',
    boundary: 'Prompt selection is development evidence specific to this model/tokenizer, not a universal prompting rule.',
    run: {
      command: 'uv run python ml/sql_prompt_formatting.py',
      reads: 'Lesson 2 selection, a fresh seeded development sample, schemas, and the selected cached model.',
      computes: 'Three semantically matched prompt serializations, greedy generation, restricted parsing, and read-only execution.',
      writes: 'Protocol, per-style records, selection JSON, and local dashboard evidence.',
      mutates: 'Creates evidence only; does not update model weights or open test.',
      complete: 'All three styles use identical non-format inputs and the predeclared hierarchy selects one style.',
      recovery: 'A missing Lesson 2 result blocks the run. Do not silently choose a fallback model or use test examples to resolve a development tie.',
      cost: 'One cached model load and 72 short generations.',
    },
  },
  'lora-fine-tuning': {
    question: 'Can a small low-rank adapter improve executable SQL while the base weights stay frozen?',
    enters: 'Selected base revision, selected prompt style, train/dev only, and no adapter learning yet.',
    changes: 'LoRA parameters in the final eight layers through 100 Adam updates.',
    evidence: 'Hashed records, zero-effect random-adapter parity, train/validation loss, trainable fraction, memory, adapter checksum, and development execution.',
    handoff: 'One checksum-identified trained adapter paired with its exact base and prompt.',
    boundary: 'The bounded 512-example run is a teaching experiment; development gains are not final test evidence.',
    run: {
      command: 'uv run python ml/sql_lora_fine_tuning.py',
      reads: 'Lessons 2/3 results, 512 seeded train and 64 development examples, and the pinned cached base.',
      computes: 'Chat-record serialization, zero-update adapter, 100 prompt-masked LoRA updates, loss traces, and matched development inference.',
      writes: 'Hashed data records, logs, random/trained adapters, evaluation records, and local dashboard JSON.',
      mutates: 'Updates only the LoRA parameter subset—1.466M parameters on the documented Qwen path; base weights remain frozen.',
      complete: 'Random adapter matches base outputs, trained adapter checksum is saved, and all three checkpoint states have complete development records.',
      recovery: 'A prerequisite mismatch blocks training. Rerun deterministically with the same protocol; never backfill a missing adapter metric or swap the base revision.',
      cost: '512-example preparation, 100 small-adapter updates, and 72 development generations; model cache excluded.',
    },
  },
  'execution-evaluation': {
    question: 'How much does the frozen adapter change answer correctness on previously unopened test examples?',
    enters: 'Exact base revision, adapter checksum, prompt style, decoding settings, evaluator, sample size, and seed frozen before test.',
    changes: 'Nothing in weights or selection; only the data split changes from development to test.',
    evidence: 'Execution accuracy, exact match, valid SQL, Wilson uncertainty interval, latency, memory, failure groups, and fixed records.',
    handoff: 'A final sampled test comparison with no post-test model or prompt selection.',
    boundary: 'One 100-example WikiSQL sample does not establish full-test performance, production SQL safety, or behavior on joins/private schemas.',
    run: {
      command: 'uv run python ml/sql_execution_evaluation.py',
      reads: 'Lesson 4 result/checksum, frozen base and adapter, and the seeded WikiSQL test sample.',
      computes: 'Greedy generation, restricted parsing, parameterized read-only execution, row comparison, and failure taxonomy; the dashboard derives Wilson intervals from stored counts.',
      writes: 'Frozen protocol, base/adapter records, final comparison, and local dashboard JSON.',
      mutates: 'Creates evidence only; performs no training and permits no further selection from the observed test result.',
      complete: 'Both frozen checkpoints evaluate the identical sample and the result records deltas, failure groups, limitations, and noFurtherSelection.',
      recovery: 'A mechanical failure may rerun the identical frozen protocol. Any model/prompt/evaluator change requires returning to development and declaring a new final protocol.',
      cost: 'Two model loads and 200 short generations plus read-only SQLite execution.',
    },
  },
};
