export const plannedBeginnerGuidance: Record<string, { purpose: string; mechanism: string; picture: string; boundary: string }> = {
  'dataset-audit': { purpose: 'Before spending hours training, establish what the stories contain, where they came from, and which defects the model could inherit.', mechanism: 'We will inspect file structure, licence, text lengths, vocabulary, duplicate or near-duplicate stories, recurring templates, and possible split leakage before selecting a bounded subset.', picture: 'Inspect and inventory timber before building furniture; warped or duplicated boards affect everything downstream.', boundary: 'An audit can reveal known problems but cannot prove a dataset is unbiased or complete.' },
  'subword-tokenizer': { purpose: 'Character tokens make sequences long, while whole-word vocabularies cannot gracefully handle every word. Subwords offer a practical middle scale.', mechanism: 'A tokenizer finds frequently reusable character sequences such as “ing” or “story,” assigns them IDs, and breaks every sentence into available pieces. We measure vocabulary size and tokens per story.', picture: 'Build text from Lego pieces of several sizes rather than only single studs or one custom brick per entire word.', boundary: 'A compact tokenisation is not automatically linguistically meaningful, and token boundaries are not thought boundaries.' },
  'scale-experiment': { purpose: 'A 32 GB laptop sets real memory and cooling limits, so model size should be chosen from measurements rather than ambition.', mechanism: 'We will benchmark candidate widths, depths, contexts, and batch sizes on a small data slice, recording parameters, training speed, and peak unified memory before committing to a long run.', picture: 'Test several engine sizes on a dynamometer before choosing one for the full journey.', boundary: 'A short speed benchmark predicts feasibility better than final quality; learning curves can change over longer training.' },
  pretraining: { purpose: 'This is the stage where random weights acquire general TinyStories next-token patterns through repeated prediction and correction.', mechanism: 'Batches of subword sequences produce logits and cross-entropy loss; gradients and AdamW update weights. Checkpoints expose the progression from noise toward sentence and story structure.', picture: 'The same correction workshop used for Shakespeare now handles larger word-piece worksheets and a much larger control panel.', boundary: '“Pretraining” means broad learning relative to later tasks, not universal knowledge or complete training.' },
  'story-evaluation': { purpose: 'Low next-token loss does not by itself tell us whether a generated story remains consistent, follows a prompt, or avoids copying.', mechanism: 'We will combine frozen loss with multiple fixed prompts and explicit checks for grammar, repetition, diversity, character consistency, prompt adherence, and training-text overlap.', picture: 'Assess a writer with both a spelling test and several essays marked against a rubric.', boundary: 'Some story qualities require judgement; a rubric makes that judgement visible but not perfectly objective.' },
  'task-and-dataset-audit': { purpose: 'SQL can be textually different yet return the same correct answer, so “correct” must be defined before training.', mechanism: 'We will inspect questions, table schemas, reference queries, split design, licence, ambiguities, and known WikiSQL limits, then define exact-match and execution-based evaluation.', picture: 'Agree whether two routes count as equivalent when both reach the same destination before judging drivers.', boundary: 'Execution correctness on benchmark tables does not guarantee safety or correctness on real databases.' },
  'base-model-selection': { purpose: 'A pretrained model brings useful language patterns but also memory cost, licence conditions, context conventions, and unknown baseline ability.', mechanism: 'Candidate models will answer the same untouched examples before fine-tuning while we measure correctness, latency, memory, tokenizer behaviour, and licence suitability.', picture: 'Audition existing translators with the same test passage and equipment limits before hiring one for specialist training.', boundary: 'A benchmark winner may still be unsuitable if its licence, size, or failure modes conflict with the project.' },
  'prompt-formatting': { purpose: 'The model must reliably distinguish the user’s question, available columns, and the SQL it should produce.', mechanism: 'We will define one template that serialises table name, column names and types, the question, and the target query, while ensuring the answer never appears in the input.', picture: 'Use a standard translation form with labelled boxes so every request presents the same kinds of information in the same places.', boundary: 'A consistent format reduces ambiguity but cannot rescue missing schema information or an inherently ambiguous question.' },
  'lora-fine-tuning': { purpose: 'Updating every pretrained weight may exceed the laptop’s practical memory budget and can unnecessarily disturb broad language capability.', mechanism: 'Original weight matrices stay frozen. Small trainable low-rank matrices learn adjustments in selected layers; at inference their contribution modifies the base calculation.', picture: 'Fit small steering attachments to a large existing machine instead of rebuilding every gear.', boundary: 'LoRA reduces trainable parameters, not necessarily all inference memory, and it does not guarantee preservation of every base capability.' },
  'execution-evaluation': { purpose: 'Two SQL strings can differ in spelling or order yet calculate the same answer, while a plausible-looking query can be dangerously wrong.', mechanism: 'Generated SQL will be parsed and run against isolated read-only benchmark databases with time and operation limits. Returned results are compared with reference answers and failures are grouped by cause.', picture: 'Judge a set of instructions by safely performing them and checking the outcome, not merely by comparing handwriting.', boundary: 'Sandbox execution reduces risk for benchmark data; generated SQL must not be trusted against production systems without independent controls.' },
};
