import type { BeginnerGuide, BeginnerSectionGuide } from './beginner-guidance';

const note = (why: string, mechanism: string, analogy: string, boundary?: string): BeginnerSectionGuide => ({ why, mechanism, analogy, boundary });

export const sqlBeginnerGuidance: Record<string, BeginnerGuide> = {
  'task-and-dataset-audit': {
    background: 'Earlier projects repeatedly predicted the next piece of text. This project asks for a checkable transformation instead: read a question and a description of one table, then produce a small database program. Before any model changes, we must define exactly what information is allowed and what result counts as correct.',
    picture: 'Imagine writing instructions for a librarian who may see a visitor’s question and the catalogue headings, but not the answer card. The instructions are tested in a sealed practice catalogue before they are trusted.',
    misconception: 'SQL that looks plausible is not necessarily correct, and SQL that differs from a reference string is not necessarily wrong. The returned database rows provide stronger evidence than appearance alone.',
    goal: 'Explain the English-to-SQL input and output boundary, why execution and exact match answer different questions, and why the benchmark evaluator must remain isolated from real databases.',
    notes: {
      departure: note('Changing from pretraining to task adaptation changes what the experiment must prove. General next-token ability is only a starting condition, not evidence of database correctness.', 'A future pretrained base will receive a question plus column descriptions and emit a restricted program. This lesson freezes that interface and its tests before any weights or adapters are chosen.', 'Before hiring a translator, write the job specification and the marking scheme for the trial translation.', 'The model will calculate token probabilities; it does not understand a database or intend to answer the user.'),
      contract: note('Without a fixed boundary, a model could appear accurate by seeing table contents, reference answers, or test examples that should be hidden.', 'The contract names each permitted input field, the restricted output grammar, the held-out split and the primary metric. Later scripts must serialize exactly those allowed fields.', 'A sealed exam states which reference sheet is allowed, what form answers must take and which questions remain locked away.', 'A benchmark contract supports fair comparison inside this task; it does not certify use on different schemas or live systems.'),
      provenance: note('Training data carries legal and interpretive constraints as well as examples. An unclear licence can block redistribution even when the files are technically easy to download.', 'The manifest records the upstream archive, fixed hash, version, code licence and unresolved dataset-licence question as separate facts. No missing permission is filled in by assumption.', 'A museum records an object’s maker and chain of custody separately from permission to reproduce it in a catalogue.', 'Provenance helps identify the source; it cannot itself grant rights that the source did not state.'),
      download: note('A reproducible audit needs the same bytes, and archive extraction must not let source-controlled filenames write outside the intended data folder.', 'The script downloads one archive, compares every byte through SHA-256, opens it as data, selects nine named regular files and writes them under the ignored raw-data directory.', 'Accept a sealed shipment only when its tamper code matches, then unpack only the nine items listed on the order form.', 'A matching hash proves byte identity with the recorded archive, not correctness, safety or licensing.'),
      structure: note('A malformed column index or unknown operator can break training targets and evaluation long after data loading seems successful.', 'Every JSON line is parsed. The question, table identifier, selected column, aggregation and each condition are checked against the matching table schema and the permitted grammar.', 'A compiler checks that every instruction names a real shelf and uses an allowed verb before the librarian follows it.', 'Structural validity does not show that an annotation expresses the question’s intended meaning.'),
      correctness: note('Program text has more than one spelling. A strict text-like comparison can reject a harmless reordering, while execution can reveal that the returned answer is unchanged.', 'Exact match compares structured fields. Execution assembles a restricted query, runs it on the frozen table and compares result rows. Both signals are kept because each exposes a different failure.', 'Two recipes may list commutative preparation steps in a different order yet produce the same dish; checking both the instructions and result explains the difference.', 'Matching one result does not prove two programs behave identically on every possible table.'),
      'safe-execution': note('SQL is executable code, so a generated string can read unintended data, consume excessive resources or change state if it reaches the wrong database.', 'Lesson 1 accepts only known structured references, allowlists operators, parameterises values, opens SQLite files read-only and enables query-only mode. Free-form model output is not executed here.', 'Test a machine’s instruction cards in a locked training room with disconnected controls and a short list of permitted actions.', 'Isolation reduces specific risks; it does not make arbitrary model-generated programs trustworthy.'),
      run: note('A command must preserve enough evidence to distinguish what was observed locally from what the published course claims.', 'The audit verifies files, calculates counts, runs a seeded execution sample and atomically writes ignored JSON. The browser fetches either local or reference evidence according to the selected mode.', 'A private lab notebook and a reviewed museum placard may describe the same experiment, but one does not become the other without review.', 'A completed script shows that its declared checks ran; it does not prove the checks cover every dataset defect.'),
      'limits-next': note('Closing a lesson with explicit limits prevents a successful plumbing test from being mistaken for a successful model.', 'The preserved contract and evaluator become fixed inputs to Lesson 2. Candidate models may vary, while data visibility, evaluation splits and execution restrictions stay constant.', 'Calibrate the measuring instrument before comparing engines, then keep that instrument unchanged during the comparison.', 'A frozen benchmark improves fairness within WikiSQL; it does not guarantee transfer to joins, private schemas or production traffic.'),
    },
  },
};
