import type { BeginnerGuide, BeginnerSectionGuide } from './beginner-guidance';

const note = (why: string, mechanism: string, analogy: string, boundary?: string): BeginnerSectionGuide => ({ why, mechanism, analogy, boundary });

export const sqlBeginnerGuidance: Record<string, BeginnerGuide> = {
  'task-and-dataset-audit': {
    background: 'Earlier projects repeatedly predicted the next piece of text. This project asks for a checkable transformation instead: read a question and a description of one table, then produce a small database program. Before any model changes, we must define exactly what information is allowed and what result counts as correct.',
    picture: 'Imagine writing instructions for a librarian who may see a visitor’s question and the catalogue headings, but not the answer card. The instructions are tested in a sealed practice catalogue before they are trusted.',
    misconception: 'SQL that looks plausible is not necessarily correct, and SQL that differs from a reference string is not necessarily wrong. The returned database rows provide stronger evidence than appearance alone.',
    goal: 'Explain the English-to-SQL input and output boundary, why execution and exact match answer different questions, and why the benchmark evaluator must remain isolated from real databases.',
    notes: {
      departure: note('Changing from pretraining to task adaptation changes what the experiment must prove. General next-token ability is only a starting condition, not evidence of database correctness.', 'A future pretrained base will receive a question plus column descriptions and emit a restricted program. This lesson freezes that interface and its tests before any weights or adapters are chosen.', 'Before hiring a translator, write the job specification and the marking scheme for the trial translation.', 'The model will calculate token probabilities; it does not understand a database or intend to answer the user.'),
      contract: note('Without a fixed boundary, a model could appear accurate by seeing table contents, reference answers, or test examples that should be hidden.', 'The contract names each permitted input field, the restricted output grammar, the held-out split and the primary metric. Later scripts must serialize exactly those allowed fields.', 'A sealed exam states which reference sheet is allowed, what form answers must take and which questions remain locked away.', 'A benchmark contract supports fair comparison inside this task; it does not certify use on different schemas or live systems.'),
      provenance: note('Training data carries legal and interpretive constraints as well as examples. An unclear licence can block redistribution even when the files are technically easy to download.', 'The manifest records the upstream archive, fixed hash, version, code licence and unresolved dataset-licence question as separate facts. No missing permission is filled in by assumption.', 'A museum records an object’s maker and chain of custody separately from permission to reproduce it in a catalogue.', 'Provenance helps identify the source; it cannot itself grant rights that the source did not state.'),
      download: note('A reproducible audit needs the same bytes, and archive extraction must not let source-controlled filenames write outside the intended data folder.', 'The script downloads one archive, compares every byte through SHA-256, opens it as data, selects nine named regular files and writes them under the ignored raw-data directory.', 'Accept a sealed shipment only when its tamper code matches, then unpack only the nine items listed on the order form.', 'A matching hash proves byte identity with the recorded archive, not correctness, safety or licensing.'),
      structure: note('A malformed column index or unknown operator can break training targets and evaluation long after data loading seems successful.', 'Every JSON line is parsed. The question, table identifier, selected column, aggregation and each condition are checked against the matching table schema and the permitted grammar.', 'A compiler checks that every instruction names a real shelf and uses an allowed verb before the librarian follows it.', 'Structural validity does not show that an annotation expresses the question’s intended meaning.'),
      correctness: note('Program text has more than one spelling. A strict text-like comparison can reject a harmless reordering, while execution can reveal that the returned answer is unchanged.', 'Exact match compares structured fields. Execution assembles a restricted query, runs it on the frozen table and compares result rows. Both signals are kept because each exposes a different failure.', 'Two recipes may list commutative preparation steps in a different order yet produce the same dish; checking both the instructions and result explains the difference.', 'Matching one result does not prove two programs behave identically on every possible table.'),
      'safe-execution': note('SQL is executable code, so a generated string can read unintended data, consume excessive resources or change state if it reaches the wrong database.', 'Lesson 1 accepts only known structured references, allowlists operators, parameterises values, opens SQLite files read-only and enables query-only mode. Free-form model output is not executed here.', 'Test a machine’s instruction cards in a locked training room with disconnected controls and a short list of permitted actions.', 'Isolation reduces specific risks; it does not make arbitrary model-generated programs trustworthy.'),
      run: note('A command must preserve enough evidence to distinguish what was observed locally from what the published course claims.', 'The audit verifies files, calculates counts, runs a seeded execution sample and atomically writes ignored JSON. The browser fetches either local or reference evidence according to the selected mode.', 'A private lab notebook and a reviewed museum placard may describe the same experiment, but one does not become the other without review.', 'A completed script shows that its declared checks ran; it does not prove the checks cover every dataset defect.'),
      'limits-next': note('Closing a lesson with explicit limits prevents a successful plumbing test from being mistaken for a successful model.', 'The preserved contract and evaluator become fixed inputs to Lesson 2. Candidate models may vary, while data visibility, evaluation splits and execution restrictions stay constant.', 'Calibrate the measuring instrument before comparing engines, then keep that instrument unchanged during the comparison.', 'A frozen benchmark improves fairness within WikiSQL; it does not guarantee transfer to joins, private schemas or production traffic.'),
    },
  },
  'base-model-selection': {
    background: 'A pretrained model already contains patterns learned from earlier text, but that does not show it can obey this course’s narrow database interface. We compare possible starting points before changing any weights.',
    picture: 'Two experienced translators sit the same sealed practical test. The winner must be accurate enough, licensed for the job and small enough to work in the available room.',
    misconception: 'More parameters do not guarantee better task behavior, and a valid-looking SQL string does not guarantee the returned answer is right.',
    goal: 'Explain why the development split chooses a base model, why test stays closed, and how correctness and local resource cost enter a predeclared decision.',
    notes: {
      question: note('A model name or leaderboard cannot answer whether one pinned conversion works for this exact local task.', 'Two instruction-tuned candidates receive the same development questions and output grammar before any training.', 'Audition two translators with the same material instead of hiring from résumé length alone.', 'The result ranks only this candidate set and protocol.'),
      boundary: note('Using final exam questions to choose a student would make the final score circular.', 'A seeded development sample supports choices while the test loader is never called.', 'Practice papers guide preparation; the sealed exam estimates the final result.', 'Repeated development choices can still overfit the development split.'),
      criteria: note('Rules written after seeing scores can quietly favor the desired winner.', 'Eligibility and tie breakers are saved before model processes start.', 'Publish race rules before runners cross the finish line.', 'Licence metadata needs human review and is not legal advice.'),
      'safe-output': note('Generated SQL is program text and must not receive automatic trust.', 'Text is parsed into a small allowlisted structure, then rebuilt with parameters for a read-only database.', 'A clerk transcribes a request onto an approved form before a locked machine accepts it.', 'The sandbox covers WikiSQL’s grammar, not arbitrary production SQL.'),
      run: note('A reproducible selection needs exact model revisions, samples and machine measurements.', 'Separate workers load each model, generate greedily and write ignored local evidence.', 'Test each appliance on the same meter and keep the inspection sheets.', 'Download and timing vary with cache and hardware.'),
      interpret: note('Zero-training behavior is a starting measurement, not the expected end of adaptation.', 'Validity, exact structure and execution expose different failure stages.', 'A trainee may speak fluently yet fail the company’s exact order form.', 'A 24-example screen has wide uncertainty.'),
      'limits-next': note('Freezing the selected base prevents later prompt experiments from changing two variables at once.', 'The next lesson reads the recorded model ID and revision directly.', 'Bolt down the engine before comparing gearboxes.', 'A better untested model may exist outside the two candidates.'),
    },
  },
  'prompt-formatting': {
    background: 'The same table schema can be written as a short list, a database declaration or JSON. Models tokenize those strings differently, so representation can change behavior even when the facts are identical.',
    picture: 'One address can appear on a handwritten label, a postal form or a barcode record. The destination is unchanged, but the reader may handle each format differently.',
    misconception: 'Prompt engineering is not permission to show hidden answers. A clearer prompt must preserve the same allowed information.',
    goal: 'Identify the one changed prompt field, explain how leakage is prevented, and justify freezing a selected serialization before training.',
    notes: {
      inherit: note('Reusing the Lesson 2 selection keeps this comparison interpretable.', 'The result file supplies the exact model revision and its chat template wraps every variant.', 'Use the same reader when comparing three form designs.', 'The conclusion is specific to that model and tokenizer.'),
      'three-formats': note('Models may recognize structural conventions differently.', 'Each form contains identical column IDs, names and types in a different serialization.', 'A parts list, blueprint annotation and inventory JSON can describe the same machine.', 'Comments and punctuation still change token sequences.'),
      control: note('Changing multiple fields would hide which choice caused a difference.', 'Only schema serialization varies across a fresh development sample.', 'Taste three recipes that differ only in one spice.', 'Sampling noise is removed with greedy decoding, not all experimental uncertainty.'),
      leakage: note('Cell values and answers could make the benchmark artificially easy.', 'Prompts contain schema metadata and question text only, with zero demonstrations.', 'A map may show roads but not the examiner’s marked route.', 'Other text in pretrained data cannot be fully audited here.'),
      run: note('The chosen format must be backed by saved outputs rather than intuition.', 'One loaded model evaluates compact, DDL and JSON prompts under matched settings.', 'Ask one translator to complete three matched form types.', 'Cache state can affect timing but not the declared correctness rule.'),
      interpret: note('Token count measures cost while execution measures task success.', 'Correctness tie breakers are applied before shorter prompt length.', 'Choose the accurate form first, then the cheaper equally accurate one.', 'A tiny sample can produce ties by chance.'),
      'limits-next': note('Training must not silently change the interface selected during evaluation.', 'The chosen style is read into every chat training record.', 'Print the approved form before training staff to fill it.', 'New tasks or schemas may require a new format experiment.'),
    },
  },
  'lora-fine-tuning': {
    background: 'Full fine-tuning changes every model weight and stores large optimizer state. LoRA leaves the pretrained matrices frozen and learns a much smaller additive route for the SQL task.',
    picture: 'Instead of rebuilding a machine, attach a small adjustable control module. The original mechanism still does most of the work, and the module nudges selected stages.',
    misconception: 'A small adapter is not a complete model and is not automatically good. It requires its exact base weights and measured behavior.',
    goal: 'Explain the zero-effect adapter, prompt-masked loss, bounded training recipe and evidence needed to claim that adaptation changed behavior.',
    notes: {
      'why-lora': note('Parameter-efficient adaptation makes a real pretrained-model experiment feasible on the reference laptop.', 'Two low-rank matrices add a learned update beside frozen linear layers.', 'Attach a compact steering linkage instead of replacing an engine.', 'Frozen base weights can still carry all their original limitations.'),
      'before-state': note('A before checkpoint separates adapter wiring from learned change.', 'The second LoRA matrix begins at zero, making the initial additive path zero.', 'Install a volume knob initially set to neutral and verify the sound is unchanged.', 'Numerical or configuration differences must still be tested.'),
      data: note('Training and validation need distinct roles, and test must remain untouched.', 'Seeded train/dev subsets become hashed chat records using the frozen prompt.', 'Practice from one workbook, check progress with another, keep the exam sealed.', 'A small subset may not cover rare query patterns.'),
      recipe: note('A fixed budget prevents repeated tuning from disguising selection as confirmation.', 'Rank, layers, batch, updates, learning rate and sequence cap are recorded.', 'Give every training attempt the same tools and time allowance.', 'The teaching recipe is not claimed optimal.'),
      run: note('Checkpoints and logs make the transition from no update to trained adapter visible.', 'The command saves zero-update and 100-update adapters, then evaluates base, random and trained states.', 'Photograph a device before adjustment, at neutral, and after calibration.', 'Model downloads live in an external cache; experiment files remain local.'),
      interpret: note('Lower token loss may not produce the correct executable program.', 'Loss traces are read beside valid SQL, exact match and execution.', 'Neater handwriting does not ensure the filled form requests the right item.', 'Development behavior does not estimate final test performance.'),
      'limits-next': note('Test must open only after all selectable choices are frozen.', 'The adapter checksum and prompt style become immutable inputs to Lesson 5.', 'Seal the finished entry before opening the competition course.', 'A disappointing final score cannot be repaired with post-test tuning.'),
    },
  },
  'execution-evaluation': {
    background: 'SQL is useful because it can be executed. The final lesson compares the returned database rows from a frozen base model and its trained adapter on questions that were not used for model, prompt or training decisions.',
    picture: 'Two written routes may use different wording but reach the same destination. Test the journey inside a fenced course, then compare where each route actually ends.',
    misconception: 'Execution accuracy is stronger than visual plausibility, but matching one table result does not prove two programs are equivalent everywhere or safe in production.',
    goal: 'Describe the frozen test protocol, safe execution path, failure groups and the bounded claim that closes the project.',
    notes: {
      freeze: note('Final evidence is trustworthy only when decisions precede observation.', 'Protocol and adapter checksum are written before loading the sampled test examples.', 'Register runners and equipment before revealing the course.', 'The sample is smaller than the complete test split.'),
      metric: note('SQL strings can differ harmlessly or match structurally while returning an unintended answer.', 'Execution rows are primary; parsed exact match and validity diagnose the route.', 'Check both a recipe card and the resulting dish.', 'One database state cannot prove universal equivalence.'),
      sandbox: note('Generated programs can be dangerous if passed directly to a database.', 'An allowlist parser creates a logical form; parameterized SQL runs read-only.', 'Only approved instruction cards operate a disconnected training machine.', 'This is not a security certification for live systems.'),
      errors: note('A single score does not tell the learner what went wrong.', 'Failures are grouped by grammar, selected column, aggregation and conditions.', 'Sort failed exam answers by the first mistaken step.', 'Automatic groups can miss deeper semantic causes.'),
      run: note('The test command must be repeatable without becoming a new selection loop.', 'Both frozen checkpoints receive the same 100 seeded questions and greedy settings.', 'Run two sealed entries on the same marked course once.', 'Reruns verify mechanics; they must not guide a replacement winner.'),
      interpret: note('Adaptation is an empirical intervention, not a guaranteed improvement.', 'Signed deltas preserve gains, ties and regressions honestly.', 'A modification earns its place by the measured trial, not by its label.', 'Small-count differences have substantial uncertainty.'),
      close: note('Course completion should state what was learned and what remains unsupported.', 'The final evidence links pretrained weights, low-rank adaptation and executable evaluation.', 'Close a lab notebook with conclusion, scope and next question.', 'WikiSQL does not represent joins, private data or production traffic.'),
    },
  },
};
