import type { BeginnerGuide } from './beginner-guidance';

const note = (why: string, mechanism: string, analogy: string, boundary?: string) => ({ why, mechanism, analogy, boundary });

export const tinyStoriesBeginnerGuidance: Record<string, BeginnerGuide> = {
  'transition-to-subwords': {
    background: 'Project 1 already established the repeating chain: text becomes token IDs; token IDs enter a model; the model emits next-token scores; training would compare those scores with known answers and update weights; inference instead samples from fixed weights. TinyStories preserves that chain but changes the size of the text pieces, the amount and origin of data, and eventually the size of the model.',
    picture: 'Shakespeare assembled text from single-letter and punctuation tiles. TinyStories introduces a box containing both small tiles and frequently useful larger pieces. A sentence can therefore fit on a shorter row, leaving room for more of the story inside the model’s fixed viewing area.',
    misconception: 'Changing to larger text pieces does not give the model vocabulary knowledge or grammar. The tokenizer only defines a reversible numbering system; useful prediction patterns still require weight updates during later training.',
    goal: 'Explain why the second project changes token scale, trace one story from source row to subword IDs and random logits, and distinguish a pipeline smoke test from pretraining.',
    notes: {
      departure: note('Character tokens are wonderfully transparent, but they consume many sequence positions. That limits how much of a story fits into one model calculation.', 'The tokenizer replaces common byte sequences with single IDs. The same context limit can then represent more visible text, while rare strings remain representable as smaller pieces.', 'Packing a suitcase with a mixture of folded garments and small loose items uses fewer slots than placing every thread in its own compartment.', 'Subword pieces are a storage and computation choice. They are not concepts in the model’s mind, and a longer visible passage does not guarantee that the model will use it well.'),
      question: note('A new project introduces several changes at once. Naming the exact learning question and what is not yet being tested prevents an early technical success from becoming an unsupported capability claim.', 'This lesson exercises every connection once with a bounded sample and random weights. Later lessons freeze data, tokenizer, batching and architecture separately before training begins.', 'A theatre performs a technical rehearsal to test lights, microphones and scene changes before judging the acting or the play.', 'A successful rehearsal proves the equipment connects; it does not prove the eventual performance will be good.'),
      source: note('Models reproduce statistical patterns from their supplied material, so authorship and generation process affect what can be learned and what claims are fair.', 'The TinyStories authors prompted larger language models to create simplified stories. We retain the source, split and recorded licence, then inspect the resulting text rather than treating “dataset” as a neutral box.', 'Before using a box of practice essays, a teacher asks who wrote them, under what instructions, and whether the same templates were reused.', 'Provenance reveals origin and constraints, not every hidden bias, error or duplicated idea in millions of generated stories.'),
      download: note('Downloading only convenient rows without recording which ones would make later comparisons impossible to reconstruct.', 'A fixed seed selects page offsets; each saved record keeps its original row number; the manifest records hashes. A hash changes when file bytes change, so it can detect a mismatch.', 'It is sampling numbered books from known library shelves and sealing an inventory with tamper-evident fingerprints.', 'A checksum detects changed bytes but cannot say whether the stories are correct, representative or ethically suitable.'),
      inspect: note('Training cost and evaluation credibility depend on story lengths, duplicates and split separation. These are data properties, not model settings.', 'The script counts stories, characters, simple whitespace-separated words, length percentiles and exact repeated texts separately for train and validation. The next audit will test subtler similarity across stories.', 'Before creating exam worksheets, count pages, find photocopies and ensure practice and exam piles are not the same stack.', 'Finding zero exact duplicates in 1,200 sampled stories does not prove the full dataset contains no duplicates or near-copies.'),
      tokenizer: note('The model needs a finite list of possible outputs. Whole words create an awkwardly huge list, while single characters create long sequences; BPE supplies a measurable compromise.', 'BPE begins with byte-level pieces and repeatedly joins frequent neighbours. The final file stores the vocabulary and merge rules so encoding and decoding follow the same procedure later.', 'A print shop starts with individual symbols, then creates reusable stamps for common combinations such as “ing” when repeated assembly wastes space.', 'The algorithm follows frequency, not grammar or meaning. A merged piece may look like a word or syllable without representing one linguistic idea.'),
      'random-model': note('Running before training creates the control condition needed to show that later structure came from updates rather than from the architecture or decoding software.', 'Seeded random numbers fill embedding, attention, feed-forward and output matrices. Token IDs flow through those matrices and produce one raw score for each vocabulary entry.', 'A newly wired sound mixing desk can pass a signal before its thousands of knobs have been adjusted for the concert.', 'The desk comparison explains adjustable state, but the model has no operator listening inside it and no intention behind its random scores.'),
      invoke: note('“The model ran” can mean either a forward calculation or a training update. This lesson isolates forward inference so the distinction is visible.', 'Eight sequences enter as integer arrays; the model returns a score grid; loss reads how poor the random scores were. During generation, one sampled ID is appended repeatedly. No backward calculation or stored weight changes occur.', 'A printer can produce a page from its current settings; measuring the bad print does not recalibrate it unless a separate correction step changes the controls.', 'Sampling adds pseudo-random variation to visible text, but it does not teach the model and should not be mistaken for creativity.'),
      'limits-next': note('A trustworthy experiment ends by separating what its evidence answers from attractive questions it has not tested.', 'We mark each pipeline connection as working, retain the random checkpoint, and leave dataset quality, tokenizer choice, architecture choice and learned story quality open for controlled lessons.', 'A pre-flight checklist can establish that engines, instruments and controls respond while still refusing to certify the entire journey complete.', 'Passing the checklist reduces known engineering risk; it neither guarantees safe data nor predicts final model quality.'),
    },
  },
};
