import type { ReactNode } from 'react';
import BeginnerTerm from '@/app/components/BeginnerTerm';
import TinyStoriesBatchingPanel from '@/app/components/TinyStoriesBatchingPanel';
import TinyStoriesDatasetAuditPanel from '@/app/components/TinyStoriesDatasetAuditPanel';
import TinyStoriesRandomBaselinePanel from '@/app/components/TinyStoriesRandomBaselinePanel';
import TinyStoriesPretrainingPanel from '@/app/components/TinyStoriesPretrainingPanel';
import TinyStoriesTokenizerPanel from '@/app/components/TinyStoriesTokenizerPanel';
import TinyStoriesTransitionPanel from '@/app/components/TinyStoriesTransitionPanel';
import type { RichLesson } from './shakespeare-lessons';

function Term({ id, children }: { id: string; children: ReactNode }) {
  return <BeginnerTerm id={id}>{children}</BeginnerTerm>;
}

function Source({ href, children }: { href: string; children: ReactNode }) {
  return <a className="inline-source" href={href} target="_blank" rel="noreferrer">{children} ↗</a>;
}

function Code({ children }: { children: string }) {
  return <pre className="lesson-code"><code>{children}</code></pre>;
}

export const tinyStoriesLessons: RichLesson[] = [
  {
    slug: 'transition-to-subwords',
    title: 'Move from characters to subwords',
    summary: 'Define the second project, inspect a bounded TinyStories sample, build a provisional byte-level BPE tokenizer, and invoke a 938,496-parameter GPT before any training update.',
    outcome: 'The recorded rerun completed the TinyStories input-to-output smoke test in 0.33 seconds: 1,200 stories were inspected, a 2,048-piece provisional vocabulary was built, and random weights produced the expected broken continuation.',
    evidence: 'Complete · tinystories-transition-001 · 0 optimiser updates · Apple GPU',
    sections: [
      {
        id: 'departure', title: 'What changes after Shakespeare?', body: <>
          <p>Shakespeare showed the entire language-model loop with one character per <Term id="token">token</Term>. That transparency came at a cost: <em>Once upon a time</em> occupied 16 character tokens, so a 64-token <Term id="context-window">context window</Term> could see only a short piece of prose.</p>
          <p>TinyStories asks a different question: can a still-small decoder-only transformer learn simple story structure when text is represented by reusable <Term id="subword-token">subword tokens</Term>? A subword may be punctuation, a complete frequent word, or part of a less frequent word. The provisional tokenizer represented <em>Once upon a time, there was</em> as seven pieces: <code>Once</code>, <code> upon</code>, <code> a</code>, <code> time</code>, <code>,</code>, <code> there</code>, and <code> was</code>.</p>
          <aside className="lesson-caveat"><strong>A transition, not a victory</strong><p>Shorter token sequences give the model more text per context window, but tokenisation alone does not create grammar or story understanding. Random weights remain random after the tokenizer is built.</p></aside>
        </>,
      },
      {
        id: 'question', title: 'Freeze the learning question and guardrails', body: <>
          <p>The project objective is to train a roughly 5–15 million parameter GPT-like model from random weights and test whether it can continue simple story prompts more coherently than our character-level Shakespeare model. Lesson 1 does not select that final size. It performs a <Term id="smoke-test">smoke test</Term>: one deliberately small run through download → inspect → tokenize → tensor → random model → logits → sampled text.</p>
          <table className="lesson-table"><tbody>
            <tr><th>Changed from Project 1</th><td>Corpus, token scale, vocabulary size, expected model scale and story-focused evaluation</td></tr>
            <tr><th>Preserved</th><td>Random baseline, held-out data, causal prediction, checkpoint evidence, controlled comparisons and local/reference separation</td></tr>
            <tr><th>Not happening yet</th><td>No optimiser, gradients, pretraining, architecture selection or claim of story quality</td></tr>
            <tr><th>Hardware boundary</th><td>32 GB Apple-silicon reference machine; later scale is chosen from measurements rather than the maximum allocation we can force</td></tr>
          </tbody></table>
        </>,
      },
      {
        id: 'source', title: 'Know what TinyStories actually is', body: <>
          <p>TinyStories is a <Term id="synthetic-dataset">synthetic dataset</Term>: its stories were generated by GPT-3.5 and GPT-4 rather than collected as naturally occurring children&apos;s writing. The authors designed it around vocabulary familiar to typical three- to four-year-olds so very small language models could be studied. Read the <Source href="https://arxiv.org/abs/2305.07759">TinyStories paper</Source> beside the <Source href="https://huggingface.co/datasets/roneneldan/TinyStories">hosted dataset card and files</Source>.</p>
          <p>The host records the dataset licence as <code>CDLA-Sharing-1.0</code>. The source currently exposes 2,119,719 training stories and 21,990 validation stories. The original repository is several gigabytes, so this first lesson intentionally downloads only a reproducible feasibility slice.</p>
          <aside className="lesson-caveat"><strong>Generated data changes the interpretation</strong><p>A model trained here can learn fluent-looking patterns, repeated templates, assumptions and mistakes inherited from the systems that generated the stories. “Vocabulary for young children” describes a design constraint; it does not prove developmental suitability, human authorship, factual accuracy or freedom from bias.</p></aside>
        </>,
      },
      {
        id: 'download', title: 'Download a bounded, traceable sample', body: <>
          <Code>{`uv run --no-sync python scripts/download_tinystories_sample.py`}</Code>
          <p>The script uses Python&apos;s standard HTTP and JSON libraries to request rows from the Hugging Face dataset service. Seed 42 selects ten non-overlapping 100-story pages from the official training split; seed 43 selects two pages from the official validation split. Every JSONL row retains its original <code>sourceRow</code>.</p>
          <p>It writes ignored files under <code>data/raw/tinystories-sample/</code>: <code>train.jsonl</code>, <code>validation.jsonl</code>, and a manifest containing source, recorded licence, retrieval time, selected offsets and SHA-256 checksums. The reference sample hashes are <code>7cc2…26c1</code> for training and <code>5be6…82b</code> for validation.</p>
          <p>This is <Term id="reproducibility">reproducibility</Term> evidence, not a guarantee that a mutable hosted dataset will never change. A later public release must either pin immutable source artifacts or publish a documented subset manifest that remains obtainable.</p>
        </>,
      },
      {
        id: 'inspect', title: 'Inspect before choosing the full course subset', body: <>
          <table className="lesson-table"><thead><tr><th>Split</th><th>Stories</th><th>Characters</th><th>Words</th><th>Median story</th><th>95th percentile</th><th>Exact duplicates within split</th></tr></thead><tbody>
            <tr><td>Training sample</td><td>1,000</td><td>839,030</td><td>163,489</td><td>765 characters</td><td>1,500</td><td>0</td></tr>
            <tr><td>Validation sample</td><td>200</td><td>157,955</td><td>30,494</td><td>773 characters</td><td>1,056</td><td>0</td></tr>
          </tbody></table>
          <p>The numbers answer a narrow feasibility question: this sample is easily large enough to build a tokenizer and fill fixed 128-token batches, while remaining quick to inspect. They do not constitute the full dataset audit. We have not yet measured near-duplicates, repeated templates, train/validation overlap, content categories, malformed stories or coverage of the source distribution.</p>
          <p>We preserve the dataset&apos;s own train and validation split instead of slicing one combined file. That prevents an obvious form of leakage, but the next lesson must test whether very similar generated stories cross the split boundary.</p>
        </>,
      },
      {
        id: 'tokenizer', title: 'Build a provisional byte-level BPE vocabulary', body: <>
          <p>We installed Hugging Face Tokenizers 0.23.1 and followed its documented <Source href="https://huggingface.co/docs/tokenizers/main/quicktour">from-scratch BPE workflow</Source>. <Term id="byte-pair-encoding">Byte Pair Encoding</Term> starts with small pieces, counts adjacent pairs, merges a frequent pair into a reusable larger piece, and repeats until it reaches the requested vocabulary size.</p>
          <p>Our <Term id="byte-level-tokenizer">byte-level tokenizer</Term> begins from byte representations, applies Unicode NFKC normalisation, and learns 2,048 vocabulary entries from only the 1,000 training stories. Four <Term id="special-token">special tokens</Term> reserve structural roles: <code>&lt;pad&gt;</code>, <code>&lt;unk&gt;</code>, <code>&lt;bos&gt;</code>, and <code>&lt;eos&gt;</code>. Validation stories do not teach merge rules.</p>
          <p>The resulting training sample contained 230,867 tokens—3.63 source characters per token on average. Validation averaged 3.55 characters per token. This is promising compression, but 2,048 is only a provisional choice. Lesson 3 will compare multiple vocabulary sizes for coverage, sequence length, model parameter cost and reversible decoding before freezing one.</p>
        </>,
      },
      {
        id: 'random-model', title: 'Construct a GPT with random weights', body: <>
          <p>The experiment reuses the readable decoder-only transformer components from Shakespeare but enlarges the vocabulary, width and context. <Term id="seed">Seed 42</Term> fills every <Term id="weight">weight</Term> with reproducible random values. MLX then materialises them on <code>Device(gpu, 0)</code>.</p>
          <table className="lesson-table"><thead><tr><th>Component</th><th>Configuration</th><th>Trainable values</th></tr></thead><tbody>
            <tr><td>Token embeddings</td><td>2,048 tokens × 128 features</td><td>262,144</td></tr>
            <tr><td>Position embeddings</td><td>128 positions × 128 features</td><td>16,384</td></tr>
            <tr><td>Two transformer blocks</td><td>4 attention heads; 4× feed-forward expansion</td><td>395,520</td></tr>
            <tr><td>Final normalisation and output</td><td>128 features → 2,048 next-token <Term id="logit">logits</Term></td><td>264,448</td></tr>
            <tr><td><strong>Total</strong></td><td>Provisional pipeline model</td><td><strong>938,496</strong></td></tr>
          </tbody></table>
          <p>This is intentionally below the eventual 5–15M target. Its job is to prove shapes, memory and decoding before architecture selection. The official random baseline will be frozen in Lesson 5 after the dataset, tokenizer and batching rules stop moving.</p>
        </>,
      },
      {
        id: 'invoke', title: 'Invoke the untrained model and read the evidence', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_transition.py`}</Code>
          <p>The command loads the two JSONL files, trains the provisional tokenizer, constructs the random model, and forms a fixed <Term id="tensor">tensor</Term> of shape <code>8 × 128</code>. One forward pass produces logits of shape <code>8 × 128 × 2,048</code>. Cross-entropy <Term id="loss">loss</Term> compares those scores with the actual next tokens, but no gradient or optimiser follows.</p>
          <p>For prompted <Term id="inference">inference</Term>, the text <em>Once upon a time, there was</em> becomes seven IDs. The model calculates 2,048 random logits for the next position, temperature rescales them, sampling selects one token, and the process repeats. The saved <code>checkpoint-0000.safetensors</code> therefore records a genuine before-training state.</p>
          <TinyStoriesTransitionPanel />
        </>,
      },
      {
        id: 'limits-next', title: 'Say exactly what Lesson 1 established', body: <>
          <p>We established that the source is reachable, the bounded files are traceable, the tokenizer can encode and decode the material, the intended transformer family fits comfortably, tensor shapes connect, random loss is finite, checkpoint saving works, and generated IDs return to visible text. That removes many plumbing risks before an expensive run.</p>
          <p>We did <strong>not</strong> establish that the dataset is clean, the vocabulary is optimal, 938,496 parameters are sufficient, the fixed-batch loss is a stable estimate, or the model can tell stories. Its broken continuation is evidence that architecture plus tokenizer is not learning.</p>
          <p>Lesson 2 now audits the dataset and freezes the bounded course subset. Only after that will we compare tokenizers, construct causal batches, and define the official random GPT baseline.</p>
        </>,
      },
    ],
  },
  {
    slug: 'dataset-audit',
    title: 'Audit and freeze the development dataset',
    summary: 'Verify the sampled files, measure malformed text, duplication, cross-split similarity, repeated templates, content terms and tokenizer integrity, then freeze a deliberately limited development split.',
    outcome: 'The 1,000/200-story split was frozen as tinystories-development-v1: no exact or ≥80%-similar cross-split pairs were found, but opening-template repetition was substantial.',
    evidence: 'Complete · tinystories-dataset-audit-001 · 200,000 cross-split comparisons · no model training',
    sections: [
      {
        id: 'why-audit', title: 'Why inspect the teaching material before training?', body: <>
          <p>A training loop will faithfully optimise against whatever text it receives. It cannot tell us that a validation story was copied from training, that thousands of stories repeat one template, or that a generated dataset contains undesirable assumptions. Those are data questions, so we ask them before spending compute.</p>
          <p>This lesson sits before the tokenizer comparison because the chosen sample determines which pairs BPE considers frequent. It also sits before model training because <Term id="data-leakage">data leakage</Term> can make validation loss look better without improving genuine generalisation.</p>
          <aside className="lesson-caveat"><strong>Audit does not mean certify</strong><p>Every check detects a defined pattern. Passing it narrows uncertainty; it never proves that two million source stories are unbiased, safe, factual, diverse or suitable for every learner.</p></aside>
        </>,
      },
      {
        id: 'freeze-inputs', title: 'Verify the exact files and preserve provenance', body: <>
          <p>The audit reloads the Lesson 1 <Term id="data-manifest">data manifest</Term> and recomputes SHA-256 for both JSONL files. It stops before analysis if either hash differs. This prevents an audit result from being silently attached to changed text.</p>
          <table className="lesson-table"><tbody>
            <tr><th>Dataset source</th><td><Source href="https://huggingface.co/datasets/roneneldan/TinyStories">roneneldan/TinyStories dataset repository</Source></td></tr>
            <tr><th>Research description</th><td><Source href="https://arxiv.org/abs/2305.07759">Eldan and Li, TinyStories</Source></td></tr>
            <tr><th>Recorded host licence</th><td>CDLA-Sharing-1.0; review again before redistribution</td></tr>
            <tr><th>Training selection</th><td>1,000 source rows selected from ten seeded, non-overlapping API pages</td></tr>
            <tr><th>Validation selection</th><td>200 source rows selected separately from two seeded API pages</td></tr>
          </tbody></table>
          <p>Original source-row identifiers stay beside each story. The course does not commit the story text; it commits the reviewed hashes, selection settings, measurements and limitations needed to identify the reference experiment.</p>
        </>,
      },
      {
        id: 'command', title: 'Run a read-only audit over text and tokenizer', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_dataset_audit.py`}</Code>
          <p>The program uses Python 3.12 standard-library JSON, hashing, Unicode, regular-expression and counting tools plus Hugging Face Tokenizers 0.23.1. It loads the provisional tokenizer created in Lesson 1 only to test encoding; it creates no neural-network architecture, calculates no logits and performs no optimiser update.</p>
          <p>Results are written atomically to <code>public/data/local/tinystories-dataset-audit.json</code>. The local configuration goes to <code>work/experiments/tinystories-dataset-audit-001/config.json</code>. Reference mode reads the separately reviewed promoted copies.</p>
        </>,
      },
      {
        id: 'integrity', title: 'Check structure before judging content', body: <>
          <p>The integrity pass checks that every JSON line contains an integer source row and string text, then counts empty stories, repeated source IDs, Unicode replacement characters and unexpected control characters. It also flags very short and very long stories for inspection rather than deleting them automatically.</p>
          <p>Length is descriptive evidence. A 700-word story is not corrupt merely because most stories are shorter, but it affects token batching and may dominate more training windows. Automatic removal would change the dataset distribution, so any future filter must be a separate versioned decision.</p>
        </>,
      },
      {
        id: 'leakage', title: 'Test exact and near-duplicate leakage', body: <>
          <p>Exact matching first compares raw text, then repeats after Unicode NFKC <Term id="normalisation">normalisation</Term>, lower-casing and whitespace collapse. That catches files which differ only in superficial representation.</p>
          <p>For <Term id="near-duplicate">near duplicates</Term>, each story becomes a set of consecutive five-word sequences. Every validation story is compared with every training story using <Term id="jaccard-similarity">Jaccard similarity</Term>: the shared five-word sequences divided by all distinct five-word sequences in the pair. At the frozen threshold of 0.80, a pair must share most of its local wording to be flagged.</p>
          <p>This produces 200 × 1,000 = 200,000 comparisons. It is a deliberately interpretable check, but paraphrases with different words may evade it and common templates can remain visible without making two whole stories 80% similar.</p>
        </>,
      },
      {
        id: 'templates', title: 'Separate leakage from template diversity', body: <>
          <p>Two stories can share a formulaic opening and still have low whole-story Jaccard similarity. We therefore count the first five normalised words and several recurring phrases separately. This addresses a different question: how narrow is the style the model is likely to imitate?</p>
          <p>A dominant opening is not train/validation leakage by itself because it can appear across many distinct stories. It is still important: a model can reduce loss and generate plausible openings by mastering repeated scaffolds before it learns longer consistency.</p>
          <TinyStoriesDatasetAuditPanel />
        </>,
      },
      {
        id: 'content-screen', title: 'Use keyword screens as triage, not judgement', body: <>
          <p>The audit counts stories containing small, declared groups of injury/death, fear/danger and conflict words. This locates material for later human inspection and proves that “simple vocabulary” does not mean every story is emotionally neutral.</p>
          <p>A keyword hit is not automatically harmful: a story may say that a character avoided danger or helped someone who was hurt. A story without those words may still contain unsuitable ideas. We preserve the method and counts while explicitly refusing to call it a safety classifier.</p>
        </>,
      },
      {
        id: 'tokenizer-check', title: 'Confirm that the provisional tokenizer preserves the split', body: <>
          <p>The existing byte-level BPE tokenizer encodes and decodes every story. The audit counts unknown-token IDs and compares decoded output with each story after the tokenizer&apos;s declared NFKC normalisation. It also measures tokens per story separately for training and validation.</p>
          <p>This is an integrity gate, not tokenizer selection. Zero unknowns and reversible decoding mean the provisional vocabulary can represent the data; Lesson 3 still has to compare vocabulary sizes, compression, sequence lengths and output-layer parameter cost.</p>
        </>,
      },
      {
        id: 'decision', title: 'Freeze a development split—and preserve its boundary', body: <>
          <p>The verified hashes, source rows and audit configuration now define <code>tinystories-development-v1</code>. Lessons 3–8 may use it for tokenizer comparison, batching, the official random baseline and short training-recipe experiments. Keeping that input fixed makes those comparisons interpretable.</p>
          <p>It is deliberately <strong>not approved</strong> as the final scaling corpus or as evidence about the complete TinyStories distribution. With only 228,867 ordinary training tokens under the provisional tokenizer, it is a fast laboratory slice rather than an adequate one-pass corpus for a 5–15M parameter final model.</p>
          <p>Next, Lesson 3 trains several BPE vocabularies on this exact training split and evaluates them on the frozen validation split. No model weights will be trained until the tokenizer decision is recorded.</p>
        </>,
      },
    ],
  },
  {
    slug: 'tokenizer-experiment',
    title: 'Compare and freeze the subword tokenizer',
    summary: 'Train four byte-level BPE vocabularies on the same frozen stories, test representation integrity and sequence compression on held-out stories, expose model-interface cost, and use a declared rule to select one tokenizer.',
    outcome: 'The reproducible procedure and My Lab dashboard are ready. Reference evidence remains intentionally unpromoted until a separate maintainer review.',
    evidence: 'Active lesson · four candidate vocabularies · tokenizer training only · no neural-model updates',
    sections: [
      {
        id: 'question', title: 'Why can the tokenizer change the model experiment?', body: <>
          <p>A tokenizer fixes both sides of the language-model interface. It converts text into input IDs, and its <Term id="vocabulary">vocabulary</Term> defines every possible next-token output. A small vocabulary assembles prose from many short pieces; a large vocabulary offers more reusable pieces but asks the model to score more alternatives at every position.</p>
          <p>Lesson 1 proved that 2,048 pieces worked. This lesson asks a controlled question: among 512, 1,024, 2,048 and 4,096-piece byte-level BPE tokenizers, which one best matches our stated preference for compact sequences without spending too much of a small model on vocabulary-specific weights?</p>
          <aside className="lesson-caveat"><strong>Tokenizer training is not model training</strong><p>BPE counts adjacent text pieces and stores merge rules. It creates no transformer weights, logits, loss, gradients or language capability. The eventual model will learn only after later optimiser updates.</p></aside>
        </>,
      },
      {
        id: 'fixed-inputs', title: 'Hold the data and tokenizer recipe fixed', body: <>
          <p>Every candidate reads the exact <code>tinystories-development-v1</code> training file approved in Lesson 2. The command refuses to continue if the JSONL hashes differ from either the source manifest or the local audit. The 200 validation stories remain <Term id="validation-set">held out</Term>: they measure the finished tokenizer but never teach its merge rules.</p>
          <table className="lesson-table"><tbody>
            <tr><th>Training input</th><td>1,000 frozen training stories; SHA-256 checked before use</td></tr>
            <tr><th>Held-out input</th><td>200 frozen validation stories; encoded only after each vocabulary is trained</td></tr>
            <tr><th>Shared pipeline</th><td>NFKC normalisation → byte-level pre-tokenisation → BPE with minimum pair frequency 2</td></tr>
            <tr><th>Shared structure</th><td><code>&lt;pad&gt;</code>, <code>&lt;unk&gt;</code>, <code>&lt;bos&gt;</code>, <code>&lt;eos&gt;</code> fixed at IDs 0–3</td></tr>
            <tr><th>Only changed variable</th><td>Requested vocabulary size: 512, 1,024, 2,048 or 4,096</td></tr>
          </tbody></table>
        </>,
      },
      {
        id: 'tooling', title: 'Use one implementation for every candidate', body: <>
          <p>The experiment uses Hugging Face Tokenizers 0.23.1. Its <Source href="https://huggingface.co/docs/tokenizers/main/quicktour">official from-scratch quick tour</Source> explains that a BPE trainer repeatedly merges frequent neighbouring pieces until reaching the requested vocabulary size. We pass the 1,000 story strings through the documented <Source href="https://huggingface.co/docs/tokenizers/main/training_from_memory">in-memory iterator interface</Source>.</p>
          <Code>{`tokenizer = build_tokenizer(train_texts, requested_size)
tokenizer.save(candidate_path, pretty=True)
train_metrics = evaluate_split(tokenizer, train_rows)
validation_metrics = evaluate_split(tokenizer, validation_rows)`}</Code>
          <p>The same Rust-backed library code, normaliser, pre-tokenizer, minimum frequency and special-token order are reused for all four candidates. That makes vocabulary size the intended changed variable rather than one member of a bundle of hidden changes. The <Source href="https://huggingface.co/docs/tokenizers/main/api/trainers">BpeTrainer API reference</Source> defines the recorded <code>vocab_size</code>, <code>min_frequency</code>, special-token and initial-alphabet settings.</p>
        </>,
      },
      {
        id: 'command', title: 'Run the comparison and preserve every candidate', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_tokenizer_experiment.py`}</Code>
          <p>The command reads the local Lesson 2 audit, manifest and two raw JSONL files. It trains four tokenizer merge tables in memory, then writes ignored candidate files, <code>tokenizer.json</code> and <code>config.json</code> beneath <code>work/experiments/tinystories-tokenizer-001/</code>. Dashboard evidence is written atomically to <code>public/data/local/tinystories-tokenizer.json</code>.</p>
          <p>The configuration records dependency version, file hashes, candidate sizes, preprocessing, selection thresholds and the checksum of the selected tokenizer. No MLX device is invoked because the computation is text counting and encoding, not tensor training.</p>
        </>,
      },
      {
        id: 'integrity', title: 'Require every tokenizer to return the text', body: <>
          <p>A <Term id="round-trip-test">round-trip test</Term> encodes each story to IDs, decodes those IDs, and compares the returned string with the declared NFKC-normalised source. The audit also counts <code>&lt;unk&gt;</code> IDs and verifies that the four special tokens retain their intended IDs.</p>
          <p>These are hard gates: a candidate with an unknown ID, a changed structural ID or one mismatched story cannot win, regardless of its sequence length. Byte-level starting pieces are meant to make arbitrary encoded text representable, but the observed files still have to prove that the configured pipeline behaves that way.</p>
          <aside className="lesson-caveat"><strong>Reversible does not mean useful</strong><p>A tokenizer could preserve every character by emitting one tiny piece at a time. Integrity establishes that information survived; it says nothing yet about sequence efficiency or eventual model quality.</p></aside>
        </>,
      },
      {
        id: 'compression', title: 'Measure how much text each token position carries', body: <>
          <p>For both splits, the script records total tokens, characters per token, and the minimum, median, mean, 95th-percentile and maximum tokens per story. Characters per token is a simple <Term id="compression-ratio">compression ratio</Term>: larger values mean one token position covers more visible source text on this corpus.</p>
          <p>Shorter sequences let a fixed context window cover more story and reduce the number of training positions needed to traverse the corpus. The metric is corpus-specific: repeated TinyStories phrases may compress well even if unrelated text or another language does not.</p>
        </>,
      },
      {
        id: 'model-cost', title: 'Count the model weights that vocabulary size would create', body: <>
          <p>Our decoder has an input token-embedding table and a separate output projection. With model width <code>d</code> and vocabulary size <code>V</code>, their combined <Term id="vocabulary-dependent-parameters">vocabulary-dependent parameters</Term> are <code>V × d + d × V + V = V × (2d + 1)</code>. Doubling <code>V</code> therefore doubles this part of the model.</p>
          <p>The experiment reports that exact quantity for a 256-wide version of the course architecture. It is a comparison proxy, not the final parameter count: Lesson 5 will freeze width, depth and the complete architecture after sequence batching is defined.</p>
        </>,
      },
      {
        id: 'decision', title: 'Apply a decision rule written before seeing the result', body: <>
          <p>The provisional 2,048-piece vocabulary is the anchor. A smaller candidate wins only if it adds no more than 10% validation tokens; a larger candidate wins only if it removes at least 20%. Otherwise we retain 2,048. These thresholds deliberately require a material sequence benefit before changing the already working interface.</p>
          <p>The dashboard below reads the active evidence mode. My Lab shows the learner-owned run; Reference mode remains “Not run yet” unless a maintainer explicitly reviews and promotes a separate reference result.</p>
          <TinyStoriesTokenizerPanel />
        </>,
      },
      {
        id: 'freeze-next', title: 'Freeze the interface, while keeping the claim narrow', body: <>
          <p>The selected <code>tokenizer.json</code>, its SHA-256 checksum and the full candidate configuration now define the text-to-ID interface for the next TinyStories development lessons. Lesson 4 can therefore compare batching strategies without silently changing how stories are represented.</p>
          <p>This freeze applies to the 1,000-story development corpus. A larger final corpus may contain different frequent pairs, so scaling the data requires an explicit tokenizer re-evaluation rather than blindly reusing today&apos;s merge table.</p>
          <p>Next, we will add beginning/end markers, decide how separate stories become fixed-length causal windows, and inspect input and target tensors by decoding them back to text. The selected tokenizer remains fixed throughout that comparison.</p>
        </>,
      },
    ],
  },
  {
    slug: 'sequence-batching',
    title: 'Build causal batches without mixing stories',
    summary: 'Turn differently sized tokenised stories into fixed 32 × 128 input, target, and loss-mask tensors while preserving every legitimate next-token pair and excluding padding.',
    outcome: 'The reproducible procedure and My Lab dashboard are ready. Reference evidence remains intentionally unpromoted until a separate maintainer review.',
    evidence: 'Available procedure · story-isolated windows · tensor construction only · no model or optimiser updates',
    sections: [
      {
        id: 'why-batching', title: 'Why does the model need batches?', body: <>
          <p>The tokenizer returns one list of token IDs per story, but those lists have different lengths. Efficient accelerator work instead uses rectangular <Term id="tensor">tensors</Term>: rows contain examples, columns contain sequence positions. A <Term id="batch">batch</Term> is a group of those examples processed in one model calculation.</p>
          <p>This lesson therefore defines the questions that future training will ask. Each input position must be paired with its genuine next token, separate stories must remain separate, and structural filler must never become a learning target. Batching is not merely storage housekeeping; a boundary mistake changes the task itself.</p>
        </>,
      },
      {
        id: 'boundaries', title: 'Wrap each story before slicing it', body: <>
          <p>Each story is encoded independently as <code>&lt;bos&gt; + ordinary tokens + &lt;eos&gt;</code>. The beginning marker tells the model that no earlier prose belongs to this story. The ending marker is a real target: learning when stories stop is part of next-token prediction.</p>
          <p>We deliberately do not join one story&apos;s end to another story&apos;s beginning. A joined stream would create an artificial <code>&lt;eos&gt; → &lt;bos&gt;</code> prediction and could let tokens in the new story attend to unrelated prose from the previous one.</p>
          <aside className="lesson-caveat"><strong>Boundaries are experimental policy</strong><p>Other systems use boundary-aware <Term id="sequence-packing">sequence packing</Term> to place multiple short documents in one tensor efficiently. That can be valid, but only when attention and loss rules preserve document separation. We choose the simpler auditable method first.</p></aside>
        </>,
      },
      {
        id: 'shifted-targets', title: 'Make the answer strip by shifting one place', body: <>
          <p>For token IDs <code>[BOS, Once, upon, …]</code>, the inputs are <code>[BOS, Once, upon, …]</code> and the <Term id="shifted-targets">shifted targets</Term> are <code>[Once, upon, …, EOS]</code>. Position zero sees <code>BOS</code> and is graded against <code>Once</code>; position one sees <code>Once</code> and is graded against <code>upon</code>.</p>
          <p>A 128-position training example consequently needs up to 129 consecutive IDs before the shift. Inputs take the first 128 and targets take the following 128. This alignment is what turns one story fragment into 128 next-token questions.</p>
        </>,
      },
      {
        id: 'windowing', title: 'Preserve every adjacent pair across windows', body: <>
          <p>Long stories are read in chunks starting at token 0, 128, 256, and so on. Each chunk reads at most 129 IDs and forms 128 input–target pairs. The last ID of one chunk becomes the first input ID of the next, creating a one-token overlap without grading any pair twice.</p>
          <p>The audit reconstructs every encoded story from its windows and checks that the number of observed target pairs equals <code>story tokens − 1</code>. This catches gaps, duplicated answers, and off-by-one errors before they can silently affect training.</p>
          <aside className="lesson-caveat"><strong>The overlap preserves pairs, not unlimited memory</strong><p>The first prediction in a later chunk sees its boundary token but cannot attend to the preceding 127 tokens from the previous chunk. A 128-token context remains a hard limit.</p></aside>
        </>,
      },
      {
        id: 'padding', title: 'Pad the rectangle, then cover the blank answers', body: <>
          <p>The final chunk of a story is often shorter than 128 questions. <Term id="padding">Padding</Term> fills the unused cells on the right with the reserved <code>&lt;pad&gt;</code> ID so every row has the same shape. Padding is scaffolding created by the batching system, not story text.</p>
          <p>A matching <Term id="loss-mask">loss mask</Term> contains <code>1</code> for each real target and <code>0</code> for padded targets. Later, per-position cross-entropy values will be multiplied by that mask before averaging, so blank cells provide neither error nor gradient.</p>
        </>,
      },
      {
        id: 'causal-mask', title: 'Keep the two masks conceptually separate', body: <>
          <p>The loss mask answers <em>should this position be graded?</em> The <Term id="causal-mask">causal mask</Term> answers <em>which positions may this position inspect?</em> In a 128 × 128 attention grid, a position may use itself and earlier positions but not later ones. That lower-triangular rule prevents the model from reading an answer before predicting it.</p>
          <p>We materialise inputs and targets as 32-bit integer MLX arrays and the loss mask as a 32-bit floating-point array. MLX documents its supported <Source href="https://ml-explore.github.io/mlx/build/html/python/data_types.html">array data types</Source> and its <Source href="https://ml-explore.github.io/mlx/build/html/usage/quick_start.html">lazy array evaluation model</Source>; the script calls <code>mx.eval</code> so the audit measures actual materialised tensors.</p>
        </>,
      },
      {
        id: 'command', title: 'Run the boundary audit and save learner evidence', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_sequence_batching.py`}</Code>
          <p>The command reads the Lesson 3 learner evidence, verifies the frozen <code>tokenizer.json</code> checksum, re-verifies both dataset hashes, and encodes each story independently. It constructs all windows, audits their pair coverage, shuffles only the training-example indices with seed 42, and materialises one fixed batch for each split.</p>
          <p>It uses Python 3.12, Tokenizers 0.23.1, and MLX 0.32.0. It writes ignored <code>public/data/local/tinystories-batching.json</code>, <code>work/experiments/tinystories-batching-001/config.json</code>, and <code>batch-preview.json</code>. No transformer is constructed, no forward loss is calculated, and no weights or optimiser state exist to change.</p>
          <Code>{`visible = story_ids[start:start + context_size + 1]\ninputs = padded_visible[:-1]\ntargets = padded_visible[1:]\nloss_mask = [1.0] * real_targets + [0.0] * padding_targets`}</Code>
        </>,
      },
      {
        id: 'evidence', title: 'Read correctness and efficiency together', body: <>
          <p>The dashboard compares story-isolated padded windows with a deliberately naïve continuous stream. The latter can fill almost every position, but that attractive utilisation number hides false cross-story targets and unrelated prior context. The selected method spends more cells to make the learning questions defensible.</p>
          <p>General transformer tooling often calls the component that pads examples into a batch a <Source href="https://huggingface.co/docs/transformers/en/main_classes/data_collator">data collator</Source>. We implement this small one directly so its boundary, shift, and mask rules remain visible rather than hidden behind a library default.</p>
          <TinyStoriesBatchingPanel />
        </>,
      },
      {
        id: 'freeze-next', title: 'Freeze the batch contract for the random baseline', body: <>
          <p>The selected development contract is now: independent BOS/EOS-wrapped stories, context 128, one-token-overlap windows, right padding, masked padded targets, batch size 32, and a causal attention mask. Those rules remain fixed while Lesson 5 chooses the first training architecture.</p>
          <p>This lesson establishes data-shape and boundary correctness, not model quality or optimal throughput. A later controlled enhancement can test segment-aware packing, but it must reproduce the same legitimate within-story target pairs and demonstrate that no attention crosses story boundaries.</p>
          <p>Next, we will create the official seeded random GPT, record its parameter count, memory, held-out loss, and broken prompt continuations, then save checkpoint zero before any optimiser update.</p>
        </>,
      },
    ],
  },
  {
    slug: 'random-gpt-baseline',
    title: 'Freeze and invoke the random GPT baseline',
    summary: 'Select the smallest architecture inside the declared 5–15M range, materialise seeded random weights, evaluate every frozen validation window, inspect prompt probabilities, and prove checkpoint-zero reload parity before training.',
    outcome: 'The reproducible procedure and My Lab dashboard are ready. Reference evidence remains intentionally unpromoted until a separate maintainer review.',
    evidence: 'Available procedure · 5.82M-parameter GPT · checkpoint step 0 · zero optimiser updates',
    sections: [
      {
        id: 'why-baseline', title: 'Why freeze an official random baseline?', body: <>
          <p>A <Term id="baseline">baseline</Term> is the measured starting condition against which later change is judged. Lesson 1 proved a provisional transformer could run, but its smaller architecture and temporary tokenizer no longer match the system we intend to train. Comparing future checkpoints with that smoke test would mix learning with several design changes.</p>
          <p>Lesson 5 therefore freezes the exact <Term id="model-architecture">model architecture</Term>, tokenizer, batches, prompts, evaluation protocol, and seed that the first pretraining lesson will inherit. It invokes this complete system before any correction step, so later improvements can be attributed to training rather than to missing before-state evidence.</p>
          <aside className="lesson-caveat"><strong>Running is not learning</strong><p>A finite loss, valid probability distribution, or grammatical-looking fragment can occur with random weights. Training requires gradients and optimiser updates; this lesson performs neither.</p></aside>
        </>,
      },
      {
        id: 'size-choice', title: 'Choose a laptop-scale architecture by a declared rule', body: <>
          <p>The project declared a target of roughly 5–15 million <Term id="parameter-count">parameters</Term>. We compare width 192, 256, and 320 while holding six blocks, context 128, and approximately 32 features per attention head. The selected width 256 design contains exactly 5,816,320 trainable numbers: the smallest candidate inside that range.</p>
          <p>This is a resource-oriented starting rule, not a quality result. The wider candidate is deferred until a later scaling lesson can justify its added memory and computation with matched training evidence. The smaller candidate remains useful for reduced-compute adaptations, but would change the declared experiment.</p>
          <Code>{`parameters = token_embedding + position_embedding\nparameters += 6 * (attention + feed_forward + block_norms)\nparameters += final_norm + output_projection`}</Code>
        </>,
      },
      {
        id: 'architecture', title: 'Trace IDs through the six-block decoder', body: <>
          <p>Each token ID retrieves a 256-number embedding, and each of the 128 positions retrieves another 256-number embedding. Their sum passes through six pre-normalised transformer blocks. Every block contains eight-head causal self-attention, a four-times-wider GELU feed-forward network, residual paths, and layer normalisation.</p>
          <p>The final normalisation and untied output projection convert every position into 2,048 <Term id="logit">logits</Term>—one score for every frozen vocabulary token. This is the same decoder-only pattern introduced in Shakespeare, enlarged in width and depth for subword stories. The original <Source href="https://arxiv.org/abs/1706.03762">Transformer paper</Source> describes stacked attention/feed-forward layers, residual connections, normalisation, and masked decoder attention.</p>
          <table className="lesson-table"><thead><tr><th>Component group</th><th>What its count depends on</th><th>Role</th></tr></thead><tbody>
            <tr><td>Token and position embeddings</td><td>Vocabulary × width; context × width</td><td>Map integer labels and positions into working vectors</td></tr>
            <tr><td>Six attention systems</td><td>Mostly width²</td><td>Route information among visible earlier positions</td></tr>
            <tr><td>Six feed-forward systems</td><td>Width × four-times expansion</td><td>Transform each position independently after attention</td></tr>
            <tr><td>Output projection</td><td>Width × vocabulary</td><td>Produce one next-token score per vocabulary entry</td></tr>
          </tbody></table>
        </>,
      },
      {
        id: 'random-state', title: 'Materialise reproducible random weights', body: <>
          <p><Term id="random-initialisation">Random initialisation</Term> fills the architecture&apos;s parameter arrays with pseudo-random starting values. Seed 42 makes that starting ticket repeatable on this software path. MLX lazily constructs arrays, so the script calls <code>mx.eval(model.parameters())</code> to ensure all weights actually exist on the selected device before they are counted or measured.</p>
          <p>The weights provide numeric transformations but contain no learned TinyStories regularities. Architecture defines possible computations; initial values specify one arbitrary starting point inside that architecture; training will later move those values using prediction error.</p>
        </>,
      },
      {
        id: 'validation', title: 'Grade every held-out target without changing the model', body: <>
          <p>A <Term id="forward-pass">forward pass</Term> sends input IDs through the current weights to produce logits. Cross-entropy compares those logits with the shifted next-token targets. The script walks every frozen validation window exactly once, uses the Lesson 4 loss mask to exclude padding, and divides the summed error by the number of real targets.</p>
          <p>The uniform-guess reference is <code>ln(2,048)</code>. Random initialisation need not equal it exactly because the initial logits need not be identical, but both establish the high-error region expected before learning. <Term id="perplexity">Perplexity</Term> is recorded for later same-tokenizer comparisons, not as an intuitive claim that the model literally considers a fixed shortlist.</p>
          <aside className="lesson-caveat"><strong>Forward speed is not training speed</strong><p>The measured throughput omits backward differentiation, gradient storage, optimiser work, and weight updates. It establishes inference feasibility, not the duration or memory of pretraining.</p></aside>
        </>,
      },
      {
        id: 'prompting', title: 'Inspect probabilities and continuations before learning', body: <>
          <p>Three frozen prompts use fixed sampling seeds, temperature 0.9, and a maximum of 64 new tokens. At each step the latest context enters the model, softmax converts its final-position logits to probabilities, categorical sampling draws one ID, and that ID is appended for the next step.</p>
          <p>The dashboard also exposes the five highest probabilities after the first prompt. Random output may contain recognisable fragments because the tokenizer already stores frequent pieces; joining those pieces does not mean the random weights learned grammar, plot, or meaning.</p>
        </>,
      },
      {
        id: 'checkpoint', title: 'Save checkpoint zero and prove it reloads', body: <>
          <p>A <Term id="checkpoint">checkpoint</Term> saves weight tensors, not the Python architecture or tokenizer. The script writes <code>checkpoint-0000.safetensors</code>, records its SHA-256 checksum and byte size, constructs a fresh matching model, and calls strict <code>load_weights</code>. A fixed slice of logits must match exactly or the experiment fails.</p>
          <p>MLX&apos;s <Source href="https://ml-explore.github.io/mlx/build/html/python/nn/module.html">Module documentation</Source> explains recursive parameters and its save/load interface; the dedicated <Source href="https://ml-explore.github.io/mlx/build/html/python/nn/_autosummary/mlx.nn.Module.save_weights.html">save_weights reference</Source> records that a <code>.safetensors</code> extension selects Safetensors serialization. Strict reload checks parameter names and shapes, while our logit comparison tests behaviour on a fixed input.</p>
        </>,
      },
      {
        id: 'command', title: 'Run the official before-state experiment', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_random_baseline.py`}</Code>
          <p>The command reads <code>public/data/local/tinystories-batching.json</code>, the selected <code>tokenizer.json</code>, and the frozen validation JSONL. It refuses mismatched tokenizer or data checksums, reconstructs Lesson 4 windows, materialises the selected GPT, warms one shape, then performs full validation, prompting, checkpoint save, and strict reload.</p>
          <p>It uses Python 3.12, MLX 0.32.0, and Tokenizers 0.23.1. It writes ignored <code>public/data/local/tinystories-random-baseline.json</code>, <code>work/experiments/tinystories-random-baseline-001/config.json</code>, and <code>checkpoint-0000.safetensors</code>. The checkpoint is learner-owned and is not committed or promoted automatically.</p>
        </>,
      },
      {
        id: 'evidence', title: 'Read checkpoint zero as a control, not a failed story model', body: <>
          <p>The live panel keeps architecture selection, complete held-out loss, forward-only memory, checkpoint integrity, top-token probabilities, and fixed-prompt output together. Switch to My Lab for learner evidence; Reference remains blank until a maintainer separately reviews and promotes a course run.</p>
          <TinyStoriesRandomBaselinePanel />
        </>,
      },
      {
        id: 'freeze-next', title: 'Freeze everything that Lesson 6 must inherit', body: <>
          <p>The development baseline now fixes dataset identity and hashes, tokenizer checksum, story-isolated batches, context 128, batch size 32, width 256, eight heads, six blocks, four-times feed-forward expansion, seed 42, evaluation windows, prompt text, sampling settings, and checkpoint zero.</p>
          <p>Lesson 6 may add only the training correction loop: masked cross-entropy, automatic differentiation, an optimiser, and a checkpoint schedule. Capturing one update and several early stages will let us see the transition from broad random probabilities toward spaces, common fragments, sentences, and eventually story patterns without hiding the awkward beginning.</p>
        </>,
      },
    ],
  },
  {
    slug: 'first-pretraining',
    title: 'Run the first TinyStories pretraining journey',
    summary: 'Load the exact checkpoint-zero control, add masked gradients and AdamW, traverse shuffled training windows, and preserve the model at seven stages so numerical and visible learning can be inspected together.',
    outcome: 'The learner-local run completes 500 optimiser updates from the frozen random baseline while recording full held-out evaluation and fixed-prompt generations at steps 0, 1, 10, 50, 100, 250, and 500.',
    evidence: 'Executable lesson · one controlled training recipe · seven staged checkpoints · learner-local evidence only',
    sections: [
      {
        id: 'meaning', title: 'What does “pretraining” mean in this small experiment?', body: <>
          <p><Term id="pretraining">Pretraining</Term> is the first broad phase in which a model learns next-token patterns from a corpus, before any later task-specific adaptation. Here “broad” means only the frozen TinyStories development slice: 1,000 synthetic training stories. It does not mean internet-scale knowledge, instruction following, or human-like understanding.</p>
          <p>Lesson 5 supplied an honest before-state: the complete 5.82M-parameter decoder could calculate probabilities, but its weights were random. Lesson 6 repeats the chain <strong>batch → prediction → error → gradient → weight update</strong> 500 times, then asks whether untouched validation stories became easier to predict.</p>
          <aside className="lesson-caveat"><strong>Training changes numbers, not the architecture</strong><p>The six blocks, eight heads, 128-token context, and 2,048-token vocabulary remain fixed. Only the values stored in the trainable weight arrays move.</p></aside>
        </>,
      },
      {
        id: 'inherit-control', title: 'Begin from the exact photographed control', body: <>
          <p>The script verifies the dataset hashes, tokenizer checksum, Lesson 4 batch contract, and SHA-256 of <code>checkpoint-0000.safetensors</code>. It reconstructs the same architecture and loads those weights strictly. The step-zero validation loss must therefore reproduce Lesson 5 before the first update.</p>
          <p>This is stronger than merely reusing seed 42. A seed asks a software path to generate random values again; loading the checked file restores the actual tensors we measured. Any later difference then follows from the learning loop rather than a subtly different initial ticket.</p>
        </>,
      },
      {
        id: 'data-order', title: 'Deal shuffled worksheets without silently dropping examples', body: <>
          <p>The 2,292 story-isolated training windows are shuffled with Python seed 42. The program takes up to 32 windows at a time, includes the smaller final batch, then reshuffles only after every window has been dealt once. This creates a reproducible <Term id="data-order">data order</Term> without repeatedly sampling some windows while missing others.</p>
          <p>The dashboard reports real target tokens seen and “equivalent complete training passes”: targets used for updates divided by the 229,867 legitimate training targets. It is a workload ratio, not a claim that every checkpoint lands exactly on an <Term id="epoch">epoch</Term> boundary.</p>
        </>,
      },
      {
        id: 'loss', title: 'Grade only genuine next-token questions', body: <>
          <p>For each batch, the model produces a 2,048-way logit vector at every one of the 128 positions. Cross-entropy calculates one error per position. The Lesson 4 <Term id="loss-mask">loss mask</Term> multiplies errors for right-hand padding by zero, then the script divides the remaining sum by the count of real targets.</p>
          <Code>{`per_position = cross_entropy(model(inputs), targets)
loss = sum(per_position * loss_mask) / sum(loss_mask)`}</Code>
          <p>Without the mask, short final chunks would reward the model for predicting artificial <code>&lt;pad&gt;</code> labels. The model could lower its score by learning our storage convenience rather than story text.</p>
        </>,
      },
      {
        id: 'gradients', title: 'Turn one error number into millions of local correction signals', body: <>
          <p>Loss says how wrong the batch was but not how each of 5,816,320 weights contributed. MLX <Term id="automatic-differentiation">automatic differentiation</Term> traces the forward calculations backward and produces a <Term id="gradient">gradient</Term> for every trainable array: a local slope showing how a tiny weight change would affect loss.</p>
          <p>Imagine a huge mixing desk after a poor recording. The loss is the single complaint “this sounds wrong”; gradients are millions of tiny arrows saying which direction each dial locally points uphill. They do not reveal the perfect final setting, so training takes a small step, listens again on another batch, and repeats. MLX documents this model-aware transformation in <Source href="https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.nn.value_and_grad.html">nn.value_and_grad</Source>.</p>
          <p>The run records the combined gradient L2 norm for diagnosis but does not clip it. That deliberate simplicity leaves clipping and schedules as controlled improvements rather than hidden ingredients.</p>
        </>,
      },
      {
        id: 'optimizer', title: 'Let AdamW translate slopes into cautious weight movements', body: <>
          <p>The <Term id="adamw">AdamW optimiser</Term> keeps running summaries of recent gradients and squared gradients for each weight. It uses those histories to scale the update, then applies decoupled weight decay. Our first recipe fixes learning rate <code>0.0003</code> and weight decay <code>0.01</code> for all 500 <Term id="training-step">training steps</Term>.</p>
          <p>The <Term id="learning-rate">learning rate</Term> is the master scale on the proposed movement. Too large can jump across useful regions; too small can make progress painfully slow. These values are a documented starting recipe, not an optimum. The <Source href="https://ml-explore.github.io/mlx/build/html/python/optimizers/_autosummary/mlx.optimizers.AdamW.html">MLX AdamW reference</Source> gives the exact update rule and defaults used by the implementation.</p>
          <Code>{`loss, gradients = value_and_grad(model, inputs, targets, loss_mask)
optimiser.update(model, gradients)
mx.eval(model.parameters(), optimiser.state)`}</Code>
        </>,
      },
      {
        id: 'checkpoints', title: 'Keep the awkward middle instead of showing only the finish', body: <>
          <p>The model is evaluated and invoked at steps 0, 1, 10, 50, 100, 250, and 500. Each evaluation walks all 442 validation windows and excludes padding exactly as Lesson 5 did. Each prompt uses the same text, sampling seed, temperature 0.9, and 64-token limit.</p>
          <p>A <Term id="checkpoint">checkpoint</Term> at each non-zero stage stores model weights and a checksum. Lesson 6 intentionally does not yet serialize optimiser momentum or the exact shuffle position, so these files support comparison and inference but are not fully resumable training snapshots. That missing machinery becomes Lesson 7.</p>
        </>,
      },
      {
        id: 'command', title: 'Run the learner-owned training experiment', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_first_pretraining.py`}</Code>
          <p>The command reads the frozen TinyStories JSONL files, selected tokenizer, Lesson 4 batching evidence, Lesson 5 baseline evidence, and checkpoint zero. It performs real GPU-backed forward calculations, backward differentiation, and AdamW updates.</p>
          <p>It writes ignored <code>public/data/local/tinystories-first-pretraining.json</code>, <code>work/experiments/tinystories-first-pretraining-001/config.json</code>, and staged <code>.safetensors</code> weight files. The JSON is atomically refreshed at every checkpoint, so an open My Lab page can update without reading a half-written file. Reference evidence remains untouched.</p>
        </>,
      },
      {
        id: 'evidence', title: 'Read numbers and completions as different kinds of evidence', body: <>
          <p>Complete validation loss aggregates tens of thousands of held-out next-token questions, so its direction is more trustworthy than one attractive sentence. Fixed-prompt completions answer a different question: what does one sampled path through the learned probabilities look like to a reader?</p>
          <p>A falling loss supports “the model predicts this held-out split better.” Cleaner spaces, words, and sentence fragments make that change visible. Neither alone establishes factuality, safety, coherent plots, or performance outside this small synthetic corpus.</p>
          <TinyStoriesPretrainingPanel />
        </>,
      },
      {
        id: 'limits-next', title: 'Name what this run still cannot do', body: <>
          <p>This is one seed, one recipe, 500 updates, and a deliberately small development corpus. Reusing those 1,000 stories for several equivalent passes can teach local style quickly and eventually overfit. Validation loss detects part of that risk, but the validation split has already influenced course decisions and is not a pristine final test.</p>
          <p>Lesson 7 will turn weight-only milestones into resumable checkpoints by saving optimiser state, update number, and data-order state, then strengthen live metrics around the same evidence boundaries. Only after reliable interruption and recovery should Lesson 8 compare learning-rate schedules, clipping, or longer budgets.</p>
        </>,
      },
    ],
  },
];

export function getTinyStoriesLesson(slug: string) {
  return tinyStoriesLessons.find(lesson => lesson.slug === slug);
}
