import type { BeginnerGuide } from './beginner-guidance';

const note = (why: string, mechanism: string, analogy: string, boundary?: string) => ({ why, mechanism, analogy, boundary });

export const tinyStoriesBeginnerGuidance: Record<string, BeginnerGuide> = {
  'transition-to-subwords': {
    background: 'Project 1 already established the repeating chain: text becomes token IDs; token IDs enter a model; the model emits next-token scores; training would compare those scores with known answers and update weights; inference instead samples from fixed weights. TinyStories preserves that chain but changes the size of the text pieces, the amount and origin of data, and eventually the size of the model.',
    picture: 'Shakespeare assembled text from single-letter and punctuation tiles. TinyStories introduces a box containing both small tiles and frequently useful larger pieces. A sentence can therefore fit on a shorter row, leaving room for more of the story inside the model’s fixed viewing area.',
    misconception: 'Changing to larger text pieces does not give the model vocabulary knowledge or grammar. The tokenizer only defines a reversible numbering system; useful prediction patterns still require weight updates during later training.',
    goal: 'Explain why the second project changes token scale, trace one story from source row to subword IDs and random logits, and distinguish a pipeline smoke test from pretraining.',
    notes: {
      departure: note('Character tokens are wonderfully transparent, but they consume many sequence positions. That limits how much of a story fits into one model calculation.', 'The tokenizer replaces common byte sequences with single IDs. The same context limit can then represent more visible text, while rare strings remain representable as smaller pieces.', 'Packing a suitcase with a mixture of folded garments and small loose items uses fewer slots than placing every thread in its own compartment.', 'Subword pieces are a storage and computation choice. They are not concepts in the model’s mind, and a longer visible passage does not guarantee that the model will use it well.'),
      question: note('A new project introduces several changes at once. Naming the exact learning question and what is not yet being tested prevents an early technical success from becoming an unsupported capability claim.', 'This lesson exercises every connection once with a bounded sample and random weights. Later lessons freeze data, tokenizer, batching and architecture separately before training begins.', 'A theatre performs a technical rehearsal to test lights, microphones and scene changes before judging the acting or the play.', 'A successful rehearsal proves the equipment connects; it does not prove the eventual performance will be good.'),
      source: note('Models reproduce statistical patterns from their supplied material, so authorship and generation process affect what can be learned and what claims are fair.', 'The TinyStories authors prompted larger language models to create simplified stories. We retain the source, split and recorded licence, then inspect the resulting text rather than treating “dataset” as a neutral box.', 'Before using a box of practice essays, a teacher asks who wrote them, under what instructions, and whether the same templates were reused.', 'Provenance reveals origin and constraints, not every hidden bias, error or duplicated idea in millions of generated stories.'),
      download: note('Downloading only convenient rows without recording which ones would make later comparisons impossible to reconstruct.', 'A fixed seed selects page offsets; each saved record keeps its original row number; the manifest records hashes. A hash changes when file bytes change, so it can detect a mismatch.', 'It is sampling numbered books from known library shelves and sealing an inventory with tamper-evident fingerprints.', 'A checksum detects changed bytes but cannot say whether the stories are correct, representative or ethically suitable.'),
      inspect: note('Training cost and evaluation credibility depend on story lengths, duplicates and split separation. These are data properties, not model settings.', 'The script counts stories, characters, simple whitespace-separated words, length percentiles and exact repeated texts separately for train and validation. The next audit will test subtler similarity across stories.', 'Before creating exam worksheets, count pages, find photocopies and ensure practice and exam piles are not the same stack.', 'Finding zero exact duplicates in 1,200 sampled stories does not prove the full dataset contains no duplicates or near-copies.'),
      tokenizer: note('The model needs a finite list of possible outputs. Whole words create an awkwardly huge list, while single characters create long sequences; BPE supplies a measurable compromise.', 'BPE begins with byte-level pieces and repeatedly joins frequent neighbours. The final file stores the vocabulary and merge rules so encoding and decoding follow the same procedure later.', 'A print shop starts with individual symbols, then creates reusable stamps for common combinations such as “ing” when repeated assembly wastes space.', 'The algorithm follows frequency, not grammar or meaning. A merged piece may look like a word or syllable without representing one linguistic idea.'),
      'random-model': note('Running before training creates the control condition needed to show that later structure came from updates rather than from the architecture or decoding software.', 'Seeded random numbers fill embedding, attention, feed-forward and output matrices. Token IDs flow through those matrices and produce one raw score for each vocabulary entry.', 'A newly wired sound mixing desk can pass a signal before its thousands of knobs have been adjusted for the concert.', 'The desk comparison explains adjustable state, but the model has no operator listening inside it and no intention behind its random scores.'),
      invoke: note('“The model ran” can mean either a forward calculation or a training update. This lesson isolates forward inference so the distinction is visible.', 'Eight sequences enter as integer arrays; the model returns a score grid; loss reads how poor the random scores were. During generation, one sampled ID is appended repeatedly. No backward calculation or stored weight changes occur.', 'A printer can produce a page from its current settings; measuring the bad print does not recalibrate it unless a separate correction step changes the controls.', 'Sampling adds pseudo-random variation to visible text, but it does not teach the model and should not be mistaken for creativity.'),
      'limits-next': note('A trustworthy experiment ends by separating what its evidence answers from attractive questions it has not tested.', 'We mark each pipeline connection as working, retain the random checkpoint, and leave dataset quality, tokenizer choice, architecture choice and learned story quality open for controlled lessons.', 'A pre-flight checklist can establish that engines, instruments and controls respond while still refusing to certify the entire journey complete.', 'Passing the checklist reduces known engineering risk; it neither guarantees safe data nor predicts final model quality.'),
    },
  },
  'dataset-audit': {
    background: 'A language model does not read a dataset as a human editor would. During training it receives token sequences and adjusts weights whenever doing so makes those supplied sequences easier to predict. If copied exam material, broken characters, or highly repeated templates enter that stream, the same correction machinery will learn from them without raising an objection. This lesson therefore examines the text and the train/validation boundary before either becomes a fixed input to later experiments.',
    picture: 'Imagine preparing a teaching workbook and a separate exam. First inventory every page, check for damaged printing, compare the exam against the workbook for copied passages, count overused worksheet templates, and then seal both piles with labelled bands. The seal does not certify that every lesson is wise; it makes later experiments use the same known material.',
    misconception: 'Finding zero exact or highly similar train/validation pairs does not prove that the stories are diverse, safe, unbiased, factual, or representative. It answers one leakage question at one declared threshold. Template repetition and content suitability require different evidence.',
    goal: 'Distinguish file integrity, split leakage, template repetition, content triage and dataset freezing; explain what each check detects, what it misses, and why no model weights change in this lesson.',
    notes: {
      'why-audit': note('Training converts repeated prediction errors into weight changes, so defects in the teaching material become part of the learning signal rather than an error message.', 'We inspect source identity, text structure, duplication and split separation before learning tokenizer merges or model weights. This keeps data failures from masquerading as modelling results.', 'A photocopier reproduces a stain on every source page perfectly; it cannot decide that the stain was not part of the lesson.', 'The audit tests declared failure patterns. It cannot discover every harmful idea, subtle bias or paraphrased copy.'),
      'freeze-inputs': note('Measurements are meaningful only if they refer to identifiable input bytes. Otherwise a changed download could inherit an old audit report.', 'The manifest records source rows and selection settings. SHA-256 compresses each complete file into a fingerprint; recomputing it detects even a one-byte change before analysis continues.', 'Record the serial numbers of two sealed exam boxes and compare their tamper-evident seals before accepting the examiner’s report.', 'Matching fingerprints prove byte identity, not truth, quality, legality or representativeness. Those are separate questions.'),
      command: note('The kind of program being run determines what can possibly have changed. Here we need an examiner, not a trainer.', 'The Python script reads JSON and tokenizer files, performs counting and comparisons, and writes a report. It never constructs a neural model, computes logits, gradients or optimiser updates, so there are no weights for it to teach.', 'A librarian can catalogue, compare and label books without rewriting any of their pages.', 'The script still creates evidence and configuration files; “read-only audit” describes its treatment of source data and model weights, not an absence of all output.'),
      integrity: note('Malformed rows can crash later code or quietly change token statistics, while unusually long stories can occupy many more training windows than typical ones.', 'Schema checks enforce expected fields and types. Character checks find replacement markers and hidden controls. Length thresholds create review flags, leaving any deletion for a separately recorded decision.', 'Inspect worksheets for blank pages, damaged symbols and unusually thick booklets before stacking them into equal classroom trays.', 'An outlier is a prompt to inspect, not proof of corruption. Automatically removing it would create a new dataset version.'),
      leakage: note('Validation is meant to act like unseen exam material. If near-copies of its stories appear in training, a model can appear to generalise by remembering familiar wording.', 'After exact and normalised matching, each story becomes a set of overlapping five-word strips. Jaccard similarity divides shared strips by all distinct strips in either story; all 200 validation stories are compared with all 1,000 training stories.', 'Cut each essay into overlapping five-word transparencies, then measure how much of two transparency piles is shared.', 'The 0.80 threshold detects heavy wording overlap, not meaning. A paraphrase can carry the same plot with few matching strips, while short formulaic phrases can match without making whole stories duplicates.'),
      templates: note('Leakage and narrow style are different. Unique stories can still repeatedly teach the same opening rhythm, making early fluency easier to imitate than long-range story consistency.', 'The audit counts the normalised first five words and selected recurring phrases independently of whole-story similarity. In the training sample, 610 of 1,000 stories start “once upon a time there.”', 'A thousand distinct forms may contain different answers while all beginning with the same printed heading and paragraph frame.', 'Template counts describe visible repetition; they do not measure every kind of plot, character, cultural or linguistic diversity.'),
      'content-screen': note('A dataset described as simple may still mention injury, fear or conflict. Locating likely examples helps a human decide what requires closer review.', 'Declared word lists act like an index: if a story contains one listed term, its category count rises. Context is not interpreted, so the result is a queue for inspection rather than a verdict.', 'A library search for books containing “fire” finds both dangerous-fire stories and fire-safety guides; a reader must still inspect them.', 'No hit means only that the listed words were absent. It does not mean the story is safe, appropriate or free of coded and contextual issues.'),
      'tokenizer-check': note('Later lessons rely on the tokenizer as the courier between text and IDs. We first confirm that it does not lose or replace content on either split.', 'Every story is encoded to IDs and decoded again. The decoded version is compared with the same declared Unicode normalisation, while unknown IDs and tokens per story are counted.', 'A courier translates every worksheet into numbered parcels and back; the returned worksheet should match the agreed printing standard.', 'Perfect round trips prove representability, not efficiency or learnability. A poor vocabulary can preserve every character while using wastefully long sequences.'),
      decision: note('Controlled comparisons require a stable input. If the stories change while vocabulary size or architecture changes, we cannot tell which cause produced the result.', 'The verified files, hashes and audit settings receive the name tinystories-development-v1. Later development lessons reuse that identity until an explicit, versioned scaling-data decision replaces it.', 'Seal and label one workbook/exam pair for laboratory trials, while keeping approval of the full school curriculum as a later decision.', 'The freeze is scoped to fast development experiments. This 1,200-story slice is not the final corpus and says little about the complete two-million-story distribution.'),
    },
  },
};
