import type { ReactNode } from 'react';
import BeginnerTerm from '@/app/components/BeginnerTerm';
import TinyStoriesTransitionPanel from '@/app/components/TinyStoriesTransitionPanel';
import type { RichLesson } from './shakespeare-lessons';

function Term({ id, children }: { id: string; children: ReactNode }) {
  return <BeginnerTerm id={id}>{children}</BeginnerTerm>;
}

function Source({ href, children }: { href: string; children: ReactNode }) {
  return <a className="inline-source" href={href} target="_blank" rel="noreferrer">{children} ↗</a>;
}

function Code({ children }: { children: string }) {
  return <pre className="lesson-code"><code>{children}</code></pre>;
}

export const tinyStoriesLessons: RichLesson[] = [
  {
    slug: 'transition-to-subwords',
    title: 'Move from characters to subwords',
    summary: 'Define the second project, inspect a bounded TinyStories sample, build a provisional byte-level BPE tokenizer, and invoke a 938,496-parameter GPT before any training update.',
    outcome: 'The recorded rerun completed the TinyStories input-to-output smoke test in 0.33 seconds: 1,200 stories were inspected, a 2,048-piece provisional vocabulary was built, and random weights produced the expected broken continuation.',
    evidence: 'Complete · tinystories-transition-001 · 0 optimiser updates · Apple GPU',
    sections: [
      {
        id: 'departure', title: 'What changes after Shakespeare?', body: <>
          <p>Shakespeare showed the entire language-model loop with one character per <Term id="token">token</Term>. That transparency came at a cost: <em>Once upon a time</em> occupied 16 character tokens, so a 64-token <Term id="context-window">context window</Term> could see only a short piece of prose.</p>
          <p>TinyStories asks a different question: can a still-small decoder-only transformer learn simple story structure when text is represented by reusable <Term id="subword-token">subword tokens</Term>? A subword may be punctuation, a complete frequent word, or part of a less frequent word. The provisional tokenizer represented <em>Once upon a time, there was</em> as seven pieces: <code>Once</code>, <code> upon</code>, <code> a</code>, <code> time</code>, <code>,</code>, <code> there</code>, and <code> was</code>.</p>
          <aside className="lesson-caveat"><strong>A transition, not a victory</strong><p>Shorter token sequences give the model more text per context window, but tokenisation alone does not create grammar or story understanding. Random weights remain random after the tokenizer is built.</p></aside>
        </>,
      },
      {
        id: 'question', title: 'Freeze the learning question and guardrails', body: <>
          <p>The project objective is to train a roughly 5–15 million parameter GPT-like model from random weights and test whether it can continue simple story prompts more coherently than our character-level Shakespeare model. Lesson 1 does not select that final size. It performs a <Term id="smoke-test">smoke test</Term>: one deliberately small run through download → inspect → tokenize → tensor → random model → logits → sampled text.</p>
          <table className="lesson-table"><tbody>
            <tr><th>Changed from Project 1</th><td>Corpus, token scale, vocabulary size, expected model scale and story-focused evaluation</td></tr>
            <tr><th>Preserved</th><td>Random baseline, held-out data, causal prediction, checkpoint evidence, controlled comparisons and local/reference separation</td></tr>
            <tr><th>Not happening yet</th><td>No optimiser, gradients, pretraining, architecture selection or claim of story quality</td></tr>
            <tr><th>Hardware boundary</th><td>32 GB Apple-silicon reference machine; later scale is chosen from measurements rather than the maximum allocation we can force</td></tr>
          </tbody></table>
        </>,
      },
      {
        id: 'source', title: 'Know what TinyStories actually is', body: <>
          <p>TinyStories is a <Term id="synthetic-dataset">synthetic dataset</Term>: its stories were generated by GPT-3.5 and GPT-4 rather than collected as naturally occurring children&apos;s writing. The authors designed it around vocabulary familiar to typical three- to four-year-olds so very small language models could be studied. Read the <Source href="https://arxiv.org/abs/2305.07759">TinyStories paper</Source> beside the <Source href="https://huggingface.co/datasets/roneneldan/TinyStories">hosted dataset card and files</Source>.</p>
          <p>The host records the dataset licence as <code>CDLA-Sharing-1.0</code>. The source currently exposes 2,119,719 training stories and 21,990 validation stories. The original repository is several gigabytes, so this first lesson intentionally downloads only a reproducible feasibility slice.</p>
          <aside className="lesson-caveat"><strong>Generated data changes the interpretation</strong><p>A model trained here can learn fluent-looking patterns, repeated templates, assumptions and mistakes inherited from the systems that generated the stories. “Vocabulary for young children” describes a design constraint; it does not prove developmental suitability, human authorship, factual accuracy or freedom from bias.</p></aside>
        </>,
      },
      {
        id: 'download', title: 'Download a bounded, traceable sample', body: <>
          <Code>{`uv run --no-sync python scripts/download_tinystories_sample.py`}</Code>
          <p>The script uses Python&apos;s standard HTTP and JSON libraries to request rows from the Hugging Face dataset service. Seed 42 selects ten non-overlapping 100-story pages from the official training split; seed 43 selects two pages from the official validation split. Every JSONL row retains its original <code>sourceRow</code>.</p>
          <p>It writes ignored files under <code>data/raw/tinystories-sample/</code>: <code>train.jsonl</code>, <code>validation.jsonl</code>, and a manifest containing source, recorded licence, retrieval time, selected offsets and SHA-256 checksums. The reference sample hashes are <code>7cc2…26c1</code> for training and <code>5be6…82b</code> for validation.</p>
          <p>This is <Term id="reproducibility">reproducibility</Term> evidence, not a guarantee that a mutable hosted dataset will never change. A later public release must either pin immutable source artifacts or publish a documented subset manifest that remains obtainable.</p>
        </>,
      },
      {
        id: 'inspect', title: 'Inspect before choosing the full course subset', body: <>
          <table className="lesson-table"><thead><tr><th>Split</th><th>Stories</th><th>Characters</th><th>Words</th><th>Median story</th><th>95th percentile</th><th>Exact duplicates within split</th></tr></thead><tbody>
            <tr><td>Training sample</td><td>1,000</td><td>839,030</td><td>163,489</td><td>765 characters</td><td>1,500</td><td>0</td></tr>
            <tr><td>Validation sample</td><td>200</td><td>157,955</td><td>30,494</td><td>773 characters</td><td>1,056</td><td>0</td></tr>
          </tbody></table>
          <p>The numbers answer a narrow feasibility question: this sample is easily large enough to build a tokenizer and fill fixed 128-token batches, while remaining quick to inspect. They do not constitute the full dataset audit. We have not yet measured near-duplicates, repeated templates, train/validation overlap, content categories, malformed stories or coverage of the source distribution.</p>
          <p>We preserve the dataset&apos;s own train and validation split instead of slicing one combined file. That prevents an obvious form of leakage, but the next lesson must test whether very similar generated stories cross the split boundary.</p>
        </>,
      },
      {
        id: 'tokenizer', title: 'Build a provisional byte-level BPE vocabulary', body: <>
          <p>We installed Hugging Face Tokenizers 0.23.1 and followed its documented <Source href="https://huggingface.co/docs/tokenizers/main/quicktour">from-scratch BPE workflow</Source>. <Term id="byte-pair-encoding">Byte Pair Encoding</Term> starts with small pieces, counts adjacent pairs, merges a frequent pair into a reusable larger piece, and repeats until it reaches the requested vocabulary size.</p>
          <p>Our <Term id="byte-level-tokenizer">byte-level tokenizer</Term> begins from byte representations, applies Unicode NFKC normalisation, and learns 2,048 vocabulary entries from only the 1,000 training stories. Four <Term id="special-token">special tokens</Term> reserve structural roles: <code>&lt;pad&gt;</code>, <code>&lt;unk&gt;</code>, <code>&lt;bos&gt;</code>, and <code>&lt;eos&gt;</code>. Validation stories do not teach merge rules.</p>
          <p>The resulting training sample contained 230,867 tokens—3.63 source characters per token on average. Validation averaged 3.55 characters per token. This is promising compression, but 2,048 is only a provisional choice. Lesson 3 will compare multiple vocabulary sizes for coverage, sequence length, model parameter cost and reversible decoding before freezing one.</p>
        </>,
      },
      {
        id: 'random-model', title: 'Construct a GPT with random weights', body: <>
          <p>The experiment reuses the readable decoder-only transformer components from Shakespeare but enlarges the vocabulary, width and context. <Term id="seed">Seed 42</Term> fills every <Term id="weight">weight</Term> with reproducible random values. MLX then materialises them on <code>Device(gpu, 0)</code>.</p>
          <table className="lesson-table"><thead><tr><th>Component</th><th>Configuration</th><th>Trainable values</th></tr></thead><tbody>
            <tr><td>Token embeddings</td><td>2,048 tokens × 128 features</td><td>262,144</td></tr>
            <tr><td>Position embeddings</td><td>128 positions × 128 features</td><td>16,384</td></tr>
            <tr><td>Two transformer blocks</td><td>4 attention heads; 4× feed-forward expansion</td><td>395,520</td></tr>
            <tr><td>Final normalisation and output</td><td>128 features → 2,048 next-token <Term id="logit">logits</Term></td><td>264,448</td></tr>
            <tr><td><strong>Total</strong></td><td>Provisional pipeline model</td><td><strong>938,496</strong></td></tr>
          </tbody></table>
          <p>This is intentionally below the eventual 5–15M target. Its job is to prove shapes, memory and decoding before architecture selection. The official random baseline will be frozen in Lesson 5 after the dataset, tokenizer and batching rules stop moving.</p>
        </>,
      },
      {
        id: 'invoke', title: 'Invoke the untrained model and read the evidence', body: <>
          <Code>{`uv run --no-sync python ml/tinystories_transition.py`}</Code>
          <p>The command loads the two JSONL files, trains the provisional tokenizer, constructs the random model, and forms a fixed <Term id="tensor">tensor</Term> of shape <code>8 × 128</code>. One forward pass produces logits of shape <code>8 × 128 × 2,048</code>. Cross-entropy <Term id="loss">loss</Term> compares those scores with the actual next tokens, but no gradient or optimiser follows.</p>
          <p>For prompted <Term id="inference">inference</Term>, the text <em>Once upon a time, there was</em> becomes seven IDs. The model calculates 2,048 random logits for the next position, temperature rescales them, sampling selects one token, and the process repeats. The saved <code>checkpoint-0000.safetensors</code> therefore records a genuine before-training state.</p>
          <TinyStoriesTransitionPanel />
        </>,
      },
      {
        id: 'limits-next', title: 'Say exactly what Lesson 1 established', body: <>
          <p>We established that the source is reachable, the bounded files are traceable, the tokenizer can encode and decode the material, the intended transformer family fits comfortably, tensor shapes connect, random loss is finite, checkpoint saving works, and generated IDs return to visible text. That removes many plumbing risks before an expensive run.</p>
          <p>We did <strong>not</strong> establish that the dataset is clean, the vocabulary is optimal, 938,496 parameters are sufficient, the fixed-batch loss is a stable estimate, or the model can tell stories. Its broken continuation is evidence that architecture plus tokenizer is not learning.</p>
          <p>Lesson 2 now audits the dataset and freezes the bounded course subset. Only after that will we compare tokenizers, construct causal batches, and define the official random GPT baseline.</p>
        </>,
      },
    ],
  },
];

export function getTinyStoriesLesson(slug: string) {
  return tinyStoriesLessons.find(lesson => lesson.slug === slug);
}
