export type Project = {
  slug: string;
  number: string;
  name: string;
  shortName: string;
  description: string;
  stage: string;
  progress: number;
  status: string;
  method: string;
  objective: string;
  dataset: { name: string; detail: string; source: string; sourceLabel: string };
  stages: { slug: string; name: string; state: 'complete' | 'active' | 'planned'; lesson: string }[];
  concepts: { term: string; explanation: string }[];
  furtherReading: { label: string; href: string }[];
};

export const projects: Project[] = [
  {
    slug: 'shakespeare', number: '01', name: 'Tiny Shakespeare', shortName: 'Shakespeare',
    description: 'Build a character-level language model from random weights and watch structure emerge.',
    stage: 'Complete', progress: 100, status: 'COMPLETE', method: 'Train from scratch',
    objective: 'Understand the complete language-model loop with the smallest model that still produces visible learning: data → tokens → predictions → loss → updated weights → generated text.',
    dataset: { name: 'Tiny Shakespeare', detail: 'Approximately 1 MB of dialogue from Shakespeare plays. We use a fixed 90/10 train/validation split and begin with individual characters as tokens.', source: 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt', sourceLabel: 'Karpathy char-rnn dataset' },
    stages: [
      { slug: 'lab-setup', name: 'Lab and wiki setup', state: 'complete', lesson: 'Create a reproducible project, record the hardware, and make results visible.' },
      { slug: 'data-and-tokenisation', name: 'Data and tokenisation', state: 'complete', lesson: 'Download the corpus, build a 65-character vocabulary, encode it, and freeze the 90/10 split.' },
      { slug: 'random-baseline', name: 'Random baseline', state: 'complete', lesson: 'Create and invoke a 4,225-weight model before learning so every improvement has a meaningful comparison.' },
      { slug: 'bigram-training', name: 'Bigram training', state: 'complete', lesson: 'Use loss, gradients and AdamW to learn which character tends to follow another character.' },
      { slug: 'context-windows', name: 'Context windows', state: 'complete', lesson: 'Let the model use several earlier characters instead of only one.' },
      { slug: 'self-attention', name: 'Self-attention', state: 'complete', lesson: 'Allow each position to selectively combine information from its context.' },
      { slug: 'tiny-transformer', name: 'Tiny transformer', state: 'complete', lesson: 'Assemble embeddings, multi-head attention, feed-forward layers, residual paths and normalisation.' },
      { slug: 'evaluation', name: 'Evaluation', state: 'complete', lesson: 'Freeze a repeatable protocol and compare every checkpoint using held-out loss, perplexity, generalisation gap and fixed prompts.' },
      { slug: 'prompt-playground', name: 'Prompt playground', state: 'complete', lesson: 'Load saved checkpoints behind a local inference service and complete learner-written Shakespearean prompts in the wiki.' },
      { slug: 'training-improvements', name: 'Training improvements', state: 'complete', lesson: 'Hold the model fixed while testing warmup plus cosine decay and gradient clipping as controlled changes.' },
      { slug: 'scaling-experiment', name: 'Scaling and longer context', state: 'complete', lesson: 'Compare wider, deeper and longer-context models while measuring quality, memory and speed.' },
      { slug: 'final-evaluation', name: 'Final model and comparison', state: 'complete', lesson: 'Confirm the selected architecture across three training seeds and close the project with an honest comparison.' },
    ],
    concepts: [
      { term: 'Token', explanation: 'A unit represented by an integer. In this first project every distinct character—including spaces and line breaks—is a token.' },
      { term: 'Weight', explanation: 'A learned number inside the model. Random initial weights know nothing; training adjusts them to reduce prediction error.' },
      { term: 'Logit', explanation: 'An unnormalised score the model assigns to each possible next token.' },
      { term: 'Loss', explanation: 'A single number measuring prediction error. Lower validation loss generally indicates better next-token predictions on unseen text.' },
    ],
    furtherReading: [
      { label: 'MLX framework', href: 'https://github.com/ml-explore/mlx' },
      { label: 'Neural Networks: Zero to Hero', href: 'https://karpathy.ai/zero-to-hero.html' },
      { label: 'Tiny Shakespeare preparation', href: 'https://github.com/karpathy/llm.c/blob/master/dev/data/tinyshakespeare.py' },
    ],
  },
  {
    slug: 'tinystories', number: '02', name: 'TinyStories', shortName: 'TinyStories',
    description: 'Scale the same ideas into a small GPT that learns simple, coherent English stories.',
    stage: 'Lesson 9 of 12 complete', progress: 75, status: 'ACTIVE', method: 'Train from scratch',
    objective: 'Move from character imitation to subword language modelling and train a roughly 5–15M parameter transformer on a deliberately simple language distribution.',
    dataset: { name: 'TinyStories', detail: 'Synthetic short stories written with vocabulary familiar to young children. We will begin with a bounded subset before choosing whether to scale.', source: 'https://www.microsoft.com/en-us/research/publication/tinystories-how-small-can-language-models-be-and-still-speak-coherent-english/', sourceLabel: 'Microsoft Research' },
    stages: [
      { slug: 'transition-to-subwords', name: 'From characters to subwords', state: 'complete', lesson: 'Define the new question, inspect a bounded sample, build a provisional tokenizer, and invoke a random GPT without training it.' },
      { slug: 'dataset-audit', name: 'Dataset audit and split freeze', state: 'complete', lesson: 'Audit provenance, licence, generated-data limitations, lengths, duplicates and leakage before freezing the course subset.' },
      { slug: 'tokenizer-experiment', name: 'Tokenizer experiment', state: 'complete', lesson: 'Compare vocabulary sizes and freeze a subword tokenizer using compression, coverage and reversibility evidence.' },
      { slug: 'sequence-batching', name: 'Sequence batching', state: 'complete', lesson: 'Turn separate stories into causal token windows while handling boundaries, padding and masks honestly.' },
      { slug: 'random-gpt-baseline', name: 'Random GPT baseline', state: 'complete', lesson: 'Freeze the first training architecture and record loss, memory and prompted output before any optimiser update.' },
      { slug: 'first-pretraining', name: 'First pretraining run', state: 'complete', lesson: 'Run next-token training from scratch and expose the first transition from random fragments toward simple sentences.' },
      { slug: 'checkpoints-dashboard', name: 'Checkpoints and live metrics', state: 'complete', lesson: 'Save comparable training states and make token loss, throughput, memory and fixed-prompt samples visible in the wiki.' },
      { slug: 'training-recipe', name: 'Improve the training recipe', state: 'complete', lesson: 'Branch one complete state into matched learning-rate policies and select with a predeclared validation threshold.' },
      { slug: 'scaling-budget', name: 'Scale within the laptop budget', state: 'complete', lesson: 'Benchmark width, depth, context and dataset size before selecting a longer run that fits the MacBook Air.' },
      { slug: 'story-evaluation', name: 'Evaluate story behaviour', state: 'active', lesson: 'Combine frozen held-out loss with prompt adherence, consistency, repetition, diversity and overlap checks.' },
      { slug: 'tinystories-playground', name: 'TinyStories prompt playground', state: 'planned', lesson: 'Complete learner-written story openings with selected local checkpoints under controlled generation settings.' },
      { slug: 'final-story-model', name: 'Final model and comparison', state: 'planned', lesson: 'Confirm the selected model across seeds and compare character-level Shakespeare with subword TinyStories honestly.' },
    ],
    concepts: [
      { term: 'Subword token', explanation: 'A reusable piece of a word, allowing a finite vocabulary to represent unfamiliar words efficiently.' },
      { term: 'Parameter count', explanation: 'The total number of trainable weights; a useful size measure, but not a quality measure by itself.' },
      { term: 'Pretraining', explanation: 'Learning general statistical patterns from a broad text corpus through next-token prediction.' },
    ],
    furtherReading: [
      { label: 'TinyStories paper and overview', href: 'https://www.microsoft.com/en-us/research/publication/tinystories-how-small-can-language-models-be-and-still-speak-coherent-english/' },
      { label: 'TinyStories paper on arXiv', href: 'https://arxiv.org/abs/2305.07759' },
    ],
  },
  {
    slug: 'sql', number: '03', name: 'English → SQL', shortName: 'English → SQL',
    description: 'Fine-tune a pretrained small model and evaluate answers by executing generated SQL.',
    stage: 'Planned', progress: 0, status: 'LATER', method: 'LoRA fine-tuning',
    objective: 'Contrast pretraining with adaptation: keep most pretrained weights fixed, train small adapter matrices, then evaluate generated queries by execution.',
    dataset: { name: 'WikiSQL', detail: 'Natural-language questions paired with table schemas and executable SQL structures. Execution provides a concrete evaluation signal.', source: 'https://github.com/salesforce/WikiSQL', sourceLabel: 'Official Salesforce WikiSQL repository' },
    stages: [
      { slug: 'task-and-dataset-audit', name: 'Task and dataset audit', state: 'planned', lesson: 'Define what counts as correct and inspect known limitations of the benchmark.' },
      { slug: 'base-model-selection', name: 'Base-model selection', state: 'planned', lesson: 'Measure candidate models for memory use, licence, context format and baseline accuracy.' },
      { slug: 'prompt-formatting', name: 'Prompt formatting', state: 'planned', lesson: 'Represent the question and schema consistently without leaking answers.' },
      { slug: 'lora-fine-tuning', name: 'LoRA fine-tuning', state: 'planned', lesson: 'Train a small number of adapter parameters while preserving base weights.' },
      { slug: 'execution-evaluation', name: 'Execution evaluation', state: 'planned', lesson: 'Execute queries in a sandbox and compare returned answers, not just SQL strings.' },
    ],
    concepts: [
      { term: 'Fine-tuning', explanation: 'Continuing training from pretrained weights on a narrower task or style.' },
      { term: 'LoRA', explanation: 'Low-Rank Adaptation: small trainable matrices modify selected layers while the original model weights stay frozen.' },
      { term: 'Execution accuracy', explanation: 'The percentage of generated queries that return the correct result when executed.' },
    ],
    furtherReading: [
      { label: 'WikiSQL repository', href: 'https://github.com/salesforce/WikiSQL' },
      { label: 'MLX-LM fine-tuning', href: 'https://github.com/ml-explore/mlx-lm' },
      { label: 'LoRA paper', href: 'https://arxiv.org/abs/2106.09685' },
    ],
  },
];

export const glossary = [
  ['API', 'Application Programming Interface: a defined way for one program to request work or data from another. The prompt UI sends JSON to the local Python inference API.'],
  ['AdamW', 'An optimiser that adapts each parameter’s update size and can apply decoupled weight decay. Our bigram baseline uses AdamW with weight decay disabled.'],
  ['Attention head', 'One independently learned query, key and value relationship space inside multi-head attention. Different heads can learn to retrieve different kinds of information.'],
  ['Autoregressive', 'Generating or predicting one token at a time while conditioning on earlier tokens.'],
  ['Automatic differentiation', 'Software tracing of numerical operations so gradients of a loss can be calculated automatically.'],
  ['Atomic write', 'A persistence pattern that replaces a completed temporary result as one filesystem action, or writes a final completion marker last, so readers can detect and reject partial state.'],
  ['Attention score', 'A query–key compatibility value that determines how strongly one position reads information from another position.'],
  ['Backpropagation', 'Computing how much each weight contributed to the loss so the optimiser can update it.'],
  ['Baseline', 'A measured starting condition used for later comparison. An untrained random checkpoint separates changes caused by training from those caused by architecture or data plumbing.'],
  ['Batch', 'Several examples processed together in one model calculation. During training, one batch commonly supplies one optimiser update; evaluation batches do not update weights.'],
  ['Capacity', 'The amount and complexity of patterns a model can represent, influenced by parameter count, width, depth and architecture.'],
  ['Bigram model', 'A model of pairs. Our character bigram predicts the next character using only the current character.'],
  ['Byte Pair Encoding', 'A subword-tokenisation method that repeatedly merges frequent adjacent pieces to build a reusable vocabulary. It is commonly abbreviated BPE.'],
  ['Byte-level tokenizer', 'A tokenizer whose guaranteed starting alphabet is the 256 possible byte values, allowing any encoded text to be represented before frequent byte sequences are merged.'],
  ['Character-level tokenizer', 'A transparent tokenizer in which every distinct character—including punctuation, spaces and line breaks—is its own token.'],
  ['Cherry-picking', 'Selecting unusually attractive examples after seeing many outputs while hiding the broader or less successful results. Fixed prompts, seeds and aggregate metrics reduce this risk.'],
  ['Causal mask', 'A mask that prevents a next-token model from attending to positions in the future.'],
  ['Checkpoint', 'A saved snapshot of model weights. A resumable training checkpoint must also preserve optimiser, step, and data-order state; a weight-only checkpoint supports inspection and inference but not exact continuation.'],
  ['Controlled experiment', 'A comparison that changes one chosen variable while keeping other relevant conditions fixed, making causal interpretation more defensible.'],
  ['Compression ratio', 'A ratio describing how much source text each token represents. This course uses characters per token, where a larger value means a shorter token sequence for the same text.'],
  ['Compute budget', 'A declared allowance of training updates, time, memory or other resources used to bound an experiment and compare what each candidate achieves for that cost.'],
  ['Context window', 'The maximum number of earlier tokens visible when predicting the next token.'],
  ['Cross-entropy', 'A loss that penalises low probability assigned to the correct class or next token.'],
  ['Data leakage', 'Information from evaluation examples entering training or model-selection inputs, making held-out results look better than genuine performance on new data.'],
  ['Data manifest', 'A machine-readable inventory recording where data came from, how it was selected, and identifying details such as row numbers and file hashes.'],
  ['Data order', 'The sequence in which training examples reach the model. Shuffling changes which examples share an update and can change the path learned weights take.'],
  ['Cosine decay', 'A learning-rate schedule that smoothly reduces the rate along part of a cosine curve, allowing smaller parameter updates late in training.'],
  ['Decoder-only transformer', 'A causal transformer that predicts future tokens from earlier tokens without a separate encoder. GPT-style language models use this arrangement.'],
  ['Embedding', 'A trainable lookup table that maps a token ID to a vector of numbers. In the bigram model each vector directly contains next-token scores.'],
  ['Epoch', 'One complete pass through the training dataset. Token-based LLM runs are often tracked by steps instead.'],
  ['Evaluation protocol', 'A procedure fixed before comparing models: the same data, sampling method, metrics, prompts and random seeds are applied to every candidate.'],
  ['Feed-forward network', 'Dense transformations applied independently to representations, usually with a nonlinear activation between layers.'],
  ['Forward pass', 'Sending inputs through the model’s current weights to calculate activations and outputs. A forward pass alone does not update those weights.'],
  ['GELU', 'Gaussian Error Linear Unit, a smooth nonlinear activation commonly used in transformer feed-forward layers.'],
  ['Gradient', 'The direction and magnitude in which changing a weight would change the loss.'],
  ['Gradient clipping', 'Rescaling gradients when their combined norm exceeds a threshold, limiting unusually large optimiser updates.'],
  ['Gradient norm', 'A single magnitude calculated from all gradients; it summarises the overall size of the proposed parameter update direction.'],
  ['Generalisation gap', 'The difference between validation loss and training loss. A growing positive gap can indicate that a model fits training data better than unseen data.'],
  ['Hot module reload', 'A development feature that applies source changes to an open page without restarting the whole application.'],
  ['Hidden layer', 'An internal neural-network layer whose values are neither the raw input nor the final output.'],
  ['Inference', 'Using trained weights to make predictions or generate output without updating them.'],
  ['Inference service', 'A long-running program that loads model weights and accepts generation requests, allowing a user interface to invoke a model without implementing tensor operations itself.'],
  ['Jaccard similarity', 'A set-overlap score: the number of items shared by two sets divided by the number of distinct items present across either set.'],
  ['Learning rate', 'The scale of each optimiser update; too high can destabilise training and too low can make it impractically slow.'],
  ['Learning-rate schedule', 'A rule that changes the learning rate over training instead of keeping it constant.'],
  ['Layer normalisation', 'Normalisation of features within each token representation, with learned scale and bias.'],
  ['Logit', 'An unnormalised score assigned to one possible output before scores are converted into probabilities.'],
  ['Loss', 'A numerical measure of prediction error. Training uses gradients of loss to update weights; evaluation uses loss without changing the model.'],
  ['Loss mask', 'A one-or-zero weight beside each target that determines whether its per-position loss contributes to the batch result. It excludes padding; it does not control attention visibility.'],
  ['Model depth', 'The number of sequential blocks or layers in a neural network. More depth adds processing stages as well as parameters and computation.'],
  ['Model architecture', 'The fixed arrangement of layers and mathematical connections that determines how inputs can be transformed. Training changes weights inside that arrangement, not the arrangement itself.'],
  ['Model width', 'The number of features used to represent each token inside the model. Wider representations increase both capacity and computation; course architectures use different widths.'],
  ['Multi-head attention', 'Several attention heads run in parallel on different learned subspaces; their outputs are concatenated and projected back to the model width.'],
  ['Near duplicate', 'A pair of examples that are not byte-for-byte identical but share enough wording or structure to risk counting essentially the same material twice.'],
  ['Normalisation', 'A declared transformation that puts equivalent-looking text into a consistent form, such as standardising Unicode representation, letter case, or whitespace.'],
  ['Numerical tolerance', 'A declared maximum difference accepted when floating-point execution is not bitwise identical. The observed difference must still be reported and discrete state must be checked separately.'],
  ['Optimiser state', 'The numerical history an optimiser carries between updates, such as AdamW’s step and moving averages. It affects future training but is not used for ordinary inference.'],
  ['Overfitting', 'Improving on training examples while getting worse or failing to improve on unseen validation data.'],
  ['Padding', 'Structural filler tokens added so variable-length examples fit equal-shaped tensors. Padded target positions must be excluded from loss.'],
  ['Parameter efficiency', 'The quality improvement achieved relative to additional parameters, memory, or computation.'],
  ['Parameter count', 'The total number of trainable numerical values in a model. It measures size, not learned quality or understanding.'],
  ['Perplexity', 'An exponential transformation of average cross-entropy loss; lower means the correct next tokens are less surprising to the model.'],
  ['Pretraining', 'The initial phase of learning broad next-token patterns from a corpus before narrower task adaptation. “Broad” is relative to the supplied corpus and does not imply universal knowledge.'],
  ['Positional embedding', 'A learned vector associated with a sequence position and combined with token information to represent order.'],
  ['Prompt', 'The input text supplied to a generative model as the context from which it should continue.'],
  ['Pre-layer-normalisation', 'A transformer arrangement that normalises a representation before each attention or feed-forward sublayer, then adds the sublayer output through a residual connection.'],
  ['Query vector', 'In attention, the learned representation of what the current position is looking for.'],
  ['Random initialisation', 'Creating a model’s starting weights from a pseudo-random numerical distribution before any training update. A seed can make the starting draw reproducible on a given software path.'],
  ['Random-number generator state', 'The internal state of a pseudo-random sequence after earlier draws. Saving it continues from the next draw; reusing only the seed restarts the sequence.'],
  ['Reproducibility', 'The ability to recreate an experiment from recorded code, data provenance, dependency versions, configuration and random seeds.'],
  ['Round-trip test', 'Encoding source text into token IDs and decoding those IDs again to verify that the declared text representation can be recovered.'],
  ['Residual connection', 'A path that adds a sublayer’s input to its output, helping preserve information and gradient flow.'],
  ['Resumable checkpoint', 'A checkpoint containing model weights plus optimiser, step, random, and data-order state needed to continue training after the program stops.'],
  ['Safetensors', 'A format for storing tensor weights without executable pickle payloads.'],
  ['Seed', 'A number used to make pseudo-random initialisation and sampling reproducible.'],
  ['Sequence packing', 'Arranging one or more variable-length sequences inside fixed-size tensors to reduce unused padding, while preserving explicit boundaries in attention and loss.'],
  ['Shifted targets', 'The known next-token answers formed by moving a token sequence one position relative to its inputs: each input position is paired with the token immediately after it.'],
  ['Smoke test', 'A small end-to-end run whose job is to prove that the pipeline connects correctly, not to establish final quality or performance.'],
  ['Special token', 'A reserved token used to mark structural events such as the beginning or end of a story, padding, or unknown input rather than ordinary visible prose.'],
  ['Subword token', 'A reusable text fragment that may be a character, punctuation mark, complete word, or word piece. Subwords balance sequence length against vocabulary size.'],
  ['Synthetic dataset', 'A dataset created by a generative process rather than directly collected as naturally occurring human-authored records. Its patterns and defects reflect that generating process.'],
  ['Self-attention', 'A mechanism that lets each position form a content-dependent weighted combination of information from positions in its context.'],
  ['Softmax', 'A transformation that turns a vector of scores into non-negative probabilities that sum to one.'],
  ['Temperature', 'A generation setting that rescales logits before sampling; lower values concentrate probability on high-scoring tokens.'],
  ['Tensor', 'A multidimensional array used to store token batches, activations, weights and gradients.'],
  ['Token', 'A discrete unit of text mapped to an integer before it enters a model.'],
  ['Training step', 'One batch loss calculation followed by one optimiser update.'],
  ['Training-seed variance', 'Differences between independently trained models caused by random initialisation, batch sampling and other seeded numerical choices.'],
  ['Unified memory', 'Apple-silicon memory shared by CPU and GPU rather than split into separate system RAM and video RAM pools.'],
  ['Validation set', 'Held-out examples used to measure generalisation during development but never used for weight updates.'],
  ['Value vector', 'In attention, the information from a position that is blended according to its attention weight.'],
  ['Virtual environment', 'A project-specific Python environment that isolates interpreter packages from other projects and the system installation.'],
  ['Vocabulary', 'The complete set of tokens a model can represent, plus the mapping between those tokens and integer IDs.'],
  ['Vocabulary-dependent parameters', 'Model weights whose count grows directly with vocabulary size, especially the token-embedding table and next-token output projection.'],
  ['Weight', 'A trainable numerical parameter that transforms information inside a neural network.'],
  ['Warmup', 'A short opening phase in which the learning rate rises gradually toward its main value, reducing the size of the earliest updates.'],
  ['Key vector', 'In attention, the learned representation that a query compares with to decide relevance.'],
] as const;

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
