import Link from '@/app/components/CourseLink';
import WikiChrome from '@/app/components/WikiChrome';
import { LearningVisual } from '@/app/components/LearningVisual';

const sentimentStages = [
  ['01', 'Frame classification', 'Define positive/negative prediction, class balance, accuracy, F1, calibration, and an untouched test set.'],
  ['02', 'Audit IMDb reviews', 'Download the 50,000 labelled reviews, verify provenance and terms, inspect length, duplicates, labels, and split integrity.'],
  ['03', 'Build simple baselines', 'Compare majority-class and bag-of-words logistic-regression baselines before using a transformer.'],
  ['04', 'Measure zero-shot behaviour', 'Prompt a small pretrained model without updates and record accuracy, invalid outputs, latency, and memory.'],
  ['05', 'Fine-tune efficiently', 'Use LoRA or a classification head, save random and trained adapter checkpoints, and monitor train/validation curves.'],
  ['06', 'Evaluate beyond accuracy', 'Add confusion matrices, F1, confidence calibration, review-length slices, and fixed qualitative errors.'],
  ['07', 'Explain and challenge', 'Test negation, sarcasm, mixed reviews, shortcut words, and whether generated explanations agree with predictions.'],
  ['08', 'Package the result', 'Add a local review box, model card, reproducible configuration, limitations, and reference-versus-local evidence.'],
];

export default function ContinueLearning() {
  return <WikiChrome active="continue"><article className="article-page">
    <div className="breadcrumbs"><Link href="/">Dashboard</Link><span>/</span><strong>Continue independently</strong></div>
    <header className="article-hero single"><div><p className="kicker">PROJECTS 04–06 · GRADUALLY REMOVE THE SCAFFOLD</p><h1>Make the learning path yours</h1><p>These three extensions deliberately provide decreasing structure. The first gives you a complete lesson spine, the second gives your coding agent a design brief, and the third leaves you with themes and questions.</p></div></header>
    <LearningVisual title="Scaffolding decreases as your experimental judgement grows" description="The evidence standard stays fixed even while the course supplies fewer design decisions." kind="compare" steps={[
      { label: 'Full lesson spine', detail: 'Sentiment: follow and then question the structure', tone: 'input' },
      { label: 'Scientific brief', detail: 'Summarisation: design lessons within guardrails', tone: 'process' },
      { label: 'Open theme', detail: 'Choose the question, data, baseline, and measures', tone: 'warning' },
      { label: 'Independent evidence', detail: 'Defend the claim and its limitations', tone: 'evidence' },
    ]} />

    <section className="lesson-section"><div className="lesson-title"><span>04</span><div><p className="kicker">FULL SCAFFOLD · SUPERVISED CLASSIFICATION</p><h2>Movie-review sentiment laboratory</h2><p className="section-intro">Learn how a language model becomes a classifier and why evaluation needs more than one accuracy number.</p></div></div><div className="two-column"><div><h3>The task</h3><p>Use Stanford’s <a className="inline-source" href="https://nlp.stanford.edu/~amaas/data/sentiment/" target="_blank" rel="noreferrer">Large Movie Review Dataset</a>: 25,000 labelled training reviews and 25,000 labelled test reviews. Compare a simple non-neural baseline, zero-shot prompting, and parameter-efficient adaptation of a small pretrained model.</p></div><aside className="callout"><strong>New ideas introduced</strong><p>Classification heads, precision/recall/F1, calibration, confusion matrices, dataset shortcuts, robustness slices, and model cards.</p></aside></div><div className="stage-list independent-stage-list">{sentimentStages.map(stage => <article className="stage-row" key={stage[0]}><span className="stage-index">{stage[0]}</span><div><h3>{stage[1]}</h3><p>{stage[2]}</p></div><span className="stage-action"><strong>scaffolded</strong></span></article>)}</div></section>

    <section className="lesson-section"><div className="lesson-title"><span>05</span><div><p className="kicker">AGENT BRIEF · SEQUENCE-TO-SEQUENCE</p><h2>Dialogue summarisation with SAMSum</h2><p className="section-intro">You decide the lesson structure; the brief supplies the scientific constraints your agent must preserve.</p></div></div><div className="experiment-note"><div><h2>Brief for your coding agent</h2><p>Scaffold a local project that adapts a small pretrained model to summarise messenger-style dialogue using the <a className="inline-source" href="https://aclanthology.org/D19-5409/" target="_blank" rel="noreferrer">SAMSum corpus and paper</a>. Begin with extractive and no-training baselines. Audit licence, dialogue length, speakers, summary length, duplicates, and split leakage. Freeze prompts and evaluation before fine-tuning.</p><p>Compare a quantised base model with LoRA adaptation. Record memory, time, train/validation loss, ROUGE, factual consistency checks, speaker/entity errors, omissions, and several fixed conversations. Require a manual error taxonomy because the SAMSum paper warns that automatic scores and human judgement can disagree.</p></div><dl><div><dt>Agent must create</dt><dd>lesson plan + evidence schema</dd></div><div><dt>Must compare</dt><dd>extractive · zero-shot · adapted</dd></div><div><dt>Primary risk</dt><dd>invented facts</dd></div><div><dt>Your decision</dt><dd>model, subset, rubric</dd></div></dl></div></section>

    <section className="lesson-section"><div className="lesson-title"><span>06</span><div><p className="kicker">OPEN EXPLORATION · CHOOSE YOUR QUESTION</p><h2>A theme rather than a recipe</h2><p className="section-intro">Pick something you care about, then design the dataset, task, baseline, evidence, and ethical boundary yourself.</p></div></div><div className="tool-detail-grid"><article><h3>Language and place</h3><p>Explore dialect, endangered-language text, local history, place names, or bilingual generation. Ask who created the data, who may be excluded, and what “quality” means to that community.</p></article><article><h3>Useful transformations</h3><p>Try extraction, tagging, rewriting, tutoring, search, retrieval, question answering, or structured output. Prefer a task whose result can be checked rather than merely admired.</p></article><article><h3>Creative systems</h3><p>Investigate recipes, music notation, tabletop worlds, poetry, game dialogue, or procedural stories. Separate originality, imitation, memorisation, coherence, and personal taste.</p></article><article><h3>Research questions</h3><p>How little data is enough? Which examples matter? When does more context help? Can a smaller model plus retrieval beat a larger model? Which metric hides the failures you care about?</p></article></div><aside className="principle-card"><p className="kicker">YOUR ONLY REQUIRED STRUCTURE</p><h2>Question → baseline → controlled change → evidence → limitation.</h2><p>If your agent cannot state those five things before training, keep designing the experiment.</p></aside></section>
  </article></WikiChrome>;
}
