import Link from '@/app/components/CourseLink';
import WikiChrome from '@/app/components/WikiChrome';
import { BeginnerOnly } from '@/app/components/BeginnerMode';
import { LearningVisual } from '@/app/components/LearningVisual';

const steps = [
  { number: '1', title: 'Define the question', standard: 'State what the model should learn and how we will tell whether it learned it.', why: 'Without a promised measurement, “make it better” invites us to favour whatever output happens to look impressive afterward.', explain: 'Name the input, desired output, comparison baseline, metric, and important constraint before changing code.', picture: 'Mark the finish line and timing method before runners start.' },
  { number: '2', title: 'Audit and split data', standard: 'Inspect provenance and quality, then freeze train, validation and test sets before tuning decisions.', why: 'A model learns the regularities and defects of its examples, while honest evaluation needs examples excluded from weight updates.', explain: 'Inspect where data came from and what it contains, then assign fixed portions to practice, development checks, and—when possible—a final untouched test.', picture: 'Review the textbook, then lock exam pages in separate envelopes.' },
  { number: '3', title: 'Tokenise', standard: 'Map text to integer IDs. Token choice determines vocabulary size and sequence length.', why: 'Neural-network operations require numbers, but the way text is divided determines both the prediction task and its computational cost.', explain: 'Choose repeatable text pieces, build their ID mapping, encode text to IDs, and verify that decoding returns the original text.', picture: 'Choose the pieces in a construction set before converting the instructions into piece numbers.' },
  { number: '4', title: 'Build a baseline', standard: 'Generate from random weights and train the simplest plausible model before adding transformer complexity.', why: 'Without a weak but measured starting point, extra layers can look sophisticated while adding no real capability.', explain: 'Run the untrained model, then the simplest trained architecture that can address the task. Preserve its metrics and outputs for every later comparison.', picture: 'Time a basic bicycle around the course before judging an elaborate new design.' },
  { number: '5', title: 'Train', standard: 'Predict next tokens, measure loss, backpropagate gradients and let an optimiser update weights.', why: 'Construction creates adjustable numbers but does not set them usefully. Training connects prediction mistakes to small changes in those numbers.', explain: 'For each batch: calculate logits, score correct targets with loss, differentiate loss with respect to every weight, apply an optimiser update, then repeat.', picture: 'Attempt a worksheet, calculate one error score, attach correction arrows to thousands of dials, and turn them slightly.' },
  { number: '6', title: 'Checkpoint', standard: 'Save comparable snapshots so we can inspect emergence and safely resume interrupted work.', why: 'The path of learning contains evidence that a final checkpoint alone cannot show, and long work should not vanish after interruption.', explain: 'At fixed steps, save weights and identifying metadata; where exact resume matters, also save optimiser and random state. Generate comparison samples with fixed settings.', picture: 'Create labelled save-game slots and take photographs from the same camera position.' },
  { number: '7', title: 'Evaluate', standard: 'Use held-out loss plus task-relevant measures and representative generations.', why: 'Training scores reward fitting practice examples, while one attractive generation is easy to cherry-pick.', explain: 'Freeze one protocol and apply it to every candidate: same withheld data, metrics, sampling rules, prompts, and seeds. Read quantitative and qualitative evidence together.', picture: 'Give every candidate the same written exam and the same practical test.' },
  { number: '8', title: 'Change one thing', standard: 'Run a controlled experiment, record the configuration, and compare it with the baseline.', why: 'If several variables move together, even a clear improvement cannot tell us which idea caused it.', explain: 'Keep relevant conditions fixed, alter one named factor, rerun the full measurement, record costs and caveats, then choose the next question from evidence.', picture: 'Change one ingredient in one cake while holding the oven, quantities, and judging rule constant.' },
];

export default function TrainingLifecycle() {
  return <WikiChrome active="path"><article className="article-page">
    <div className="breadcrumbs"><Link href="/">Dashboard</Link><span>/</span><strong>Learning path</strong></div>
    <header className="article-hero single"><div><p className="kicker">THE REPEATABLE LOOP</p><h1>From raw text to evidence</h1><p>Every project follows the same scientific shape. The models and datasets change; the discipline of making comparable, reproducible experiments does not.</p></div></header>
    <LearningVisual title="The course’s recurring causal chain" description="Training changes weights; checkpointing preserves them; evaluation observes them without further updates." kind="cycle" steps={[
      { label: 'Text → tokens', detail: 'Create numerical model inputs', tone: 'input' },
      { label: 'Logits → loss', detail: 'Score next-token predictions', tone: 'warning' },
      { label: 'Gradients → updates', detail: 'Change trainable weights', tone: 'process' },
      { label: 'Checkpoint → evaluation', detail: 'Save and measure the resulting state', tone: 'evidence' },
    ]} footer="Inference uses the saved weights to generate; it does not continue the correction loop." />
    <BeginnerOnly className="beginner-lesson-intro"><p className="kicker">BEGINNER MODE · THE BIG PICTURE</p><h2>Training is a correction loop, not a knowledge upload</h2><p>We do not place rules or sentences directly inside the model. We arrange a prediction exercise, calculate how poor its probability assignments were, and repeatedly adjust numerical weights. Separate evaluation tells us whether those adjustments help on text excluded from practice.</p><div className="beginner-intro-grid"><section><strong>Think like a coach</strong><p>Prepare → practise → score → correct → save → examine → change one condition.</p></section><section><strong>Do not overread the metaphor</strong><p>The model is not a pupil with beliefs or motivation. “Practice” and “correction” name numerical forward passes, loss calculations, gradients, and updates.</p></section></div></BeginnerOnly>
    <section className="lifecycle">{steps.map(step => <article key={step.number}><span>{step.number}</span><div><h2>{step.title}</h2><p>{step.standard}</p><BeginnerOnly className="lifecycle-plain"><dl><div><dt>Why</dt><dd>{step.why}</dd></div><div><dt>What happens</dt><dd>{step.explain}</dd></div><div><dt>Picture it</dt><dd>{step.picture}</dd></div></dl></BeginnerOnly></div></article>)}</section>
    <aside className="principle-card"><p className="kicker">CORE PRINCIPLE</p><h2>Never improve a model you have not measured.</h2><p>A simple baseline makes progress legible. Without it, added complexity may produce more impressive-looking code without producing a better model.</p></aside>
  </article></WikiChrome>;
}
